Repository magento/inventory, pull requests merged in 2018-04, with the labels that each got.

#807 MSI-791: Incorrect salable quantity calculation.
  app/code/Magento/InventoryCatalog/Plugin/InventoryReservationsApi/ApplyDataToLegacyCatalogInventoryAtReservationPlacingPlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/InventoryReservationsApi/ApplyDataToLegacyStockItemAtReservationPlacingTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/InventoryReservationsApi/ApplyDataToLegacyStockStatusAtReservationPlacingTest.php
  app/code/Magento/InventoryCatalog/etc/di.xml
Labels: Bugfixing, current sprint

#766 MSI-765: RSS feed works incorrect
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyBaseJoins.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyNameAttributeCondition.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyNameAttributeJoin.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyStatusAttributeJoin.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/SelectBuilder.php
Labels: Bugfixing

#710 MSI: 333: Investigate and fix problem with OnePageCheckoutOfflinePaym…
  dev/tests/functional/tests/app/Magento/Checkout/Test/TestCase/OnePageCheckoutOfflinePaymentMethodsTest.php
Labels: WIP

#769 MSI-757: Add Inventory Index invalidation when Source is enabled or disabled.
  app/code/Magento/InventoryIndexer/Model/ResourceModel/GetStockItemData.php
  app/code/Magento/InventoryIndexer/Model/ResourceModel/IsInvalidationRequiredForSource.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/InvalidateAfterEnablingOrDisablingSourcePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/InvalidateAfterStockSourceLinksDeletePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/InvalidateAfterStockSourceLinksSavePlugin.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/SourceIndexerTest.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/SourceItemIndexerTest.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/StockIndexerTest.php
  app/code/Magento/InventoryIndexer/Test/Integration/InvalidateAfterEnablingOrDisablingSourceTest.php
  app/code/Magento/InventoryIndexer/Test/_files/reindex_inventory.php
  app/code/Magento/InventoryIndexer/etc/di.xml
Labels: WIP, current sprint

#830 MSI-829: No Reservations should be placed when cataloginventory/options/can_subtract set to 0.
  app/code/Magento/InventorySales/Plugin/InventoryReservationsApi/PreventAppendReservationOnNotManageItemsInStockPlugin.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnCanSubtractQtySetToZeroTest.php
  app/code/Magento/InventorySales/etc/adminhtml/system.xml
Labels: Bugfixing, WIP, current sprint

#871 Refacoring: Source Selection Algoritm on Shipping page - call by all requestedItems
  app/code/Magento/InventoryShipping/Controller/Adminhtml/Algorithm/GetSources.php
Labels: Refactoring, acknowledged

#788 Source deduction
  app/code/Magento/InventoryShipping/Block/Adminhtml/Order/View/ShipButton.php
  app/code/Magento/InventoryShipping/Block/Adminhtml/Shipment/AlgorithmSelectionButton.php
  app/code/Magento/InventoryShipping/Block/Adminhtml/Shipment/Inventory.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/Index.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/ProcessAlgorithm.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/Validate.php
  app/code/Magento/InventoryShipping/Model/ResourceModel/ShipmentSource/DeleteShipmentSource.php
  app/code/Magento/InventoryShipping/Model/ResourceModel/ShipmentSource/GetSourceCodeByShipmentId.php
  app/code/Magento/InventoryShipping/Model/ResourceModel/ShipmentSource/SaveShipmentSource.php
  app/code/Magento/InventoryShipping/Model/ShipmentProvider.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/ItemToDeduct.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/ItemToDeductInterface.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequest.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequestInterface.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionServiceInterface.php
  app/code/Magento/InventoryShipping/Observer/NewShipmentLoadBefore.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/Plugin/Sales/Block/Order/Invoice/Create/DisallowCreateShipmentPlugin.php
  app/code/Magento/InventoryShipping/Plugin/Sales/CollectSourcesForShipmentItems.php
  app/code/Magento/InventoryShipping/Plugin/Sales/ResourceModel/Order/Shipment/DeleteSourceForShipmentPlugin.php
  app/code/Magento/InventoryShipping/Plugin/Sales/ResourceModel/Order/Shipment/LoadSourceForShipmentPlugin.php
  app/code/Magento/InventoryShipping/Plugin/Sales/ResourceModel/Order/Shipment/SaveSourceForShipmentPlugin.php
  app/code/Magento/InventoryShipping/Plugin/Sales/Shipment/AssignSourceCodeToShipmentPlugin.php
  app/code/Magento/InventoryShipping/Plugin/Sales/Shipment/Block/Adminhtml/Create/AddInventoryBlockRenderPlugin.php
  app/code/Magento/InventoryShipping/Setup/Operation/AssignDefaultSourceToShipments.php
  app/code/Magento/InventoryShipping/Setup/Patch/InitializeDefaultSourceForShipments.php
  app/code/Magento/InventoryShipping/Ui/Component/Control/SourceSelection/AlgorithmSelectionButton.php
  app/code/Magento/InventoryShipping/Ui/DataProvider/SourceSelectionDataProvider.php
  app/code/Magento/InventoryShipping/composer.json
  app/code/Magento/InventoryShipping/etc/adminhtml/di.xml
  app/code/Magento/InventoryShipping/etc/db_schema.xml
  app/code/Magento/InventoryShipping/etc/db_schema_whitelist.json
  app/code/Magento/InventoryShipping/etc/di.xml
  app/code/Magento/InventoryShipping/etc/events.xml
  app/code/Magento/InventoryShipping/etc/extension_attributes.xml
  app/code/Magento/InventoryShipping/view/adminhtml/layout/adminhtml_order_shipment_new.xml
  app/code/Magento/InventoryShipping/view/adminhtml/layout/inventoryshipping_sourceselection_index.xml
  app/code/Magento/InventoryShipping/view/adminhtml/layout/sales_order_view.xml
  app/code/Magento/InventoryShipping/view/adminhtml/templates/shipment/button_script.phtml
  app/code/Magento/InventoryShipping/view/adminhtml/templates/shipment/inventory.phtml
  app/code/Magento/InventoryShipping/view/adminhtml/templates/shipment/items/default.phtml
  app/code/Magento/InventoryShipping/view/adminhtml/ui_component/inventory_shipping_source_selection_form.xml
  app/code/Magento/InventoryShipping/view/adminhtml/web/js/form/element/qty_to_deduct.js
  app/code/Magento/InventoryShipping/view/adminhtml/web/js/form/element/sourceCode.js
  app/code/Magento/InventoryShipping/view/adminhtml/web/js/form/form.js
  app/code/Magento/Sales/Model/Order/ShipmentFactory.php
  app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/NewAction.php
  app/code/Magento/Shipping/Model/ShipmentProvider.php
  app/code/Magento/Shipping/Model/ShipmentProviderInterface.php
  app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/Shipment/NewActionTest.php
  app/code/Magento/Shipping/etc/adminhtml/di.xml
  dev/tests/integration/testsuite/Magento/Sales/Model/Order/Email/Sender/ShipmentSenderTest.php
  dev/tests/integration/testsuite/Magento/Sales/Model/Order/ShipmentTest.php
  dev/tests/integration/testsuite/Magento/Sales/_files/shipment.php
  dev/tests/integration/testsuite/Magento/Sales/_files/shipment_comments_for_search.php
  dev/tests/integration/testsuite/Magento/Sales/_files/shipment_items_for_search.php
  dev/tests/integration/testsuite/Magento/Sales/_files/shipment_list.php
  dev/tests/integration/testsuite/Magento/Sales/_files/shipment_tracks_for_search.php
Labels: WIP, complex, special achievement, test coverage

#900 Add OrderId into the Metadata attribute of Reservation entity
  app/code/Magento/InventoryConfiguration/Model/StockItemConfiguration.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsCorrectQtyCondition.php
  app/code/Magento/InventorySales/Model/ItemToSell.php
  app/code/Magento/InventorySales/Model/PlaceReservationsForSalesEvent.php
  app/code/Magento/InventorySales/Model/SalesEvent.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRegisterProductsSalePlugin.php
  app/code/Magento/InventorySales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnNotDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRegisterProductsSaleTest.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Api/Data/ItemToSellInterface.php
  app/code/Magento/InventorySalesApi/Api/Data/SalesEventInterface.php
  app/code/Magento/InventorySalesApi/Api/PlaceReservationsForSalesEventInterface.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequest.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequestInterface.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/composer.json
Labels: MageTitansCD, WIP, complex

#819 MSI-810: Exception should be thrown when Stock Source Link related to Default Stock is saved or deleted.
  app/code/Magento/InventoryCatalog/Model/StockSourceLink/Validator/AssignDefaultSourceToNonDefaultStockValidator.php
  app/code/Magento/InventoryCatalog/Model/StockSourceLink/Validator/AssignToDefaultStockDefaultSourceValidator.php
  app/code/Magento/InventoryCatalog/Plugin/Inventory/Stock/StockSaveProcessor/PreventProcessDefaultStockLinksPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/StockSourceLinksDelete/PreventDeleteDefaultStockLinksPlugin.php
  app/code/Magento/InventoryCatalog/Setup/Operation/AssignDefaultSourceToDefaultStock.php
  app/code/Magento/InventoryCatalog/etc/di.xml
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/InvalidateAfterStockSourceLinksDeletePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/InvalidateAfterStockSourceLinksSavePlugin.php
Labels: WIP

#922 Source Selection in separate module
  app/code/Magento/InventoryShipping/Block/Adminhtml/Order/View/Tab/SourceSelection.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/ProcessAlgorithm.php
  app/code/Magento/InventoryShipping/Ui/Component/Control/SourceSelection/AlgorithmSelectionButton.php
  app/code/Magento/InventoryShipping/Ui/DataProvider/SourceSelectionDataProvider.php
  app/code/Magento/InventoryShipping/composer.json
  app/code/Magento/InventoryShipping/etc/di.xml
  app/code/Magento/InventorySourceSelection/LICENSE.txt
  app/code/Magento/InventorySourceSelection/LICENSE_AFL.txt
  app/code/Magento/InventorySourceSelection/Model/Algorithms/PriorityBasedAlgorithm.php
  app/code/Magento/InventorySourceSelection/Model/GetDefaultSourceSelectionAlgorithmCode.php
  app/code/Magento/InventorySourceSelection/Model/GetDefaultSourceSelectionAlgorithmCodeInterface.php
  app/code/Magento/InventorySourceSelection/Model/GetSourceSelectionAlgorithmList.php
  app/code/Magento/InventorySourceSelection/Model/InventoryRequestFromOrderFactory.php
  app/code/Magento/InventorySourceSelection/Model/Request/InventoryRequest.php
  app/code/Magento/InventorySourceSelection/Model/Request/ItemRequest.php
  app/code/Magento/InventorySourceSelection/Model/Result/SourceSelectionItem.php
  app/code/Magento/InventorySourceSelection/Model/Result/SourceSelectionResult.php
  app/code/Magento/InventorySourceSelection/Model/SourceSelectionAlgorithm.php
  app/code/Magento/InventorySourceSelection/Model/SourceSelectionInterface.php
  app/code/Magento/InventorySourceSelection/Model/SourceSelectionService.php
  app/code/Magento/InventorySourceSelection/README.md
  app/code/Magento/InventorySourceSelection/composer.json
  app/code/Magento/InventorySourceSelection/etc/di.xml
  app/code/Magento/InventorySourceSelection/etc/module.xml
  app/code/Magento/InventorySourceSelection/registration.php
  app/code/Magento/InventorySourceSelectionApi/Api/Data/InventoryRequestInterface.php
  app/code/Magento/InventorySourceSelectionApi/Api/Data/ItemRequestInterface.php
  app/code/Magento/InventorySourceSelectionApi/Api/Data/SourceSelectionAlgorithmInterface.php
  app/code/Magento/InventorySourceSelectionApi/Api/Data/SourceSelectionResultInterface.php
  app/code/Magento/InventorySourceSelectionApi/Api/GetSourceSelectionAlgorithmListInterface.php
  app/code/Magento/InventorySourceSelectionApi/Api/SourceSelectionServiceInterface.php
  app/code/Magento/InventorySourceSelectionApi/Test/Api/GetSourceSelectionAlgorithmListTest.php
  app/code/Magento/InventorySourceSelectionApi/Test/Api/SourceSelectionServiceTest.php
  app/code/Magento/InventorySourceSelectionApi/etc/webapi.xml
  composer.json
  composer.lock
Labels: complex, special achievement, test coverage

#972 MSI-971: Typo in InventoryCatalog Integration test.
  app/code/Magento/InventoryCatalog/Test/Integration/IsSingleSourceModeTest.php
Labels: current sprint

#924 MSI-885: Options on Storefront Product View Page for Configurable Product Assigned to Custom Stock are Empty.
  app/code/Magento/InventoryConfigurableProduct/Plugin/Model/ResourceModel/Attribute/IsSalableOptionSelectBuilder.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Options/OptionsAvailabilityTest.php
  app/code/Magento/InventoryConfigurableProduct/composer.json
  app/code/Magento/InventoryConfigurableProduct/etc/frontend/di.xml
Labels: current sprint

#944 MSI-886: Need to move ReservationBuilderInterface to ReservationApi module.
  app/code/Magento/InventoryReservations/Model/ReservationBuilder.php
  app/code/Magento/InventoryReservations/etc/di.xml
  app/code/Magento/InventoryReservationsApi/Api/ReservationBuilderInterface.php
  app/code/Magento/InventorySales/Model/PlaceReservationsForSalesEvent.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessBackItemQtyPlugin.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRevertProductsSalePlugin.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/Stock/GetProductSalableQtyTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringBackItemQtyTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRegisterProductsSaleTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRevertProductsSaleTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnCanSubtractQtySetToZeroTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnUseConfigManageStockSetToZeroTest.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php
  app/code/Magento/InventoryShipping/composer.json
Labels: current sprint

#974 MSI-887: Resolve dependency on Inventory Module because of reference to a resource for permission.
  app/code/Magento/Inventory/Controller/Adminhtml/Source/Edit.php
  app/code/Magento/Inventory/Controller/Adminhtml/Source/Index.php
  app/code/Magento/Inventory/Controller/Adminhtml/Source/InlineEdit.php
  app/code/Magento/Inventory/Controller/Adminhtml/Source/NewAction.php
  app/code/Magento/Inventory/Controller/Adminhtml/Source/Save.php
  app/code/Magento/Inventory/Controller/Adminhtml/Stock/Delete.php
  app/code/Magento/Inventory/Controller/Adminhtml/Stock/Edit.php
  app/code/Magento/Inventory/Controller/Adminhtml/Stock/Index.php
  app/code/Magento/Inventory/Controller/Adminhtml/Stock/InlineEdit.php
  app/code/Magento/Inventory/Controller/Adminhtml/Stock/MassDelete.php
  app/code/Magento/Inventory/Controller/Adminhtml/Stock/NewAction.php
  app/code/Magento/Inventory/Controller/Adminhtml/Stock/Save.php
  app/code/Magento/Inventory/etc/adminhtml/menu.xml
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/Index.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/ProcessAlgorithm.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/Validate.php
  app/code/Magento/InventoryShipping/composer.json
Labels: current sprint

#948 MSI-640 / 430 Source Deduction Improvements
  app/code/Magento/InventoryShipping/Block/Adminhtml/Order/View/ShipButton.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/Index.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/ProcessAlgorithm.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/Validate.php
  app/code/Magento/InventoryShipping/Model/IsMultiSourceMode.php
  app/code/Magento/InventoryShipping/Observer/GetItemsToDeduct.php
  app/code/Magento/InventoryShipping/Observer/NewShipmentLoadBefore.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/Plugin/Sales/Shipment/Block/Adminhtml/BackButtonUrlOnNewShipmentPagePlugin.php
  app/code/Magento/InventoryShipping/Plugin/Sales/Shipment/Block/Adminhtml/Create/AddInventoryBlockRenderPlugin.php
  app/code/Magento/InventoryShipping/Ui/Component/Control/SourceSelection/BackButton.php
  app/code/Magento/InventoryShipping/Ui/DataProvider/GetSourcesByStockIdSkuAndQty.php
  app/code/Magento/InventoryShipping/Ui/DataProvider/SourceSelectionDataProvider.php
  app/code/Magento/InventoryShipping/etc/di.xml
  app/code/Magento/InventoryShipping/view/adminhtml/ui_component/inventory_shipping_source_selection_form.xml
  app/code/Magento/InventoryShipping/view/adminhtml/web/js/form/element/qty_to_deduct.js
  app/code/Magento/InventoryShipping/view/adminhtml/web/js/form/element/sourceCode.js
  app/code/Magento/InventoryShipping/view/adminhtml/web/js/form/form.js
Labels: WIP, complex, special achievement

#914 MSI-891: Stock status title is visible on "Advanced Inventory" in multi source mode
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/AdvancedInventory.php
Labels: Bugfixing

#987 Source Deduction improvements
  app/code/Magento/InventoryShipping/Observer/GetItemsToDeduct.php
  app/code/Magento/InventoryShipping/view/adminhtml/ui_component/inventory_shipping_source_selection_form.xml
Labels: special achievement

#970 MSI-918: Need to refactor test ReservationPlacingDuringRegisterProductsSaleTest::testRegisterProductsSale as we don't make source deduction at the time of RegisterSales Anymore.
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRegisterProductsSaleTest.php
Labels: current sprint

#841 [PR] MSI: 619: MFTF Tests for MSI - Part 2
  app/code/Magento/Inventory/Test/Acceptance/LICENSE.txt
  app/code/Magento/Inventory/Test/Acceptance/LICENSE_AFL.txt
  app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageSourcesPage.xml
  app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageStockPage.xml
  app/code/Magento/Inventory/Test/Acceptance/README.md
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminAssignSourcesSlideOutSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesEditFormSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesGridSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageStockFormSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageStockGridSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminProductSourcesFormSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddConfigurableProductWithDropDownAttributeAndDefaultSourceTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddMultipleSourcesToProductTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddRemoveSourceColumnsTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminAddRemoveStockColumnsTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminAssignMultipleSourcesToStockTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminCreateNewSourceTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminCreateNewStockWithNoSourceOrSalesChannelTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminCreateNewWebsiteWithStoreAndStoreViewTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminCreateSimpleProductWithDefaultSourceTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminDefaultStockCannotBeDeletedTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminFilterSourcesInGridTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminFilterStocksInGridTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminManageSourcesSearchByKeywordTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminManageStocksSearchByKeywordTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminMultipleWebsitesAssignedAsSaleChannelsToStockTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminNewWebsiteHasDefaultStockAssignedAutomaticallyTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminSourceForEachQuantityCanBeSetByAdminTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminStockCannotBeDeletedWhenSalesChannelIsAssignedTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminStockDeletedFromGridWhenNoSalesChannelsAssignedTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminUpdateSimpleProductQuantityViaTheAdminTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminUpdateSourceDataTest.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminUpdateStockDataTest.xml
  app/code/Magento/Inventory/Test/Acceptance/composer.json
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiProductData.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiSourceData.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiStockData.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiStoreData.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiStoreViewData.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiWebsiteData.xml
  app/code/Magento/InventoryApi/Test/Acceptance/LICENSE.txt
  app/code/Magento/InventoryApi/Test/Acceptance/LICENSE_AFL.txt
  app/code/Magento/InventoryApi/Test/Acceptance/Metadata/source-meta.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Metadata/stock-meta.xml
  app/code/Magento/InventoryApi/Test/Acceptance/README.md
  app/code/Magento/InventoryApi/Test/Acceptance/composer.json
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Metadata/store-meta.xml
  dev/tests/static/testsuite/Magento/Test/Integrity/Xml/SchemaTest.php
  dev/tests/static/testsuite/Magento/Test/Php/_files/blacklist/code_freeze.txt
Labels: WIP

#996 MSI-875: issue with duplicating SKU in one Order
  app/code/Magento/InventorySales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php
Labels: Imagine2018

#995 Msi 920 bis
  app/code/Magento/InventorySales/Model/CheckItemsQuantity.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRegisterProductsSalePlugin.php
  app/code/Magento/InventorySales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php
  app/code/Magento/InventoryShipping/composer.json
  dev/tests/integration/testsuite/Magento/Signifyd/_files/order_with_customer_and_two_simple_products.php
Labels: Imagine2018, WIP

#975 Adapt logic backItemQty and RevertQuote for new API
  app/code/Magento/InventorySales/Model/CheckItemsQuantity.php
  app/code/Magento/InventorySales/Model/PlaceReservationsForSalesEvent.php
  app/code/Magento/InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
  app/code/Magento/InventorySales/Observer/CatalogInventory/RevertQuoteInventoryObserver.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRegisterProductsSalePlugin.php
  app/code/Magento/InventorySales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventorySales/etc/events.xml
  app/code/Magento/InventorySalesApi/Api/Data/SalesEventInterface.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequest.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequestInterface.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/composer.json
  dev/tests/integration/testsuite/Magento/Signifyd/_files/order_with_customer_and_two_simple_products.php
Labels: Imagine2018, WIP, advanced, current sprint, special achievement

#938 MSI-912: Fatal error when creating the Shipment during Invoice for the Bundle and Grouped product
  app/code/Magento/InventorySales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php
  app/code/Magento/InventoryShipping/Observer/GetItemsToDeduct.php
  app/code/Magento/InventoryShipping/Test/Integration/SourceDeductionForBundleProductsOnDefaultStockTest.php
  app/code/Magento/InventoryShipping/Test/_files/order_bundle_products.php
  app/code/Magento/InventoryShipping/Test/_files/order_bundle_products_rollback.php
  app/code/Magento/InventoryShipping/Test/_files/products_bundle.php
  app/code/Magento/InventoryShipping/Test/_files/products_bundle_rollback.php
  app/code/Magento/InventoryShipping/Test/_files/source_items_for_bundle_children.php
Labels: Kharkiv Contribution Day

#994 MSI-666: replicate source items
  app/code/Magento/InventoryCatalogAdminUi/Plugin/Catalog/CopySourceItemsPlugin.php
  app/code/Magento/InventoryCatalogAdminUi/etc/adminhtml/di.xml
Labels: Imagine2018

#999 add sorting by source name to the source item grid dataprovider
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItems.php
Labels: Imagine2018
