Repository magento/inventory, pull requests merged in 2018-07, with the labels that each got.

#1423 MSI-1372 When you set 'Manage Inventory' to No it will still remembe…
  app/code/Magento/InventorySalesAdminUi/Model/GetSalableQuantityDataBySku.php
  app/code/Magento/InventorySalesAdminUi/view/adminhtml/web/template/product/grid/cell/salable-quantity.html
Labels: Dare to Share

#1450 MSI-1411-1421: prevent copy/paste test for fixtures
  dev/tests/static/testsuite/Magento/Test/Php/_files/phpcpd/blacklist/common.txt
Labels: Atwix Contribution Day, Atwix Contribution Day 2018

#1457 MSI-1431: Make SourceDeductionServiceInterface service as the only extension point
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessBackItemQtyToSource.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessRefundItems.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/BackItemQtyRequest.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventoryShipping/Model/GetItemsToDeductFromShipment.php
  app/code/Magento/InventoryShipping/Model/GetSourceSelectionResultFromInvoice.php
  app/code/Magento/InventoryShipping/Model/SourceDeductionRequestFromShipmentFactory.php
  app/code/Magento/InventoryShipping/Model/SourceDeductionRequestsFromSourceSelectionFactory.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/Observer/VirtualSourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/composer.json
  app/code/Magento/InventoryShipping/etc/di.xml
  app/code/Magento/InventorySourceDeductionApi/LICENSE.txt
  app/code/Magento/InventorySourceDeductionApi/LICENSE_AFL.txt
  app/code/Magento/InventorySourceDeductionApi/Model/GetSourceItemBySourceCodeAndSku.php
  app/code/Magento/InventorySourceDeductionApi/Model/ItemToDeduct.php
  app/code/Magento/InventorySourceDeductionApi/Model/ItemToDeductInterface.php
  app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionRequest.php
  app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionRequestInterface.php
  app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php
  app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionServiceInterface.php
  app/code/Magento/InventorySourceDeductionApi/README.md
  app/code/Magento/InventorySourceDeductionApi/composer.json
  app/code/Magento/InventorySourceDeductionApi/etc/di.xml
  app/code/Magento/InventorySourceDeductionApi/etc/module.xml
  app/code/Magento/InventorySourceDeductionApi/registration.php
  composer.json
  composer.lock
Labels: QA Passed, WIP

#1388 #1378 Fix for Error in fixture
  app/code/Magento/InventorySourceSelectionApi/Test/Api/SourceSelectionServiceTest.php
Labels: Bugfixing, WEB API

#1452 MSI-1440: There are no checks that prevent lost of the last association between Stock and Sales Channels when merchant tries to Save the Stock
  app/code/Magento/InventorySales/Model/GetUnassignedSalesChannelsForStock.php
  app/code/Magento/InventorySales/Plugin/InventoryApi/StockRepository/SaveSalesChannelsLinksPlugin.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesAdminUi/Model/SalesChannelNameResolverInterface.php
  app/code/Magento/InventorySalesAdminUi/Model/WebsiteNameResolver.php
  app/code/Magento/InventorySalesAdminUi/Plugin/InventoryApi/StockRepository/AddNoticeForUnassignedSalesChannels.php
  app/code/Magento/InventorySalesAdminUi/Ui/Component/Listing/Column/SalesChannels.php
  app/code/Magento/InventorySalesAdminUi/etc/adminhtml/di.xml
  app/code/Magento/InventorySalesAdminUi/view/adminhtml/ui_component/inventory_stock_form.xml
  app/code/Magento/InventorySalesApi/Test/Api/StockRepository/AssignSalesChannelTest.php
  app/code/Magento/InventorySalesApi/Test/Api/StockRepository/SalesChannelManagementTest.php
Labels: Atwix Contribution Day 2018, Bugfixing, WIP

#1459 Allow negative min_qty
  app/code/Magento/InventoryCatalog/Plugin/Catalog/Controller/Adminhtml/Product/Initialization/StockDataFilter/AllowNegativeMinQtyPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/Data/StockItemInterface/AdaptMinQtyToBackordersPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Model/StockStateProvider/AdaptVerifyStockToNegativeMinQtyPlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/NegativeMinQtyTest.php
  app/code/Magento/InventoryCatalog/etc/di.xml
  app/code/Magento/InventoryConfiguration/Plugin/CatalogInventory/Model/System/Config/Backend/Minqty/AllowNegativeMinQtyInConfigPlugin.php
  app/code/Magento/InventoryConfiguration/etc/di.xml
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/BackOrderCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php
  app/code/Magento/InventorySales/Model/ResourceModel/IsStockItemSalableCondition/BackordersCondition.php
  app/code/Magento/InventorySalesFrontendUi/Plugin/Block/Stockqty/AbstractStockqtyPlugin.php
  dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Backend/ControllerAclTest.php
Labels: QA Passed, WIP

#1443 Product grid mass inventory actions
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryApi/etc/di.xml
  app/code/Magento/InventoryCatalog/Model/BulkInventoryTransfer.php
  app/code/Magento/InventoryCatalog/Model/BulkSourceAssign.php
  app/code/Magento/InventoryCatalog/Model/BulkSourceUnassign.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkInventoryTransfer.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkSourceAssign.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkSourceUnassign.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkZeroLegacyStockItem.php
  app/code/Magento/InventoryCatalog/Model/Source/Validator/Bulk/AssignSourcesValidator.php
  app/code/Magento/InventoryCatalog/Model/Source/Validator/Bulk/TransferSourceValidator.php
  app/code/Magento/InventoryCatalog/Model/Source/Validator/Bulk/UnassignSourcesValidator.php
  app/code/Magento/InventoryCatalog/Test/Integration/Bulk/InventoryTransferTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/Bulk/InventoryTransferValidatorTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/Bulk/SourceAssignTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/Bulk/SourceAssignValidatorTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/Bulk/SourceUnassignTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/Bulk/SourceUnassignValidatorTest.php
  app/code/Magento/InventoryCatalog/etc/di.xml
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Inventory/BulkTransfer.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Inventory/BulkTransferPost.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssign.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssignPost.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkUnassign.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkUnassignPost.php
  app/code/Magento/InventoryCatalogAdminUi/Model/BulkSessionProductsStorage.php
  app/code/Magento/InventoryCatalogAdminUi/ViewModel/InventoryTransfer.php
  app/code/Magento/InventoryCatalogAdminUi/ViewModel/SourcesSelection.php
  app/code/Magento/InventoryCatalogAdminUi/composer.json
  app/code/Magento/InventoryCatalogAdminUi/etc/adminhtml/routes.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/layout/inventorycatalog_inventory_bulktransfer.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/layout/inventorycatalog_source_bulkassign.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/layout/inventorycatalog_source_bulkunassign.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/templates/assign_notice.phtml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/templates/inventory_transfer.phtml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/templates/source_selection.phtml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/templates/unassign_notice.phtml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/product_listing.xml
  app/code/Magento/InventoryCatalogApi/Api/BulkInventoryTransferInterface.php
  app/code/Magento/InventoryCatalogApi/Api/BulkSourceAssignInterface.php
  app/code/Magento/InventoryCatalogApi/Api/BulkSourceUnassignInterface.php
  app/code/Magento/InventoryCatalogApi/Model/BulkInventoryTransferValidatorChain.php
  app/code/Magento/InventoryCatalogApi/Model/BulkInventoryTransferValidatorInterface.php
  app/code/Magento/InventoryCatalogApi/Model/BulkSourceAssignValidatorChain.php
  app/code/Magento/InventoryCatalogApi/Model/BulkSourceAssignValidatorInterface.php
  app/code/Magento/InventoryCatalogApi/Model/BulkSourceUnassignValidatorChain.php
  app/code/Magento/InventoryCatalogApi/Model/BulkSourceUnassignValidatorInterface.php
  app/code/Magento/InventoryCatalogApi/etc/di.xml
  app/code/Magento/InventoryCatalogApi/etc/webapi.xml
Labels: Award: advanced, Award: special achievement, QA Passed
