Repository magento/inventory, pull requests merged in 2018-09, with the labels that each got.

#1374 MSI-962: MFTF Test for Configurable Product created with text swatch attribute…
  app/code/Magento/Inventory/Test/Mftf/Test/AdminAddConfigurableProductWithTextSwatchAttributeAndDefaultSourceTest.xml
  app/code/Magento/InventoryBundleProduct/Test/Mftf/Section/StorefrontProductInfoMainSection.xml
  app/code/Magento/InventoryCatalog/Test/Mftf/Data/CatalogData.xml
  app/code/Magento/InventoryConfigurableProduct/Test/Mftf/Data/ProductConfigurableAttributeData.xml
  app/code/Magento/InventoryConfigurableProductAdminUi/Test/Mftf/Section/AdminCreateProductConfigurationsPanelSection.xml
  app/code/Magento/InventoryConfigurableProductAdminUi/Test/Mftf/Section/AdminNewAttributePanelSection.xml
Labels: MFTF (Functional Test Coverage)

#1453 1451 avoid fading assign sources listing when advanced inventory manage stock being changed
  app/code/Magento/InventoryCatalogAdminUi/Model/CanManageSourceItemsBySku.php
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItems.php
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/js/product/form/source-items.js
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/view/adminhtml/web/js/components/notify-stock-qty.js
Labels: Atwix Contribution Day 2018, QA Passed

#1648 Issue 863 mass actions async api
  app/code/Magento/Inventory/Model/GetSourceCodesBySkus.php
  app/code/Magento/Inventory/Model/ResourceModel/GetSourceCodesBySkus.php
  app/code/Magento/Inventory/Test/Integration/GetSourceCodesBySkusTest.php
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryApi/Model/GetSourceCodesBySkusInterface.php
  app/code/Magento/InventoryCatalog/Model/BulkInventoryTransfer.php
  app/code/Magento/InventoryCatalog/Model/BulkSourceUnassign.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkInventoryTransfer.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkSourceUnassign.php
  app/code/Magento/InventoryCatalog/Test/Integration/Bulk/InventoryTransferTest.php
  app/code/Magento/InventoryCatalog/etc/config.xml
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Bulk/BulkPageProcessor.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Inventory/BulkTransfer.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Inventory/BulkTransferPost.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssign.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssignPost.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkUnassign.php
  app/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkUnassignPost.php
  app/code/Magento/InventoryCatalogAdminUi/Model/BulkOperationsConfig.php
  app/code/Magento/InventoryCatalogAdminUi/ViewModel/InventoryTransfer.php
  app/code/Magento/InventoryCatalogAdminUi/ViewModel/SourcesSelection.php
  app/code/Magento/InventoryCatalogAdminUi/composer.json
  app/code/Magento/InventoryCatalogAdminUi/etc/adminhtml/system.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/layout/inventorycatalog_inventory_bulktransfer.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/layout/inventorycatalog_source_bulkassign.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/layout/inventorycatalog_source_bulkunassign.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/templates/inventory_transfer.phtml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/templates/source_selection.phtml
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationAssign.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationUnassign.php
  app/code/Magento/InventoryLowQuantityNotification/Plugin/InventoryCatalogApi/BulkConfigurationTransferInterfacePlugin.php
  app/code/Magento/InventoryLowQuantityNotification/Plugin/InventoryCatalogApi/BulkSourceAssignInterfacePlugin.php
  app/code/Magento/InventoryLowQuantityNotification/Test/Integration/Model/ResourceModel/BulkConfigurationAssignTest.php
  app/code/Magento/InventoryLowQuantityNotification/Test/Integration/Model/ResourceModel/BulkConfigurationTransferTest.php
  app/code/Magento/InventoryLowQuantityNotification/Test/Integration/Model/ResourceModel/BulkConfigurationUnassignTest.php
  app/code/Magento/InventoryLowQuantityNotification/etc/di.xml
Labels: QA Failed

#1642 MFTF tests issues
  app/code/Magento/Inventory/Test/Mftf/Test/SkippedTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Suite/msi-suite.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminAddStockToVirtualProductTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontOrderCreatedWithVirtualProductByGuestCustomerTest.xml
Labels: MFTF (Functional Test Coverage), approved

#1671 Alternative FIX for issue #1664 - Decimal qty could be added when not configured
  app/code/Magento/InventoryApi/Test/_files/products.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsCorrectQtyCondition.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsCorrectQtyConditionTest.php
Labels: Award: special achievement
