Repository magento/inventory, pull requests merged in 2018-11, with the labels that each got.

#1803 magento-engcom/msi#1799 [MFTF] Disable source code field
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateNewSourceAndCheckDisableSourceCodeTest.xml
Labels: MFTF (Functional Test Coverage), WIP

#1833 magento-engcom/msi#1778-MSI-MFTF-Test-Cases-10
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/AdminOnProductEditPageAssignSourceToProductActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForBundleProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForConfigurableProductOnTestStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForDownloadableProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForDownloadableProductOnTestStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForGroupedProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForSimpleProductOnTestStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForVirtualProductInSingleStockModeTestst.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForVirtualProductOnTestStockTest.xml
  app/code/Magento/InventoryCatalogSearch/Test/Mftf/Section/CatalogSearchResultSection.xml
Labels: MFTF (Functional Test Coverage), WIP

#1856 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/AdminOnProductEditPageAssignSourceToProductActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForBundleProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForConfigurableProductOnTestStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForDownloadableProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForDownloadableProductOnTestStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForGroupedProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForSimpleProductOnTestStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForVirtualProductInSingleStockModeTestst.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCatalogQuickSearchForVirtualProductOnTestStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateNewSourceAndCheckDisableSourceCodeTest.xml
  app/code/Magento/InventoryCatalogSearch/Test/Mftf/Section/CatalogSearchResultSection.xml
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
  app/code/Magento/InventorySales/Model/GetSkuFromOrderItem.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php
  app/code/Magento/InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessBackItemQtyPlugin.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRevertProductsSalePlugin.php
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Model/GetSkuFromOrderItemInterface.php
  app/code/Magento/InventoryShipping/Model/GetItemsToDeductFromShipment.php
  app/code/Magento/InventoryShipping/Model/GetSourceSelectionResultFromInvoice.php
  app/code/Magento/InventoryShipping/Model/InventoryRequestFromOrderFactory.php
  app/code/Magento/InventoryShippingAdminUi/Ui/DataProvider/SourceSelectionDataProvider.php
  app/code/Magento/InventorySourceDeductionApi/Model/GetSourceItemBySourceCodeAndSku.php
Labels: 2.3.0-release

#1792 magento-engcom/msi#1792 [MFTF] Test Cases Merged
  app/code/Magento/Inventory/Test/Mftf/Test/AdminAddConfigurableProductWithTextSwatchAttributeAndDefaultSourceTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminUseDecimalQuantityOnVirtualProductTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Data/MsiProductData.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Data/MsiStockData.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenDownloadableProductIsSoldOutOnMultipleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenDownloadableProductIsSoldOutOnSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenSimpleProductIsSoldOutOnMultipleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenSimpleProductIsSoldOutOnSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenVirtualProductIsSoldOutOnMultipleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenVirtualProductIsSoldOutOnSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateBundledProductOnSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateDownloadableProductOnSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateDownloadableProductWithCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateDownloadableProductWithDefaultSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateInvoiceForVirtualProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateOrderWithGroupedProductDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateOrderWithSimpleProductWithNewStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminManageSourceGridColumnsSortingTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminManageStockGridColumnsSortingTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminNotifyQuantityUseDefaultAppliedToVirtualProductOnConfigurationAdminPageTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminOrderCreatedForGuestCustomerWithConfigurableProductWithDropDownAttributeViaTheAdminTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminOrderCreatedWithSimpleProductViaTheAdminTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminOutOfStockThresholdAppliedToSimpleInAdvancedInventoryOnProductPageTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminSelectDeselectManipulationsInManageStocksGridTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminSourceForEachQuantityCanBeSetByAdminTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminUpdateVirtualProductQuantityInSingleStockModeViaTheAdminTest.xml
  app/code/Magento/InventoryCatalogAdminUi/Test/Mftf/Test/AdminCreateOrderWithVirtualProductFromTestSourceWithBackordersTest.xml
  app/code/Magento/InventoryGroupedProductAdminUi/Test/Mftf/ActionGroup/AddGroupedProductOptionToOrderActionGroup.xml
Labels: MFTF (Functional Test Coverage), WIP

#1882 MSI-1881 + MSI-1878
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
  app/code/Magento/InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
Labels: QA Passed

#1885 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/Inventory/README.md
  app/code/Magento/InventoryAdminUi/README.md
  app/code/Magento/InventoryApi/README.md
  app/code/Magento/InventoryBundleProduct/README.md
  app/code/Magento/InventoryBundleProductAdminUi/README.md
  app/code/Magento/InventoryCache/README.md
  app/code/Magento/InventoryCatalog/README.md
  app/code/Magento/InventoryCatalogAdminUi/README.md
  app/code/Magento/InventoryCatalogApi/README.md
  app/code/Magento/InventoryCatalogSearch/README.md
  app/code/Magento/InventoryConfigurableProduct/README.md
  app/code/Magento/InventoryConfigurableProductAdminUi/README.md
  app/code/Magento/InventoryConfigurableProductIndexer/README.md
  app/code/Magento/InventoryConfiguration/README.md
  app/code/Magento/InventoryConfigurationApi/README.md
  app/code/Magento/InventoryGroupedProduct/README.md
  app/code/Magento/InventoryGroupedProductAdminUi/README.md
  app/code/Magento/InventoryGroupedProductIndexer/README.md
  app/code/Magento/InventoryImportExport/README.md
  app/code/Magento/InventoryIndexer/README.md
  app/code/Magento/InventoryLowQuantityNotification/README.md
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/README.md
  app/code/Magento/InventoryLowQuantityNotificationApi/README.md
  app/code/Magento/InventoryMultiDimensionalIndexerApi/README.md
  app/code/Magento/InventoryProductAlert/README.md
  app/code/Magento/InventoryReservations/README.md
  app/code/Magento/InventoryReservationsApi/README.md
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessRefundItems.php
  app/code/Magento/InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
  app/code/Magento/InventorySales/README.md
  app/code/Magento/InventorySalesAdminUi/README.md
  app/code/Magento/InventorySalesApi/README.md
  app/code/Magento/InventorySalesFrontendUi/README.md
  app/code/Magento/InventoryShipping/README.md
  app/code/Magento/InventoryShippingAdminUi/README.md
  app/code/Magento/InventorySourceDeductionApi/README.md
  app/code/Magento/InventorySourceSelection/README.md
  app/code/Magento/InventorySourceSelectionApi/README.md
Labels: 2.3.0-release

#1892 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
Labels: 2.3.0-release

#1894 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
  app/code/Magento/InventoryShippingAdminUi/Ui/DataProvider/SourceSelectionDataProvider.php
Labels: 2.3.0-release

#1899 MSI-1895: Fixed wrong refund processing on multi source
  app/code/Magento/InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php
Labels: QA Passed

#1900 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php
Labels: 2.3.0-release

#1904 Release preparation and Regression Bug Fixes
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
Labels: 2.3.0-release

#1916 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/InventoryImportExport/Model/Import/SourceItemConvert.php
Labels: 2.3.0-release

#1917 Double compensational reservation after cancellation of shipped order with bundle product
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
Labels: QA Passed

#1918 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/InventorySales/Model/GetItemsToCancelFromOrderItem.php
Labels: 2.3.0-release
