Repository magento/inventory, pull requests merged in 2018-10, with the labels that each got.

#1717 MSI 1703 - Uncaught Fatal Error from SourceDeductionService during Credit Memo creation
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
  app/code/Magento/InventoryShipping/Model/ReturnProcessor/GetShippedItemsPerSourceByPriority.php
Labels: QA Passed

#1721 Wrong database isolation between tests or missing cleanups
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/BackorderConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/ManageStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/MinQtyConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/BackorderConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsCorrectQtyConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/ManageStockConditionTest.php
Labels: InventoryConfiguration

#1708 MSI-1647: fixed default source notify stock qty use default
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php
Labels: QA Passed

#1719 MSI-1705: No difference between successful and unsuccessful operations for DELETE operation on StockRepositoryInterface
  app/code/Magento/Inventory/Model/Stock/Command/DeleteById.php
Labels: QA Passed, Regression MS2, WEB API

#1739 #1724 Fix Test for DELETE Command for low-quantity-notification
  app/code/Magento/InventoryLowQuantityNotificationApi/Test/Api/DeleteSourceItemConfigurationTest.php
Labels: Award: test coverage

#1731 MFTF test suite optimization
  app/code/Magento/InventoryAdminUi/Test/Mftf/Suite/msi-suite.xml
Labels: MFTF (Functional Test Coverage)

#1757 magento-engcom/msi#1756 [MFTF] Admin Manage Stock Grid Broken Test
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminManageStockGridChangeColumnOrderByDragAndDropTest.xml
Labels: MFTF (Functional Test Coverage)

#1758 magento-engcom/msi#1755 [MFTF] Admin Add Remove Stock Columns Broken Test
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminAddRemoveStockColumnsTest.xml
Labels: MFTF (Functional Test Coverage)

#1785 MSI-1783: 500 error when change source name from grid
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/InlineEdit.php
  app/code/Magento/InventoryAdminUi/Model/Source/SourceCoordinatesDataProcessor.php
  app/code/Magento/InventoryAdminUi/Model/Source/SourceHydrator.php
  app/code/Magento/InventoryAdminUi/Model/Source/SourceRegionDataProcessor.php
Labels: QA Passed

#1818 magento-engcom/msi#1818 [MFTF] Fix test Configurable Product with a text swatch attribute
  app/code/Magento/Inventory/Test/Mftf/Test/AdminAddConfigurableProductWithTextSwatchAttributeAndDefaultSourceTest.xml
Labels: MFTF (Functional Test Coverage)

#1737 MSI-1693: Skip condition chain for products with negative legacy stoc…
  app/code/Magento/InventoryBundleProduct/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventoryBundleProduct/Test/_files/default_stock_bundle_products.php
  app/code/Magento/InventoryBundleProduct/Test/_files/default_stock_bundle_products_rollback.php
  app/code/Magento/InventoryBundleProduct/Test/_files/product_simple_out_of_stock.php
  app/code/Magento/InventoryBundleProduct/Test/_files/product_simple_out_of_stock_rollback.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryConfigurationApi/GetStockItemConfiguration/LoadIsInStockPlugin.php
  app/code/Magento/InventoryCatalog/composer.json
  app/code/Magento/InventoryCatalog/etc/extension_attributes.xml
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/IsProductSalable/IsSalableLegacyStockItemIsInStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/default_stock_configurable_products.php
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForSku.php
  app/code/Magento/InventoryConfiguration/Model/SaveStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/StockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/etc/di.xml
  app/code/Magento/InventoryConfigurationApi/Api/Data/StockItemConfigurationInterface.php
  app/code/Magento/InventoryConfigurationApi/Model/IsSourceItemManagementAllowedForSkuInterface.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsProductSalableConditionChain.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsSetInStockStatusForCompositeProductCondition.php
  app/code/Magento/InventorySales/etc/di.xml
Labels: QA Passed

#1618 Fix issue #1543 Low Stock Report
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/Observer/ProcessSourceItemConfigurationsObserver.php
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/composer.json
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/etc/module.xml
Labels: QA Passed, Top 10 PRs

#1838 MAGETWO-95595: Index names are ignored by declarative schema
  app/code/Magento/Inventory/etc/db_schema.xml
  app/code/Magento/InventoryLowQuantityNotification/etc/db_schema.xml
  app/code/Magento/InventoryReservations/etc/db_schema.xml
  app/code/Magento/InventorySales/etc/db_schema.xml
  app/code/Magento/InventoryShipping/etc/db_schema.xml
Labels: 2.3.0-release

#1842 MSI-1841: Product disappear from category page when manage stock disabled on product and config pages
  app/code/Magento/InventorySales/Model/ResourceModel/IsStockItemSalableCondition/ManageStockCondition.php
Labels: QA Passed

#1844 2.3.0 Release preparation and Regression Bug Fixes
  app/code/Magento/InventorySales/Model/ResourceModel/IsStockItemSalableCondition/ManageStockCondition.php
Labels: 2.3.0-release
