Repository magento/inventory, pull requests merged in 2018-06, with the labels that each got.

#1229 1227: Fix is getSalableQty for Out of Stock products
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetStockStatusBySkuPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetStockStatusPlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusTest.php
  app/code/Magento/InventorySales/Model/GetProductSalableQty.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php
Labels: Bugfixing, regression phase 2

#1283 MSI-1053: Fix naming for Source Deducation API
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequest.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/Request/SourceDeductionRequestInterface.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php
  app/code/Magento/InventoryShipping/Model/SourceDeductionRequestsFromSourceSelectionFactory.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
Labels: MM18NL, regression phase 2

#1292 Issue 1236: support of order operations for deleted from Catlog products
  app/code/Magento/InventoryCatalog/Model/GetProductTypesBySkus.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetProductTypesBySkusTest.php
  app/code/Magento/InventoryCatalogApi/Model/GetProductTypesBySkusInterface.php
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
  app/code/Magento/InventoryIndexer/Indexer/SelectBuilder.php
  app/code/Magento/InventorySales/Model/PlaceReservationsForSalesEvent.php
  app/code/Magento/InventorySales/Model/ResourceModel/IsStockItemSalableCondition/SkuIsAbsentInCatalogCondition.php
  app/code/Magento/InventorySales/Plugin/InventoryReservationsApi/PreventAppendReservationOnNotManageItemsInStockPlugin.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php
  app/code/Magento/InventoryShippingAdminUi/Ui/DataProvider/SourceSelectionDataProvider.php
Labels: Catalog <-> Inventory Product consistency, MM18NL, Top 10 PRs, regression phase 2

#1226 MFTF Tests Batch
  app/code/Magento/Inventory/Test/Mftf/ActionGroup/ChangeAllSourcesStatusActionGroup.xml
  app/code/Magento/Inventory/Test/Mftf/Page/AdminManageSourcesPage.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminManageSourcesGridSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminProductGridSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminProductSourcesFormSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminShipmentInventorySection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminSourceSelectionFormSection.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminAddConfigurableProductWithDropDownAttributeAndCustomSourceTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminAllStocksDeletedFromGridExceptDefault.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminConfigurableProductDisabledManageStockOnCustomStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminConfigurableProductDisabledManageStockOnDefaultStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminConfigurableProductDisabledManageStockOnProductPageCustomStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateInvoiceForVirtualProductInSingleStockMode.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateInvoiceForVirtualProductOnDefaultStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminManageStockOnConfigurationPageTurnedOffForSimpleProduct.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminSourcePrioritySelectionAlgorithmSimpleProductCustomStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/NotifyQuantityUseDefaultAppliedToSimpleProductOnConfigurationAdminPage.xml
  app/code/Magento/InventoryApi/Test/Mftf/Data/MsiCustomerData.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/CatalogInventory/Section/AdminAdvancedInventorySection.xml
Labels: MFTF (Functional Test Coverage)

#1219 Cover with Integration Tests Quote Operation for Configurable product
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnNotDefaultStockTest.php
Labels: Top 10 PRs

#1235 MSI-1233: Merge MFTF tests into single PR.
  app/code/Magento/Inventory/Test/Mftf/ActionGroup/AssignSourceToProductActionGroup.xml
  app/code/Magento/Inventory/Test/Mftf/ActionGroup/AssignSourceToStockActionGroup.xml
  app/code/Magento/Inventory/Test/Mftf/ActionGroup/DisableSourceActionGroup.xml
  app/code/Magento/Inventory/Test/Mftf/Page/AdminSourceSelectionPage.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminAdvancedInventorySlideOutSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminItemsOrderedSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminManageStockFormSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminManageStockGridSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminSelectSourceSection.xml
  app/code/Magento/Inventory/Test/Mftf/Section/AdminSourceSelectionControlsSection.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreatePartialShipmentForOrderWithSimpleProductFromCustomSourceTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreatePartialShipmentForOrderWithSimpleProductInSingleStockModeTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithSimpleProductFromCustomSourceTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithSimpleProductInSingleStockModeTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminManageStockOnProductPageTurnedOffForSimpleProductTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminManualSelectingOfSourcesToDeductItemsInShipmentForOrderWithSimpleProductTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminPaginationWorkedInManageStocksGridTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminPriorityOfSourcesChangedByDragAndDropTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminSelectDeselectManipulationsInManageStocksGridTest.xml
  app/code/Magento/InventoryApi/Test/Mftf/Data/MsiStockData.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Shipping/Section/AdminShipmentItemsSection.xml
Labels: MFTF (Functional Test Coverage)

#1280 MSI-1240: Credit memo with return to stock works incorrect.
  app/code/Magento/InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessBackItemQtyToSource.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessRefundItems.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/BackItemQtyRequest.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/BackItemQtyRequestInterface.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/ItemsToRefund.php
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Model/ReturnProcessor/GetSourceDeductedOrderItemsChain.php
  app/code/Magento/InventorySalesApi/Model/ReturnProcessor/GetSourceDeductedOrderItemsInterface.php
  app/code/Magento/InventorySalesApi/Model/ReturnProcessor/ProcessRefundItemsInterface.php
  app/code/Magento/InventorySalesApi/Model/ReturnProcessor/Request/ItemsToRefundInterface.php
  app/code/Magento/InventorySalesApi/Model/ReturnProcessor/Result/SourceDeductedOrderItem.php
  app/code/Magento/InventorySalesApi/Model/ReturnProcessor/Result/SourceDeductedOrderItemsResult.php
  app/code/Magento/InventorySalesApi/composer.json
  app/code/Magento/InventorySalesApi/etc/di.xml
  app/code/Magento/InventoryShipping/Model/ReturnProcessor/GetShippedItemsPerSourceByPriority.php
  app/code/Magento/InventoryShipping/etc/di.xml
Labels: Award: complex, Award: special achievement, Bugfixing, Top 10 PRs, regression phase 2

#1289 DI cleaning
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryConfiguration/etc/di.xml
  app/code/Magento/InventorySales/etc/di.xml
Labels: MM18NL, Partner: MageSpecialist, partners-contribution

#1340 Use of NoSuchEntityException instead of InputException in GetProductI…
  app/code/Magento/InventoryCatalog/Model/GetProductIdsBySkus.php
  app/code/Magento/InventoryCatalog/Model/GetSkusByProductIds.php
  app/code/Magento/InventoryCatalog/Model/SourceItemsSaveSynchronization/SetDataToLegacyCatalogInventory.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetToZeroLegacyCatalogInventoryAtSourceItemsDeletePlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetProductIdsBySkusTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetSkusByProductIdsTest.php
  app/code/Magento/InventoryCatalogApi/Model/GetProductIdsBySkusInterface.php
  app/code/Magento/InventoryCatalogApi/Model/GetSkusByProductIdsInterface.php
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
  app/code/Magento/InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessBackItemQtyPlugin.php
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
  app/code/Magento/InventoryShipping/Model/GetItemsToDeduct.php
  app/code/Magento/InventoryShipping/Model/InventoryRequestFromInvoiceFactory.php
  app/code/Magento/InventoryShipping/Model/ReturnProcessor/GetShippedItemsPerSourceByPriority.php
Labels: Partner: MageSpecialist, Perugia, partners-contribution

#1345 MSI-666: when duplicate a product set as disabled
  app/code/Magento/InventoryCatalogAdminUi/Plugin/Catalog/CopySourceItemsPlugin.php
Labels: Perugia

#1347 Fix for issue #717
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php
  app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
Labels: Award: special achievement, Partner: MageSpecialist, Perugia, partners-contribution

#1288 Issue 1039 incorrect web api delete implementation
  app/code/Magento/InventoryApi/Test/Api/SourceItemsDeleteTest.php
  app/code/Magento/InventoryApi/Test/Api/StockSourceLink/StockSourceLinksDeleteTest.php
  app/code/Magento/InventoryApi/etc/webapi.xml
Labels: MM18NL, Partner: MageSpecialist, partners-contribution

#1344 Issue 1306 rename website breaks grid
  app/code/Magento/InventorySales/Model/ResourceModel/GetWebsiteCodeByWebsiteId.php
  app/code/Magento/InventorySales/Model/ResourceModel/UpdateSalesChannelWebsiteCode.php
  app/code/Magento/InventorySales/Plugin/Store/Model/ResourceModel/Website/AssignWebsiteToDefaultStockPlugin.php
  app/code/Magento/InventorySales/Plugin/Store/Model/ResourceModel/Website/UpdateSalesChannelWebsiteCodePlugin.php
  app/code/Magento/InventorySales/Test/Integration/Website/RenameWebsiteToStockLinkTest.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySales/etc/events.xml
  app/code/Magento/InventorySalesAdminUi/Ui/Component/Listing/Column/SalesChannels.php
Labels: Partner: MageSpecialist, Perugia, QA Passed, partners-contribution

#1371 FIX for issue#1341: Preventing assigning product to default source
  app/code/Magento/InventoryApi/Test/_files/products.php
  app/code/Magento/InventoryCatalog/Model/GetDefaultSourceItemBySku.php
  app/code/Magento/InventoryCatalog/Model/UpdateSourceItemBasedOnLegacyStockItem.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/UpdateSourceItemAtLegacyStockItemSavePlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockDataToCollectionOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockStatusToSelectOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockStatusToSelectTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetDefaultSourceItemBySkuTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetProductIdsBySkusTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetSkusByProductIdsTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/InvalidateIndexOnConfigChangeTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/UpdateDefaultSourceItemAtLegacyStockItemSaveTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/UpdateDefaultSourceItemAtProductSaveTest.php
  app/code/Magento/InventoryCatalog/Test/_files/source_items_on_mixed_sources.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Adapter/Mysql/Aggregation/DataProvider/ApplyStockConditionToSelectTest.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Adapter/Mysql/Aggregation/DataProvider/ApplyStockConditionToSelectWithDefaultStockTest.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Search/FilterMapper/TermDropdownStrategy/ApplyStockConditionToSelectOnDefaultStockTest.php
Labels: Award: complex, Award: special achievement, Award: test coverage, Partner: MageSpecialist, partners-contribution

#1356 Switched from observer based logic to plugin based logic for website …
  app/code/Magento/InventorySales/Observer/Website/DeleteWebsiteToStockLink.php
  app/code/Magento/InventorySales/Plugin/Store/Model/ResourceModel/Website/DeleteWebsiteToStockLinkPlugin.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySales/etc/events.xml
Labels: QA Passed

#1350 Fix Magento\Sales\Service\V1\ShipmentGetTest::testShipmentGet
  dev/tests/api-functional/testsuite/Magento/Sales/Service/V1/ShipmentGetTest.php
Labels: Partner: MageSpecialist, Perugia, partners-contribution

#1342 Fix issue #1339 - \Magento\Sales\Service\V1\ShipmentCreateTest::testInvoke
  dev/tests/api-functional/testsuite/Magento/Sales/Service/V1/ShipmentCreateTest.php
Labels: Partner: MageSpecialist, Perugia, partners-contribution

#1218 Cover with Integration Tests Order Placement for Configurable product
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
Labels: Top 10 PRs

#1290 Singular names switched to plural in webapi calls.
  app/code/Magento/InventoryApi/Test/Api/SourceItemRepository/GetListTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceItemsDeleteTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceItemsSave/SaveTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceItemsSave/ValidationTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceRepository/CreateTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceRepository/GetListTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceRepository/GetTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceRepository/RegionProcessingTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceRepository/UpdateTest.php
  app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php
  app/code/Magento/InventoryApi/Test/Api/StockRepository/CreateTest.php
  app/code/Magento/InventoryApi/Test/Api/StockRepository/DeleteTest.php
  app/code/Magento/InventoryApi/Test/Api/StockRepository/GetListTest.php
  app/code/Magento/InventoryApi/Test/Api/StockRepository/GetTest.php
  app/code/Magento/InventoryApi/Test/Api/StockRepository/UpdateTest.php
  app/code/Magento/InventoryApi/Test/Api/StockRepository/ValidationTest.php
  app/code/Magento/InventoryApi/Test/Api/StockSourceLink/GetStockSourceLinksTest.php
  app/code/Magento/InventoryApi/Test/Api/StockSourceLink/StockSourceLinksDeleteTest.php
  app/code/Magento/InventoryApi/Test/Api/StockSourceLink/StockSourceLinksSaveTest.php
  app/code/Magento/InventoryApi/Test/Mftf/Metadata/source-meta.xml
  app/code/Magento/InventoryApi/Test/Mftf/Metadata/stock-meta.xml
  app/code/Magento/InventoryApi/Test/Mftf/Metadata/stock-source-link-meta.xml
  app/code/Magento/InventoryApi/etc/webapi.xml
  app/code/Magento/InventoryCatalog/Test/Api/GetDefaultSourceTest.php
  app/code/Magento/InventoryCatalog/Test/Api/GetDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Api/StockRepository/PreventDefaultStockDeletingTest.php
  app/code/Magento/InventoryCatalog/Test/Api/StockSourceLink/PreventAssignSourcesToDefaultStockTest.php
  app/code/Magento/InventoryCatalogApi/Test/Api/PreventDefaultSourceDisablingTest.php
  app/code/Magento/InventorySalesApi/Test/Api/StockRepository/PreventAssignedToSalesChannelsStockDeletingTest.php
  app/code/Magento/InventorySalesApi/Test/Api/StockRepository/SalesChannelManagementTest.php
Labels: MM18NL, Partner: MageSpecialist, partners-contribution

#1424 MSI-1422 Avoid code duplication in ResourceModel/PredefinedId
  app/code/Magento/Inventory/Model/ResourceModel/PredefinedId.php
  app/code/Magento/Inventory/Model/ResourceModel/Source.php
  app/code/Magento/Inventory/Model/ResourceModel/Stock.php
Labels: Dare to Share

#1315 MSI-1301: MFTF Order created with Downloadable product from Admin
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateOrderWithDownloadableProductDefaultStock.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/ActionGroup/AdminOrderActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/Page/AdminOrderCreatePage.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/Section/AdminOrderCustomersGridSection.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/Section/AdminOrderFormDownloadableProductSection.xml
Labels: MFTF (Functional Test Coverage)

#1320 MSI-1297: MFTF Order created with Virtual product on Default stock from Admin
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateOrderWithVirtualProductDefaultStock.xml
Labels: MFTF (Functional Test Coverage)

#1326 MSI-1296: MFTF Guest Customer ordered Virtual product on Default source from Homepage
  app/code/Magento/Inventory/Test/Mftf/Section/AdminManageStockFormSection.xml
  app/code/Magento/Inventory/Test/Mftf/Test/GuestCustomerOrderedVirtualProductOnDefaultSourceFromHomepageTest.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Checkout/ActionGroup/StorefrontProductCartActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Checkout/Section/StorefrontMiniCartSection.xml
Labels: MFTF (Functional Test Coverage)

#1328 MSI-1319: MFTF Order created with Grouped product with child products assigned to default Stock from Admin
  app/code/Magento/Inventory/Test/Mftf/ActionGroup/DisableSourceActionGroup.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateOrderWithGroupedProductDefaultStock.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/ActionGroup/AdminOrderActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/Page/AdminOrderCreatePage.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/Section/AdminOrderFormGroupedProductSection.xml
Labels: MFTF (Functional Test Coverage)

#1333 MSI-1332: MFTF Order created with Bundle product with child products assigned to default Stock from Admin
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateOrderWithBundleProductDefaultStock.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/ActionGroup/AdminOrderActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/Page/AdminOrderCreatePage.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Sales/Section/AdminOrderFormBundleProductSection.xml
Labels: MFTF (Functional Test Coverage)

#1355 MSI-1331: MFTF Logged in Customer ordered Bundle product with child products assigned to default Stock from Homepage
  app/code/Magento/Inventory/Test/Mftf/Test/LoggedCustomerCreateOrderWithBundleProductDefaultStock.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Bundle/ActionGroup/StorefrontProductCartActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Bundle/Section/StorefrontProductActionSection.xml
Labels: MFTF (Functional Test Coverage)

#1357 MSI-1330: MFTF Guest Customer ordered Bundle product with child products assigned to default Stock from Homepage
  app/code/Magento/Inventory/Test/Mftf/Test/GuestCustomerCreateOrderWithBundleProductDefaultStock.xml
Labels: MFTF (Functional Test Coverage)

#1368 MSI-1329: MFTF Guest Customer ordered Bundle product on Single stock mode from Homepage
  app/code/Magento/Inventory/Test/Mftf/Section/AdminProductGridSection.xml
  app/code/Magento/Inventory/Test/Mftf/Test/GuestCustomerCreateOrderWithBundleProductSingleStockMode.xml
Labels: MFTF (Functional Test Coverage)

#1369 MSI-1317: MFTF Guest Customer ordered Grouped product on Single stock mode from Homepage
  app/code/Magento/Inventory/Test/Mftf/Test/GuestCustomerOrderedGroupedProductOnSingleStockModeFromHomepage.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Checkout/ActionGroup/StorefrontProductCartActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Checkout/Section/StorefrontMiniCartSection.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/GroupedProduct/ActionGroup/AdminGroupedProductActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/GroupedProduct/Section/AdminAddProductsToGroupPanelSection.xml
Labels: MFTF (Functional Test Coverage)

#1321 MSI-1299: MFTF Guest Customer ordered Downloadable product on Default stock from Homepage.
  app/code/Magento/Inventory/Test/Mftf/ActionGroup/DisableSourceActionGroup.xml
  app/code/Magento/Inventory/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnDefaultStockFromHomepageTest.xml
Labels: MFTF (Functional Test Coverage)

#1322 MSI-1300: MFTF Guest Customer ordered Downloadable product on Test stock from Homepage.
  app/code/Magento/Inventory/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnCustomStockFromHomepageTest.xml
Labels: MFTF (Functional Test Coverage)

#1327 MSI-494: [Configuration-Sources] Select / Deselect All, Select All manipulations in Manage Sources grid by Admin user.
  app/code/Magento/Inventory/Test/Mftf/Section/AdminManageSourcesGridSection.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminSelectDeselectManipulationsInManageSourceGridTest.xml
Labels: MFTF (Functional Test Coverage)

#1311 MSI-1140: [Sales-Shipments] Partial Shipment created for order with Configurable product in Admin.
  app/code/Magento/Inventory/Test/Mftf/Test/AdminAddConfigurableProductWithDropDownAttributeAndCustomSourceTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminAddConfigurableProductWithDropDownAttributeAndDefaultSourceTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminConfigurableProductDisabledManageStockOnCustomStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminConfigurableProductDisabledManageStockOnDefaultStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminConfigurableProductDisabledManageStockOnProductPageCustomStock.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreatePartialShipmentForOrderWithConfigurableProductFromCustomSourceTest.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/ConfigurableProduct/Section/AdminProductFormConfigurationsSection.xml
Labels: MFTF (Functional Test Coverage)

#1307 MSI-1139: [Sales-Shipments] Shipment created for whole order with Configurable product in Admin.
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithConfigurableProductFromCustomSourceTest.xml
Labels: MFTF (Functional Test Coverage)

#1408 msi #1407 Remove redundant Configurable index
  app/code/Magento/InventoryConfigurableProduct/Model/ResourceModel/IsStockItemSalableCondition/GetConfigurableCondition.php
  app/code/Magento/InventoryConfigurableProduct/composer.json
  app/code/Magento/InventoryConfigurableProduct/etc/di.xml
Labels: Dare to Share, QA Passed

#1392 MSI-1381 // SalesChannel validation for API requests
  app/code/Magento/InventoryApi/Test/Api/StockSourceLink/GetSourcesAssignedToStockOrderedByPriorityTest.php
  app/code/Magento/InventorySales/Model/Stock/Validator/SalesChannelsValidator.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Test/Api/StockRepository/AssignSalesChannelTest.php
  app/code/Magento/InventorySalesApi/Test/_files/websites_with_stores_rollback.php
Labels: Bugfixing, WEB API

#1353 fix stock item configuration
  app/code/Magento/Inventory/Model/ResourceModel/IsProductAssignedToStock.php
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryApi/Model/IsProductAssignedToStockInterface.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetDataToLegacyCatalogInventoryAtSourceItemsSavePlugin.php
  app/code/Magento/InventoryCatalogAdminUi/Model/CanManageSourceItemsBySku.php
  app/code/Magento/InventoryConfiguration/Model/GetLegacyStockItem.php
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForSku.php
  app/code/Magento/InventoryConfiguration/composer.json
  app/code/Magento/InventoryConfigurationApi/Api/GetStockItemConfigurationInterface.php
  app/code/Magento/InventoryConfigurationApi/Exception/SkuIsNotAssignedToStockException.php
  app/code/Magento/InventorySales/Model/GetProductSalableQty.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/BackOrderCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsProductSalableConditionChain.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/ManageStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsCorrectQtyCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Plugin/InventoryReservationsApi/PreventAppendReservationOnNotManageItemsInStockPlugin.php
  app/code/Magento/InventorySalesFrontendUi/Plugin/Block/Stockqty/AbstractStockqtyPlugin.php
  app/code/Magento/InventoryShipping/Model/GetItemsToDeductFromShipment.php
  app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/Test/Integration/SourceDeductionForVirtualProductsOnDefaultStockTest.php
  app/code/Magento/InventoryShipping/Test/Integration/SourceDeductionForVirtualProductsOnMultiStockTest.php
  app/code/Magento/InventoryShipping/Test/_files/create_quote_on_default_website.php
  app/code/Magento/InventoryShipping/Test/_files/create_quote_on_default_website_rollback.php
  app/code/Magento/InventoryShipping/Test/_files/create_quote_on_eu_website.php
  app/code/Magento/InventoryShipping/Test/_files/order_virtual_products.php
  app/code/Magento/InventoryShippingAdminUi/Ui/DataProvider/SourceSelectionDataProvider.php
Labels: Dare to Share

#1428 #1282 notify qty use default check box
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/view/adminhtml/web/js/components/use-config-settings.js
Labels: Dare to Share

#1410 1250: added plugin to prevent disabling default source
  app/code/Magento/InventoryAdminUi/Ui/DataProvider/SourceDataProvider.php
  app/code/Magento/InventoryAdminUi/view/adminhtml/ui_component/inventory_source_form.xml
  app/code/Magento/InventoryCatalogAdminUi/Plugin/InventoryAdminUi/DataProvider/PreventDisablingDefaultSourcePlugin.php
  app/code/Magento/InventoryCatalogAdminUi/etc/adminhtml/di.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/inventory_source_form.xml
Labels: Dare to Share

#1429 MSI-1427 Add backorder condition to indexer
  app/code/Magento/InventorySales/Model/ResourceModel/IsStockItemSalableCondition/BackordersCondition.php
  app/code/Magento/InventorySales/Test/Integration/GetStockItemData/BackorderConditionTest.php
  app/code/Magento/InventorySales/etc/di.xml
Labels: Dare to Share, QA Passed

#1414 1409: removed $this usage from template
  app/code/Magento/InventoryShippingAdminUi/view/adminhtml/templates/shipment/inventory.phtml
Labels: Dare to Share
