Repository magento/inventory, pull requests merged in 2018-03, with the labels that each got.

#560 #518 Simplest “By Priority” Algorithm implementation
  app/code/Magento/Inventory/Model/Source/Command/GetSourcesAssignedToStockOrderedByPriority.php
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryApi/Api/GetSourcesAssignedToStockOrderedByPriorityInterface.php
  app/code/Magento/InventoryApi/Test/Api/StockSourceLink/GetSourcesAssignedToStockOrderedByPriorityTest.php
  app/code/Magento/InventoryApi/Test/_files/stock_source_links.php
  app/code/Magento/InventoryApi/etc/webapi.xml
  app/code/Magento/InventoryShipping/Block/Adminhtml/Order/View/Tab/SourceSelection.php
  app/code/Magento/InventoryShipping/Model/DefaultShippingAlgorithm.php
  app/code/Magento/InventoryShipping/Model/PriorityShippingAlgorithm/GetEnabledSourcesOrderedByPriorityByStoreId.php
  app/code/Magento/InventoryShipping/Model/PriorityShippingAlgorithm/GetSourceItemBySourceCodeAndSku.php
  app/code/Magento/InventoryShipping/Model/PriorityShippingAlgorithm/PriorityShippingAlgorithm.php
  app/code/Magento/InventoryShipping/Model/ShippingAlgorithmProvider.php
  app/code/Magento/InventoryShipping/Test/Integration/PriorityShippingAlgorithmTest.php
  app/code/Magento/InventoryShipping/composer.json
  app/code/Magento/InventoryShipping/etc/module.xml
  app/code/Magento/InventoryShipping/view/adminhtml/templates/order/view/tab/source_selection.phtml
Labels: Chernivtsi Contribution Day

#604 MSI: 363: Notify Quantity - Use Default check-box on product page in Sources tab not applying after Save
  app/code/Magento/Inventory/etc/adminhtml/system.xml
  app/code/Magento/Inventory/etc/config.xml
  app/code/Magento/InventoryLowQuantityNotification/Model/SourceItemConfiguration/Command/GetDefaultValues.php
  app/code/Magento/InventoryLowQuantityNotification/Ui/Component/Product/Form/Element/UseConfigSettings.php
  app/code/Magento/InventoryLowQuantityNotification/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php
  app/code/Magento/InventoryLowQuantityNotification/composer.json
  app/code/Magento/InventoryLowQuantityNotification/etc/adminhtml/system.xml
  app/code/Magento/InventoryLowQuantityNotification/etc/config.xml
  app/code/Magento/InventoryLowQuantityNotification/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryLowQuantityNotification/view/adminhtml/web/js/components/use-config-settings.js
Labels: QA Passed

#646 Fix Magento\InventoryCatalog\Plugin\InventoryApi\ApplyDataToLegacyCatalogInventoryAtReservationPlacingPlugin
  app/code/Magento/InventoryCatalog/Plugin/InventoryReservationsApi/ApplyDataToLegacyCatalogInventoryAtReservationPlacingPlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/InventoryReservationsApi/ApplyDataToLegacyStockItemAtReservationPlacingTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/InventoryReservationsApi/ApplyDataToLegacyStockStatusAtReservationPlacingTest.php
  dev/tests/integration/testsuite/Magento/Sales/Controller/Adminhtml/Order/CreditmemoTest.php
Labels: WIP

#554 #498 Fix for throws low level exception
  app/code/Magento/InventoryIndexer/Model/GetStockItemData.php
  app/code/Magento/InventorySales/Model/GetStockItemDataInterface.php
  app/code/Magento/InventorySales/Test/Integration/GetStockItemData/GetStockItemDataTest.php
Labels: Bugfixing, Chernivtsi Contribution Day

#647 Source deduction at Order complete #2
  app/code/Magento/InventoryShipping/Block/Adminhtml/Shipment/AlgorithmSelectionButton.php
  app/code/Magento/InventoryShipping/Controller/Adminhtml/Algorithm/GetSources.php
  app/code/Magento/InventoryShipping/Plugin/Sales/CollectSourcesForShipmentItems.php
  app/code/Magento/InventoryShipping/composer.json
  app/code/Magento/InventoryShipping/etc/adminhtml/routes.xml
  app/code/Magento/InventoryShipping/etc/module.xml
  app/code/Magento/InventoryShipping/view/adminhtml/layout/adminhtml_order_shipment_new.xml
  app/code/Magento/InventoryShipping/view/adminhtml/templates/shipment/button_script.phtml
  app/code/Magento/InventoryShipping/view/adminhtml/templates/shipment/items/default.phtml
Labels: WIP

#562 #556: When filling Source Code with space on Source Creation Page and…
  app/code/Magento/Inventory/Controller/Adminhtml/Source/Save.php
  app/code/Magento/Inventory/Ui/DataProvider/SourceDataProvider.php
  app/code/Magento/Inventory/view/adminhtml/ui_component/inventory_source_form.xml
Labels: Chernivtsi Contribution Day

#656 MSI: 654: Exception when trying to create Grouped or Bundle product in admin
  app/code/Magento/InventoryConfigurableProduct/Ui/DataProvider/Product/Form/Modifier/InventoryConfigurablePanel.php
  app/code/Magento/InventoryConfigurableProduct/etc/adminhtml/di.xml
  app/code/Magento/InventoryConfigurableProduct/etc/di.xml
  app/code/Magento/InventoryConfigurableProduct/etc/module.xml
Labels: current sprint

#629 Add IsProductSalableForRequestedQty service
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/SaveStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/StockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/etc/di.xml
  app/code/Magento/InventoryConfigurationApi/Api/Data/StockItemConfigurationInterface.php
  app/code/Magento/InventoryConfigurationApi/Api/SaveStockItemConfigurationInterface.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsProductSalableConditionChain.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/MinQtyStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/BackOrderCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsCorrectQtyCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/ManageStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/ProductSalabilityError.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/ProductSalableResult.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/ManageStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/BackorderConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsCorrectQtyConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/ManageStockConditionTest.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Api/Data/ProductSalabilityErrorInterface.php
  app/code/Magento/InventorySalesApi/Api/Data/ProductSalableResultInterface.php
  app/code/Magento/InventorySalesApi/Api/IsProductSalableForRequestedQtyInterface.php
Labels: WIP, complex, current sprint

#652 Quote items qty validation tests on default and not default stocks
  app/code/Magento/InventoryConfigurableProduct/Ui/DataProvider/Product/Form/Modifier/InventoryConfigurablePanel.php
  app/code/Magento/InventoryConfigurableProduct/etc/adminhtml/di.xml
  app/code/Magento/InventoryConfigurableProduct/etc/di.xml
  app/code/Magento/InventoryConfigurableProduct/etc/module.xml
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/layout/catalog_product_wizard.xml
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/SaveStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/StockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/etc/di.xml
  app/code/Magento/InventoryConfigurationApi/Api/Data/StockItemConfigurationInterface.php
  app/code/Magento/InventoryConfigurationApi/Api/SaveStockItemConfigurationInterface.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/MinQtyStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/BackOrderCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsCorrectQtyCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/ManageStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/ProductSalabilityError.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/ProductSalableResult.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRegisterProductsSalePlugin.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsCorrectQtyConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnDefaultSourceTest.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnNotDefaultSourceTest.php
  app/code/Magento/InventorySales/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnNotDefaultStockTest.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Api/Data/ProductSalabilityErrorInterface.php
  app/code/Magento/InventorySalesApi/Api/Data/ProductSalableResultInterface.php
  app/code/Magento/InventorySalesApi/Api/IsProductSalableForRequestedQtyInterface.php
  app/code/Magento/InventorySalesApi/Test/_files/quote.php
  app/code/Magento/InventorySalesApi/Test/_files/quote_rollback.php
Labels: current sprint

#677 Update source items on config save
  app/code/Magento/InventoryCatalog/Observer/UpdateSourceItemsUponConfigChangeObserver.php
  app/code/Magento/InventoryCatalog/Test/Integration/InvalidateIndexOnConfigChangeTest.php
  app/code/Magento/InventoryCatalog/etc/adminhtml/events.xml
Labels: current sprint

#631 555: Implement RSS feed to Low Stock Notifications
  app/code/Magento/InventoryLowQuantityNotification/Block/Adminhtml/Rss/NotifyStock.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyBaseJoins.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyConfigurationCondition.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyNameAttributeCondition.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/ApplyStatusAttributeCondition.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/GetSourceItemsCollection.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/Rss/NotifyStock/SelectBuilder.php
  app/code/Magento/InventoryLowQuantityNotification/Test/Integration/Model/RssFeedTest.php
  app/code/Magento/InventoryLowQuantityNotification/composer.json
  app/code/Magento/InventoryLowQuantityNotification/etc/adminhtml/di.xml
  app/code/Magento/InventoryLowQuantityNotification/etc/module.xml
  app/code/Magento/InventoryLowQuantityNotificationApi/Test/_files/enable_manage_stock_for_products.php
Labels: WIP, current sprint

#648 MSI: 612: Modify step wizard on configurable product page backend
  app/code/Magento/ConfigurableProduct/Test/Unit/Ui/DataProvider/Product/Form/Modifier/CompositeTest.php
  app/code/Magento/ConfigurableProduct/Ui/DataProvider/Product/Form/Modifier/Composite.php
  app/code/Magento/InventoryConfigurableProduct/Model/GetQuantityInformationPerSource.php
  app/code/Magento/InventoryConfigurableProduct/Observer/ProcessSourceItemsObserver.php
  app/code/Magento/InventoryConfigurableProduct/Ui/DataProvider/Product/Form/Modifier/InventoryConfigurablePanel.php
  app/code/Magento/InventoryConfigurableProduct/composer.json
  app/code/Magento/InventoryConfigurableProduct/etc/events.xml
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/ui_component/configurable_quantity_templates.xml
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/template/dynamic-rows/cells/cell-source.html
Labels: WIP, current sprint

#651 MSI: 614: Use configurable wizard on simple product when converted to configurable
  app/code/Magento/InventoryCatalog/Ui/DataProvider/Product/Form/Modifier/SourceItems.php
  app/code/Magento/InventoryCatalog/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryCatalog/view/adminhtml/web/template/product/form/cell-status.html
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/js/components/sources-visibility-checker.js
Labels: WIP

#667 Adapt `\Magento\CatalogInventory\Model\StockStateProvider`
  app/code/Magento/CatalogInventory/etc/db_schema.xml
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRegisterProductsSalePlugin.php
  app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
  app/code/Magento/InventorySales/Plugin/StockState/SuggestQtyPlugin.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnDefaultSourceTest.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnNotDefaultSourceTest.php
  app/code/Magento/InventorySales/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnNotDefaultStockTest.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Test/_files/quote.php
  app/code/Magento/InventorySalesApi/Test/_files/quote_rollback.php
  dev/tests/integration/testsuite/Magento/InstantPurchase/Model/PlaceOrderTest.php
  dev/tests/integration/testsuite/Magento/Wishlist/Controller/IndexTest.php
Labels: WIP, complex, current sprint

#686 Grouped products work with Single Stock
  app/code/Magento/InventoryGroupedProduct/LICENSE.txt
  app/code/Magento/InventoryGroupedProduct/LICENSE_AFL.txt
  app/code/Magento/InventoryGroupedProduct/Plugin/InventoryConfiguration/IsSourceItemsAllowedForProductType/DisableGroupedTypePlugin.php
  app/code/Magento/InventoryGroupedProduct/README.md
  app/code/Magento/InventoryGroupedProduct/composer.json
  app/code/Magento/InventoryGroupedProduct/etc/di.xml
  app/code/Magento/InventoryGroupedProduct/etc/module.xml
  app/code/Magento/InventoryGroupedProduct/registration.php
  app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
  composer.json
  composer.lock
  dev/tests/static/testsuite/Magento/Test/Php/_files/whitelist/strict_type.txt
Labels: WIP

#696 MSI-683: Bundled products work with Single Stock
  app/code/Magento/InventoryBundle/Plugin/InventoryConfiguration/IsSourceItemsAllowedForProductType/DisableBundleTypePlugin.php
  app/code/Magento/InventoryBundle/composer.json
  app/code/Magento/InventoryBundle/etc/di.xml
  app/code/Magento/InventoryBundle/etc/module.xml
Labels: current sprint

#694 Unskip test testRouteConfigsValidation
  dev/tests/integration/testsuite/Magento/Test/Integrity/Modular/RouteConfigFilesTest.php
  lib/internal/Magento/Framework/Config/Dom.php
Labels: WIP

#749 Fix add to cart using itemQty instead of requestedQty
  app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
Labels: Bugfixing, Distributed CD, distributed-cd

#731 MSI-719: Investigate fails test on Groped products
  app/code/Magento/InventoryCatalog/Ui/DataProvider/Product/Form/Modifier/Quantity.php
  app/code/Magento/InventoryCatalog/Ui/DataProvider/Product/Form/Modifier/StockStatus.php
Labels: Distributed CD, WIP, distributed-cd

#655 MSI: 607: Update Product Grid for single-stock and multi-stock mode
  app/code/Magento/Catalog/Ui/DataProvider/Product/ProductDataProvider.php
  app/code/Magento/Catalog/etc/adminhtml/di.xml
  app/code/Magento/InventoryCatalog/Ui/Component/Listing/Column/SourceItems.php
  app/code/Magento/InventoryCatalog/Ui/DataProvider/Product/Listing/Modifier/Quantity.php
  app/code/Magento/InventoryCatalog/Ui/DataProvider/Product/Listing/Modifier/QuantityPerSource.php
  app/code/Magento/InventoryCatalog/Ui/DataProvider/Product/Listing/Modifier/SalableQuantity.php
  app/code/Magento/InventoryCatalog/etc/adminhtml/di.xml
Labels: current sprint

#559 #451 disabled sources tab content on manage_stock update
  app/code/Magento/InventoryCatalog/Model/CanManageSourceItemsBySku.php
  app/code/Magento/InventoryCatalog/Ui/DataProvider/Product/Form/Modifier/SourceItems.php
  app/code/Magento/InventoryCatalog/composer.json
  app/code/Magento/InventoryCatalog/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryCatalog/view/adminhtml/web/js/product/form/components/source-items.js
Labels: Chernivtsi Contribution Day, WIP, approved, distributed-cd

#739 #715 Low stock report should not display notifications for product with stock status "Out of stock" on source
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
  app/code/Magento/InventoryLowQuantityNotification/Test/Integration/Model/ResourceModel/LowQuantityCollectionTest.php
  app/code/Magento/InventoryLowQuantityNotificationApi/Test/_files/source_item_configuration.php
Labels: Distributed CD, distributed-cd

#752 737 Exception in Low stock report for product with another name on additional storeview
  app/code/Magento/InventoryLowQuantityNotification/Block/Adminhtml/Product/Lowstock/Grid.php
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
  app/code/Magento/InventoryLowQuantityNotification/view/adminhtml/layout/reports_report_product_lowstock.xml
Labels: Distributed CD, distributed-cd

#753 714: Fatal error: Uncaught TypeError: during the saving of configurable product
  app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/components/dynamic-rows-configurable.js
  app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/variations/steps/bulk.js
  app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/variations/steps/summary.js
  app/code/Magento/InventoryConfigurableProduct/Model/GetQuantityInformationPerSource.php
  app/code/Magento/InventoryConfigurableProduct/Observer/ProcessSourceItemsObserver.php
  app/code/Magento/InventoryConfigurableProduct/Ui/DataProvider/Product/Form/Modifier/InventoryConfigurablePanel.php
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/bulk.phtml
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/templates/catalog/product/edit/attribute/steps/summary.phtml
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/ui_component/configurable_quantity_templates.xml
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/js/components/dynamic-rows-configurable.js
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/js/form/element/quantity-per-source.js
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/js/variations/steps/bulk.js
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/js/variations/steps/summary.js
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/template/dynamic-rows/cells/cell-source.html
  app/code/Magento/InventoryConfigurableProduct/view/adminhtml/web/template/variations/steps/summary-grid.html
Labels: Distributed CD, core affected, distributed-cd

#779 MSI-690: Unskip and Fix Integration Test for Quantity Increment Messa…
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsCorrectQtyCondition.php
  dev/tests/integration/testsuite/Magento/Wishlist/Controller/IndexTest.php
Labels: WIP

#770 MSI-633: Investigate possible exception with $this->getProductIdsBySkus->execute([$sku])[$sku]
  app/code/Magento/InventoryCatalog/Model/GetProductIdsBySkus.php
  app/code/Magento/InventoryCatalog/Model/GetProductIdsBySkusInterface.php
  app/code/Magento/InventoryCatalog/Model/GetSkusByProductIds.php
  app/code/Magento/InventoryCatalog/Model/GetSkusByProductIdsInterface.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/SetDataToLegacyStockItem.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetProductIdsBySkusTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetSkusByProductIdsTest.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Indexer/FulltextTest.php
  app/code/Magento/InventoryCatalogSearch/etc/module.xml
  app/code/Magento/InventoryConfigurableProduct/Test/_files/source_items_configurable.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/source_items_configurable_rollback.php
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
  app/code/Magento/InventoryConfiguration/Model/SaveStockItemConfiguration.php
Labels: WIP

#707 MSI-698: Adapt MSI to use Default Stock
  app/code/Magento/InventoryBundleIndexer/Indexer/SourceItem/ByBundleSkuAndChildrenSourceItemsIdsIndexer.php
  app/code/Magento/InventoryBundleIndexer/Indexer/SourceItem/ChildrenSourceItemsIdsProvider.php
  app/code/Magento/InventoryBundleIndexer/Indexer/SourceItem/GetSkuListInStock.php
  app/code/Magento/InventoryBundleIndexer/Indexer/SourceItem/IndexDataBySkuListProvider.php
  app/code/Magento/InventoryBundleIndexer/Indexer/SourceItem/SourceItemIndexer.php
  app/code/Magento/InventoryBundleIndexer/Indexer/SourceItem/SourceItemsIdsByChildrenProductsIdsProvider.php
  app/code/Magento/InventoryBundleIndexer/LICENSE.txt
  app/code/Magento/InventoryBundleIndexer/LICENSE_AFL.txt
  app/code/Magento/InventoryBundleIndexer/Plugin/InventoryIndexer/Indexer/SourceItem/AddBundleDataToIndexByBundleIds.php
  app/code/Magento/InventoryBundleIndexer/Plugin/InventoryIndexer/Indexer/SourceItem/AddBundleDataToIndexBySourceItemsIds.php
  app/code/Magento/InventoryBundleIndexer/README.md
  app/code/Magento/InventoryBundleIndexer/Test/Integration/SourceItemIndexerTest.php
  app/code/Magento/InventoryBundleIndexer/Test/_files/bundle_product_eu_website.php
  app/code/Magento/InventoryBundleIndexer/Test/_files/bundle_product_eu_website_rollback.php
  app/code/Magento/InventoryBundleIndexer/composer.json
  app/code/Magento/InventoryBundleIndexer/etc/di.xml
  app/code/Magento/InventoryBundleIndexer/etc/module.xml
  app/code/Magento/InventoryBundleIndexer/registration.php
  app/code/Magento/InventoryCatalog/Setup/Patch/Schema/CreateLegacyStockStatusView.php
  app/code/Magento/InventoryIndexer/Indexer/SourceItem/GetSourceItemIds.php
  app/code/Magento/InventoryIndexer/Indexer/SourceItem/SourceItemIndexer.php
  app/code/Magento/InventoryIndexer/Indexer/Stock/StockIndexer.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterSourceItemsDeletePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterSourceItemsSavePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterStockSourceLinksDeletePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterStockSourceLinksSavePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAroundStockSourceLinksDeletePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAroundStockSourceLinksSavePlugin.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/SourceItemIndexerTest.php
  app/code/Magento/InventoryIndexer/composer.json
  app/code/Magento/InventoryIndexer/etc/di.xml
  app/code/Magento/InventoryIndexer/etc/module.xml
  composer.json
  composer.lock
  dev/tests/static/testsuite/Magento/Test/Php/_files/whitelist/strict_type.txt
Labels: Distributed CD, WIP, current sprint, distributed-cd

#764 "Could not receive Stock Item data" Line Appear Instead of Admin Product Grid.
  app/code/Magento/InventoryIndexer/Model/GetStockItemData.php
  app/code/Magento/InventorySales/Test/Integration/GetStockItemData/GetStockItemDataTest.php
Labels: Distributed CD, distributed-cd

#803 MSI-800: Fix all comments from PR#707
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterStockSourceLinksDeletePlugin.php
  app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterStockSourceLinksSavePlugin.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/SourceItemIndexerTest.php
  app/code/Magento/InventoryIndexer/etc/di.xml
Labels: current sprint

#758 MSI-449 Adapt use_config_manage_stock = 0
  app/code/Magento/CatalogSearch/Model/Search/FilterMapper/TermDropdownStrategy/ApplyStockConditionToSelect.php
  app/code/Magento/InventoryApi/Test/_files/assign_products_to_websites.php
  app/code/Magento/InventoryApi/Test/_files/products.php
  app/code/Magento/InventoryApi/Test/_files/products_rollback.php
  app/code/Magento/InventoryApi/Test/_files/source_items.php
  app/code/Magento/InventoryApi/Test/_files/source_items_rollback.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetDataToLegacyCatalogInventoryAtSourceItemsSavePlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Helper/Stock/AddInStockFilterToCollectionOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Helper/Stock/AddInStockFilterToCollectionTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddIsInStockFilterToCollectionOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddIsInStockFilterToCollectionTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockDataToCollectionOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockDataToCollectionTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockStatusToSelectOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockStatusToSelectTest.php
  app/code/Magento/InventoryCatalog/Test/_files/source_items_on_default_source.php
  app/code/Magento/InventoryCatalog/Test/_files/source_items_on_default_source_rollback.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Adapter/Mysql/Aggregation/DataProvider/ApplyStockConditionToSelectTest.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Adapter/Mysql/Aggregation/DataProvider/ApplyStockConditionToSelectWithDefaultStockTest.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Search/FilterMapper/TermDropdownStrategy/ApplyStockConditionToSelectOnDefaultStockTest.php
  app/code/Magento/InventoryCatalogSearch/Test/Integration/Model/Search/FilterMapper/TermDropdownStrategy/ApplyStockConditionToSelectTest.php
  app/code/Magento/InventoryImportExport/Test/Integration/Model/Export/_files/export_filtered_by_source.csv
  app/code/Magento/InventorySales/Plugin/InventoryReservationsApi/PreventAppendReservationOnNotManageItemsInStockPlugin.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnUseConfigManageStockSetToZeroTest.php
  app/code/Magento/InventorySales/etc/di.xml
Labels: Distributed CD, distributed-cd, needs update

#760 Completed integration tests for place order process
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
Labels: Distributed CD, distributed-cd
