Repository magento/inventory, pull requests merged in 2018-05, with the labels that each got.

#945 MSI-896: Disabled "Advanced Inventory" button.
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/js/product/form/source-items.js
Labels: Bugfixing, current sprint

#921 MSI#822 Source deduction for virtual and downloadable products
  app/code/Magento/InventorySalesApi/Api/Data/SalesEventInterface.php
  app/code/Magento/InventorySalesApi/Test/_files/websites_with_stores.php
  app/code/Magento/InventoryShipping/Model/InventoryRequestFromInvoiceFactory.php
  app/code/Magento/InventoryShipping/Model/SourceDeductionRequestsFromSourceSelectionFactory.php
  app/code/Magento/InventoryShipping/Observer/VirtualSourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/Test/Integration/SourceDeductionForVirtualProductsOnDefaultStockTest.php
  app/code/Magento/InventoryShipping/Test/Integration/SourceDeductionForVirtualProductsOnMultiStockTest.php
  app/code/Magento/InventoryShipping/Test/_files/create_quote_on_default_website.php
  app/code/Magento/InventoryShipping/Test/_files/create_quote_on_default_website_rollback.php
  app/code/Magento/InventoryShipping/Test/_files/create_quote_on_eu_website.php
  app/code/Magento/InventoryShipping/Test/_files/create_quote_on_eu_website_rollback.php
  app/code/Magento/InventoryShipping/Test/_files/order_virtual_products.php
  app/code/Magento/InventoryShipping/Test/_files/order_virtual_products_rollback.php
  app/code/Magento/InventoryShipping/Test/_files/products_virtual.php
  app/code/Magento/InventoryShipping/Test/_files/products_virtual_rollback.php
  app/code/Magento/InventoryShipping/Test/_files/source_items_for_virtual_on_default_source.php
  app/code/Magento/InventoryShipping/Test/_files/source_items_for_virtual_on_multi_source.php
  app/code/Magento/InventoryShipping/etc/events.xml
Labels: complex, special achievement, test coverage

#1021 Return processor
  app/code/Magento/InventorySales/Model/ReturnProcessor/GetShippedItemsPerSourceByPriority.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessBackItemQtyToSource.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessRefundItems.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessRefundItemsInterface.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/BackItemQtyRequest.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/BackItemQtyRequestInterface.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/ItemsToRefund.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/Request/ItemsToRefundInterface.php
  app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySalesApi/Api/Data/SalesEventInterface.php
Labels: WIP, current sprint, special achievement

#1013 MSI-1007: Creating an order with a product that has a number in the product name causes fatal error
  app/code/Magento/InventoryCatalog/Model/GetProductTypesBySkus.php
  app/code/Magento/InventoryCatalog/Model/GetSkusByProductIds.php
  app/code/Magento/InventorySales/Model/CheckItemsQuantity.php
Labels: Top 10 PRs

#1060 Fix modularity problem with Reservation module
  app/code/Magento/InventoryReservations/Cron/CleanupReservations.php
  app/code/Magento/InventoryReservations/Model/ResourceModel/CleanupReservations.php
  app/code/Magento/InventoryReservations/Model/ResourceModel/GetReservationsQuantity.php
  app/code/Magento/InventoryReservations/etc/di.xml
  app/code/Magento/InventoryReservationsApi/Module/CleanupReservationsInterface.php
  app/code/Magento/InventoryReservationsApi/Module/GetReservationsQuantityInterface.php
  app/code/Magento/InventorySales/Model/GetProductSalableQty.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsCorrectQtyCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/SalesQuoteItem/AddSalesQuoteItemOnNotDefaultStockTest.php
  app/code/Magento/InventorySales/Test/Integration/Stock/GetProductSalableQtyTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringBackItemQtyTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRegisterProductsSaleTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRevertProductsSaleTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnCanSubtractQtySetToZeroTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnUseConfigManageStockSetToZeroTest.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventoryShipping/Test/Integration/SourceDeductionForVirtualProductsOnDefaultStockTest.php
  app/code/Magento/InventoryShipping/Test/Integration/SourceDeductionForVirtualProductsOnMultiStockTest.php
Labels: Modularity

#1047 MSI-954: [Configuration-Catalog-Products-Simple product] Simple Produ…
  app/code/Magento/Inventory/Test/Acceptance/ActionGroup/FillMainProductFormInMultiSourceModeActionGroup.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesEditFormSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/SimpleProductAssignedToNonDefaultSourceCreatedByAdminUserTest.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiStockData.xml
Labels: MFTF (Functional Test Coverage), approved

#1040 MSI-933: [Configuration-Sources] Pagination worked in Manage Sources grid - Admin user
  app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageSourcesPage.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageSourcesGridSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminPaginationWorkedInManageSourcesGridTest.xml
  app/code/Magento/InventoryApi/Test/Acceptance/Data/MsiSourceData.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Ui/ActionGroup/AdminDataGridPaginationActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Ui/ActionGroup/AdminGridFilterSearchResultsActionGroup.xml
Labels: MFTF (Functional Test Coverage), approved

#1038 MSI-953: [Configuration-Catalog-Products-Simple product] Simple Product created on Single stock mode by Admin user
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminCreateSimpleProductOnSingleStockMode.xml
Labels: MFTF (Functional Test Coverage), approved

#1032 MSI-950: [Configuration-Stocks-Delete Stock] Stock can not be deleted…
  app/code/Magento/Inventory/Test/Acceptance/Page/AdminManageStockPage.xml
  app/code/Magento/Inventory/Test/Acceptance/Section/AdminManageStockFormSection.xml
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminStockCannotBeDeletedOnStockPageWhenSalesChannelIsAssignedTest.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/ActionGroup/AdminCreateStoreGroupActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/ActionGroup/DeleteCustomWebsiteActionGroup.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Data/StoreGroupData.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Data/WebsiteData.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Metadata/website-meta.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Page/AdminSystemStoreGroupPage.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Page/AdminSystemWebsiteEditPage.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Section/AdminNewStoreGroupActionsSection.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Section/AdminStoresDeleteWebsiteSection.xml
Labels: MFTF (Functional Test Coverage), approved

#1030 MSI-969: [Configuration-Catalog-Products-Configurable product] Manage Stock on Configuration page turned off in admin for Configurable Product on Default stock
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminConfigurableProductManageStockOnDefaultStock.xml
Labels: MFTF (Functional Test Coverage), approved

#1104 Source Selection algorithm modularity
  app/code/Magento/InventoryShipping/Controller/Adminhtml/SourceSelection/ProcessAlgorithm.php
  app/code/Magento/InventoryShipping/Model/InventoryRequestFromOrderFactory.php
  app/code/Magento/InventoryShipping/Observer/VirtualSourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/Ui/Component/Control/SourceSelection/AlgorithmSelectionButton.php
  app/code/Magento/InventoryShipping/Ui/DataProvider/GetSourcesByStockIdSkuAndQty.php
  app/code/Magento/InventoryShipping/composer.json
  app/code/Magento/InventorySourceSelection/Model/Algorithms/PriorityBasedAlgorithm.php
  app/code/Magento/InventorySourceSelection/Model/GetDefaultSourceSelectionAlgorithmCode.php
  app/code/Magento/InventorySourceSelection/Model/SourceSelectionService.php
  app/code/Magento/InventorySourceSelection/composer.json
  app/code/Magento/InventorySourceSelection/etc/di.xml
  app/code/Magento/InventorySourceSelectionApi/Api/GetDefaultSourceSelectionAlgorithmCodeInterface.php
  app/code/Magento/InventorySourceSelectionApi/Model/GetSourceSelectionAlgorithmList.php
  app/code/Magento/InventorySourceSelectionApi/Model/SourceSelectionInterface.php
  app/code/Magento/InventorySourceSelectionApi/Test/Api/SourceSelectionServiceTest.php
  app/code/Magento/InventorySourceSelectionApi/etc/di.xml
Labels: Modularity

#1114 Move Api\AppendReservationsInterface and Api\ReservationBuilderInterface to Model namespace
  app/code/Magento/InventoryReservations/Model/AppendReservations.php
  app/code/Magento/InventoryReservations/Model/Reservation.php
  app/code/Magento/InventoryReservations/Model/ReservationBuilder.php
  app/code/Magento/InventoryReservations/Model/ResourceModel/CleanupReservations.php
  app/code/Magento/InventoryReservations/Model/ResourceModel/GetReservationsQuantity.php
  app/code/Magento/InventoryReservations/Model/ResourceModel/SaveMultiple.php
  app/code/Magento/InventoryReservations/Test/Unit/Model/ReservationBuilderTest.php
  app/code/Magento/InventoryReservations/etc/di.xml
  app/code/Magento/InventoryReservationsApi/Model/AppendReservationsInterface.php
  app/code/Magento/InventoryReservationsApi/Model/ReservationBuilderInterface.php
  app/code/Magento/InventoryReservationsApi/Model/ReservationInterface.php
  app/code/Magento/InventorySales/Model/PlaceReservationsForSalesEvent.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessBackItemQtyPlugin.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRevertProductsSalePlugin.php
  app/code/Magento/InventorySales/Plugin/InventoryReservationsApi/PreventAppendReservationOnNotManageItemsInStockPlugin.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsSalableWithReservationsConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/Stock/GetProductSalableQtyTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringBackItemQtyTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRegisterProductsSaleTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRevertProductsSaleTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnCanSubtractQtySetToZeroTest.php
  app/code/Magento/InventorySales/Test/Integration/StockManagement/ReservationPlacingOnUseConfigManageStockSetToZeroTest.php
  app/code/Magento/InventorySales/etc/di.xml
Labels: Modularity

#1120 Fix hard dependency InventoryCache module on Inventory module
  app/code/Magento/InventoryCache/Model/ResourceModel/GetProductIdsBySourceItemIds.php
  app/code/Magento/InventoryCache/composer.json
  app/code/Magento/InventoryCache/etc/di.xml
Labels: Modularity

#1121 #1116 Resolve dependency InventoryAdminUi on Inventory module
  app/code/Magento/Inventory/composer.json
  app/code/Magento/InventoryAdminUi/Model/OptionSource/CarrierSource.php
  app/code/Magento/InventoryAdminUi/Model/OptionSource/RegionSource.php
  app/code/Magento/InventoryAdminUi/Ui/Component/Listing/Column/Region.php
  app/code/Magento/InventoryAdminUi/composer.json
  app/code/Magento/InventoryAdminUi/etc/adminhtml/system.xml
  app/code/Magento/InventoryAdminUi/etc/module.xml
Labels: Inventory Modularity, Modularity

#1122 Removed Inventory module dependency from InventoryCatalog module
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/PriorityValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/SourceCodeValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/StockIdValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/StockSourceLinksValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/ValidatorChain.php
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryApi/Api/StockSourceLinkValidatorInterface.php
  app/code/Magento/InventoryCatalog/Model/StockSourceLink/Validator/AssignToDefaultStockDefaultSourceValidator.php
  app/code/Magento/InventoryCatalog/Setup/Operation/AssignDefaultSourceToDefaultStock.php
  app/code/Magento/InventoryCatalog/Setup/Operation/UpdateInventorySourceItem.php
  app/code/Magento/InventoryCatalog/composer.json
  app/code/Magento/InventoryCatalog/etc/di.xml
Labels: Modularity

#1035 MSI-1033: Saving configurable product automatically makes its children in stock
  app/code/Magento/InventoryConfigurableProduct/Model/GetQuantityInformationPerSource.php
Labels: Top 10 PRs

#1108 Move Multi Dimension indexation from Framework to InventoryMultiDimensionIndex modules
  app/code/Magento/InventoryCache/Model/ResourceModel/GetProductIdsByStockIds.php
  app/code/Magento/InventoryConfigurableProductIndexer/Indexer/SelectBuilder.php
  app/code/Magento/InventoryConfigurableProductIndexer/Indexer/SourceItem/SourceItemIndexer.php
  app/code/Magento/InventoryConfigurableProductIndexer/Indexer/Stock/StockIndexer.php
  app/code/Magento/InventoryConfigurableProductIndexer/composer.json
  app/code/Magento/InventoryIndexer/Indexer/IndexHandler.php
  app/code/Magento/InventoryIndexer/Indexer/IndexStructure.php
  app/code/Magento/InventoryIndexer/Indexer/SourceItem/SourceItemIndexer.php
  app/code/Magento/InventoryIndexer/Indexer/Stock/StockIndexer.php
  app/code/Magento/InventoryIndexer/Model/StockIndexTableNameResolver.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/RemoveIndexData.php
  app/code/Magento/InventoryIndexer/composer.json
  app/code/Magento/InventoryMultiDimensionalIndexerApi/LICENSE.txt
  app/code/Magento/InventoryMultiDimensionalIndexerApi/LICENSE_AFL.txt
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/Alias.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/AliasFactory.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/Dimension.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/DimensionFactory.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexHandlerInterface.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexName.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexNameBuilder.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexNameResolver.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexNameResolverInterface.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexStructureInterface.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexTableSwitcher.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Model/IndexTableSwitcherInterface.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/README.md
  app/code/Magento/InventoryMultiDimensionalIndexerApi/Test/Unit/IndexTableSwitcherTest.php
  app/code/Magento/InventoryMultiDimensionalIndexerApi/composer.json
  app/code/Magento/InventoryMultiDimensionalIndexerApi/etc/di.xml
  app/code/Magento/InventoryMultiDimensionalIndexerApi/etc/module.xml
  app/code/Magento/InventoryMultiDimensionalIndexerApi/registration.php
  app/etc/di.xml
  composer.json
  composer.lock
Labels: Modularity

#1130 Inventory & inventoryApi modularity
  app/code/Magento/Inventory/Model/ResourceModel/Source.php
  app/code/Magento/Inventory/Model/ResourceModel/Source/Collection.php
  app/code/Magento/Inventory/Model/Source/Command/Save.php
  app/code/Magento/Inventory/Model/Source/Validator/CarrierLinksValidator.php
  app/code/Magento/Inventory/Model/Source/Validator/CodeValidator.php
  app/code/Magento/Inventory/Model/Source/Validator/CountryValidator.php
  app/code/Magento/Inventory/Model/Source/Validator/NameValidator.php
  app/code/Magento/Inventory/Model/Source/Validator/PostcodeValidator.php
  app/code/Magento/Inventory/Model/SourceCarrierLinkManagement.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/QuantityValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/SkuValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/SourceCodeValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/SourceItemsValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/StatusValidator.php
  app/code/Magento/Inventory/Model/Stock/Command/Save.php
  app/code/Magento/Inventory/Model/Stock/Validator/NameValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/PriorityValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/SourceCodeValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/StockIdValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/StockSourceLinksValidator.php
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryApi/Model/SourceCarrierLinkManagementInterface.php
  app/code/Magento/InventoryApi/Model/SourceItemValidatorChain.php
  app/code/Magento/InventoryApi/Model/SourceItemValidatorInterface.php
  app/code/Magento/InventoryApi/Model/SourceValidatorChain.php
  app/code/Magento/InventoryApi/Model/SourceValidatorInterface.php
  app/code/Magento/InventoryApi/Model/StockSourceLinkValidatorChain.php
  app/code/Magento/InventoryApi/Model/StockSourceLinkValidatorInterface.php
  app/code/Magento/InventoryApi/Model/StockValidatorChain.php
  app/code/Magento/InventoryApi/Model/StockValidatorInterface.php
  app/code/Magento/InventoryApi/etc/di.xml
  app/code/Magento/InventoryCatalog/Model/StockSourceLink/Validator/AssignToDefaultStockDefaultSourceValidator.php
  app/code/Magento/InventoryCatalog/etc/di.xml
Labels: Modularity

#1134 Inventory Configuration modularity
  app/code/Magento/InventoryBundle/Plugin/InventoryConfiguration/IsSourceItemManagementAllowedForProductType/DisableBundleTypePlugin.php
  app/code/Magento/InventoryBundle/composer.json
  app/code/Magento/InventoryBundle/etc/di.xml
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/UpdateSourceItemAtLegacyStockItemSavePlugin.php
  app/code/Magento/InventoryCatalog/composer.json
  app/code/Magento/InventoryCatalogAdminUi/Observer/ProcessSourceItemsObserver.php
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/Quantity.php
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItems.php
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/StockStatus.php
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Listing/Modifier/QuantityPerSource.php
  app/code/Magento/InventoryCatalogAdminUi/composer.json
  app/code/Magento/InventoryConfiguration/Model/GetAllowedProductTypesForSourceItemManagement.php
  app/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType.php
  app/code/Magento/InventoryConfiguration/etc/di.xml
  app/code/Magento/InventoryConfigurationApi/Model/GetAllowedProductTypesForSourceItemManagementInterface.php
  app/code/Magento/InventoryConfigurationApi/Model/IsSourceItemManagementAllowedForProductTypeInterface.php
  app/code/Magento/InventoryGroupedProduct/Plugin/InventoryConfiguration/IsSourceItemManagementAllowedForProductType/DisableGroupedTypePlugin.php
  app/code/Magento/InventoryGroupedProduct/composer.json
  app/code/Magento/InventoryGroupedProduct/etc/di.xml
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
  app/code/Magento/InventoryLowQuantityNotification/Observer/ProcessSourceItemConfigurationsObserver.php
  app/code/Magento/InventoryLowQuantityNotification/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php
  app/code/Magento/InventoryLowQuantityNotification/composer.json
  app/code/Magento/InventorySales/Model/CheckItemsQuantity.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsSalableWithReservationsCondition.php
  app/code/Magento/InventorySales/Model/PlaceReservationsForSalesEvent.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessBackItemQtyPlugin.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessRevertProductsSalePlugin.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventorySalesAdminUi/Ui/Component/Listing/Column/SalableQuantity.php
  app/code/Magento/InventorySalesAdminUi/Ui/DataProvider/Product/Form/Modifier/SalableQuantity.php
  app/code/Magento/InventorySalesAdminUi/composer.json
Labels: Modularity

#1077 MSI-793: Incorrect process of Out-of-Stock Threshold
  app/code/Magento/InventoryCatalog/Model/ResourceModel/SetDataToLegacyStockStatus.php
  app/code/Magento/InventoryCatalog/Model/SourceItem/SourceItemsSave.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetDataToLegacyCatalogInventoryAtSourceItemsSavePlugin.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetToZeroLegacyCatalogInventoryAtSourceItemsDeletePlugin.php
  app/code/Magento/InventoryCatalog/composer.json
  app/code/Magento/InventoryCatalog/etc/di.xml
  app/code/Magento/InventoryConfiguration/Model/GetStockItemConfiguration.php
Labels: Top 10 PRs, WIP

#1153 MSI-1029: Configurable Product Presents on Category Page When All It'…
  app/code/Magento/InventoryCatalog/Model/SourceItemsSaveSynchronization/SetDataToLegacyCatalogInventory.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetDataToLegacyCatalogInventoryAtSourceItemsSavePlugin.php
Labels: QA Passed, Top 10 PRs

#1193 Fix modularity of InventoryShipping module
  app/code/Magento/InventoryShipping/Model/GetItemsToDeduct.php
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
  app/code/Magento/InventoryShipping/Plugin/Sales/Shipment/AssignSourceCodeToShipmentPlugin.php
  app/code/Magento/InventoryShipping/etc/events.xml
Labels: Modularity, WIP

#1014 MSI-992: Cannot add Configurable product to cart on Custom Stock.
  app/code/Magento/InventoryBundle/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryBundle/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryBundle/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryBundle/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryBundle/Test/_files/default_stock_bundle_products.php
  app/code/Magento/InventoryBundle/Test/_files/default_stock_bundle_products_rollback.php
  app/code/Magento/InventoryCatalog/Model/GetSkusByProductIds.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetProductStockStatusBySkuPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetProductStockStatusPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetStockStatusBySkuPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetStockStatusPlugin.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Model/ResourceModel/Stock/Status/AdaptAddStockStatusToSelectPlugin.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusBySkuTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusTest.php
  app/code/Magento/InventoryCatalog/etc/di.xml
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusBuSkuOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusBySkuTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/default_stock_configurable_products.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/default_stock_configurable_products_rollback.php
  app/code/Magento/InventoryGroupedProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryGroupedProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetProductStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryGroupedProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusBySkuOnDefaultStockTest.php
  app/code/Magento/InventoryGroupedProduct/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusOnDefaultStockTest.php
  app/code/Magento/InventoryGroupedProduct/Test/_files/default_stock_grouped_products.php
  app/code/Magento/InventoryGroupedProduct/Test/_files/default_stock_grouped_products_rollback.php
Labels: QA Passed, Top 10 PRs, WIP

#1194 Eliminate dependency on Inventory module on Shipping module
  app/code/Magento/Inventory/Model/Source.php
  app/code/Magento/Inventory/composer.json
  app/code/Magento/Inventory/etc/di.xml
  app/code/Magento/InventoryAdminUi/Model/OptionSource/CarrierSource.php
  app/code/Magento/InventoryAdminUi/Model/Source/SourceCarrierDataProcessor.php
  app/code/Magento/InventoryAdminUi/Model/Source/SourceHydrator.php
  app/code/Magento/InventoryAdminUi/Ui/DataProvider/SourceDataProvider.php
  app/code/Magento/InventoryAdminUi/composer.json
  app/code/Magento/InventoryAdminUi/view/adminhtml/ui_component/inventory_source_form.xml
  app/code/Magento/InventoryShipping/Model/Source/Validator/CarrierLinksValidator.php
  app/code/Magento/InventoryShipping/composer.json
  app/code/Magento/InventoryShipping/etc/di.xml
Labels: Modularity

#1085 MSI-858: [Configuration-Stocks] Admin user applied Mass action: Delet…
  app/code/Magento/Inventory/Test/Acceptance/Test/AdminAllStocksDeletedFromGridExceptDefault.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Ui/Section/AdminGridControlsSection.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Ui/Section/AdminMessagesSection.xml
Labels: MFTF (Functional Test Coverage), approved

#1255 Resolve dependency of InventoryCatalogAdminUi on Inventory module
  app/code/Magento/InventoryCatalogAdminUi/Model/GetSourceItemsDataBySku.php
  app/code/Magento/InventoryCatalogAdminUi/Model/OptionSource/SourceItemStatus.php
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItems.php
  app/code/Magento/InventoryCatalogAdminUi/composer.json
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/product_form.xml
Labels: Award: advanced, Award: special achievement, Modularity

#1252 Wrong salable quantity after shipment created for bundle product type
  app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php
Labels: Bugfixing, current sprint, regression phase 2

#1272 Reservations created twice for Configurable Products Virtual child
  app/code/Magento/InventoryShipping/Model/InventoryRequestFromInvoiceFactory.php
Labels: Bugfixing, regression phase 2

#1274 Cannot cancel order with deleted product.
  app/code/Magento/InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
  app/code/Magento/InventorySales/Plugin/CatalogInventory/StockManagement/ProcessBackItemQtyPlugin.php
Labels: Bugfixing, regression phase 2
