Repository magento/inventory, pull requests merged in 2018-12, with the labels that each got.

#1927 magento-engcom/msi - MFTF MSI suite enabling dbBackup
  app/code/Magento/InventoryAdminUi/Test/Mftf/Suite/msi-suite.xml
Labels: MFTF (Functional Test Coverage), Release Line: 2.3

#1934 Merge 2.3-develop into 2.3.0-release
  app/code/Magento/Catalog/Model/Indexer/Category/Flat/Action/Full.php
  app/code/Magento/Catalog/Model/Product/Gallery/GalleryManagement.php
  app/code/Magento/Cms/Test/Mftf/Test/AdminAddImageToCMSPageTinyMCE3Test.xml
  app/code/Magento/Config/App/Config/Type/System.php
  app/code/Magento/Customer/etc/db_schema.xml
  app/code/Magento/Integration/etc/adminhtml/system.xml
  app/code/Magento/Integration/etc/db_schema.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Suite/msi-suite.xml
  app/code/Magento/Review/Model/ResourceModel/Review/Product/Collection.php
  app/code/Magento/Sales/etc/db_schema.xml
  composer.json
  composer.lock
  dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php
  dev/tests/functional/tests/app/Magento/Bundle/Test/Block/Adminhtml/Product/Composite/Configure.xml
  dev/tests/functional/tests/app/Magento/ConfigurableProduct/Test/Block/Adminhtml/Product/Composite/Configure.xml
  dev/tests/functional/tests/app/Magento/Downloadable/Test/Block/Adminhtml/Product/Composite/Configure.xml
  dev/tests/integration/testsuite/Magento/Integration/Block/Adminhtml/System/Config/OauthSectionTest.php
  dev/tests/integration/testsuite/Magento/Review/Model/ResourceModel/Review/Product/CollectionTest.php
  lib/web/mage/adminhtml/wysiwyg/tiny_mce/setup.js
  lib/web/mage/adminhtml/wysiwyg/tiny_mce/tinymce4Adapter.js
Labels: 2.3.0-release

#1937 MSI-1921: Removed redundant join on 'catalog_product_entity'
  app/code/Magento/InventoryCatalogSearch/Plugin/Model/Adapter/Mysql/Aggregation/DataProvider/SelectBuilderForAttribute/AdaptApplyStockConditionToSelectPlugin.php
  app/code/Magento/InventoryCatalogSearch/composer.json
Labels: Partner: Atwix, partners-contribution

#1950 MSI-1921: Replaced inventory_stock_1 with cataloginventory_stock_status until bundle product is not implemented
  app/code/Magento/InventoryCatalog/Model/ResourceModel/AddStockDataToCollection.php
  app/code/Magento/InventoryCatalogSearch/Plugin/Search/FilterMapper/AdaptStockStatusFilterPlugin.php
  app/code/Magento/InventoryConfigurableProduct/Model/ResourceModel/Product/StockStatusBaseSelectProcessor.php
  app/code/Magento/InventoryConfigurableProduct/Plugin/Model/ResourceModel/Attribute/IsSalableOptionSelectBuilder.php
  app/code/Magento/InventoryConfigurableProduct/composer.json
Labels: QA Passed

#1955 Fix issue 1922
  app/code/Magento/InventoryLowQuantityNotification/Model/ResourceModel/BulkConfigurationTransfer.php
Labels: Partner: Comwrap, partners-contribution

#1676 MSI-1667: 'Salable Quantity' column is empty after deploying small.xml preset.
  app/code/Magento/Inventory/Model/ResourceModel/SourceItem/SaveMultiple.php
  app/code/Magento/InventorySetupFixtureGenerator/LICENSE.txt
  app/code/Magento/InventorySetupFixtureGenerator/LICENSE_AFL.txt
  app/code/Magento/InventorySetupFixtureGenerator/Plugin/Setup/Model/FixtureGenerator/EntityGeneratorFactory/UpdateCustomTableMapPlugin.php
  app/code/Magento/InventorySetupFixtureGenerator/README.md
  app/code/Magento/InventorySetupFixtureGenerator/composer.json
  app/code/Magento/InventorySetupFixtureGenerator/etc/di.xml
  app/code/Magento/InventorySetupFixtureGenerator/etc/module.xml
  app/code/Magento/InventorySetupFixtureGenerator/registration.php
  composer.json
  composer.lock
Labels: Performance
