Repository magento/inventory, pull requests merged in 2019-10, with the labels that each got.

#2603 MSI-2599: Clearing index with wrong predicate
  app/code/Magento/InventoryConfigurableProductIndexer/Indexer/Stock/StockIndexer.php
  app/code/Magento/InventoryGroupedProductIndexer/Indexer/Stock/StockIndexer.php
  app/code/Magento/InventoryIndexer/Indexer/Stock/PrepareIndexDataForClearingIndex.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/PrepareIndexDataForClearingIndexTest.php
Labels: Auto-Tests: Covered, Award: bug fix, Award: test coverage, Partner: TechDivision, Progress: review, partners-contribution

#2613 Increase MFTF tests coverage.
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/AdminAssertSalableQtySingleStockModeActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Data/CatalogInventoryData.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Section/AdminProductGridSection.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationBundleProductSoldOutSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoPartialRefundFullInvoiceFullShipmentBundleProductDefaultStock.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoPartialRefundFullInvoicePartialShipmentBundleProductDefaultStock.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateScheduledPermanentUpdateDownloadableProductCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateScheduledPermanentUpdateDownloadableProductDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithBundleAndSimpleProductsSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminSimpleProductDisabledManageStockInConfigurationDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontCacheValidationConfigurableProductSoldOutInSingleStockMode.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontCacheValidationSimpleProductSoldOutInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerOrderDownloadableProductDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontQuickOrderConfigurableProductsCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontQuickOrderSimpleProductCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontQuickOrderSimpleProductsCustomStockTest.xml
  app/code/Magento/InventoryAdvancedCheckout/Test/Mftf/Test/AddSimpleFromCustomStockBySkuFromCustomerAccountTest.xml
  app/code/Magento/InventoryRequisitionList/Test/Mftf/Test/OrderWithMultipleConfigurableProductsAdditionalStock.xml
Labels: Progress: changes requested

#2621 Shipment Creation MFTF tests modification to support source selection algorithm verification with grouped and configurable product types.
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/AdminSourceSelectionAlgorithmByPriorityActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Data/CatalogInventoryData.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoWholeOrderWithConfigurableProductFromCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderGroupedProductCustomStock.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithConfigurableProductFromCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithConfigurableProductFromDefaultSourceTest.xml
Labels: MFTF

#2618 Update module-inventory-distance-based-source-selection/etc/db_schema.xml
  app/code/Magento/InventoryDistanceBasedSourceSelection/etc/db_schema.xml
Labels: Progress: changes requested

#2623 MSI-2620: Decimal value allowed for input for quantity on source for product
  app/code/Magento/InventoryAdminUi/Test/Mftf/Data/CatalogInventoryData.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Section/AdminProductSourcesFormSection.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminDecimalQtySimpleProductCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/VerifyThatMessageOnlyZeroLeftNotAppearedOnSimpleProductPageOnFrontendTest.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/js/product/form/sources/qty.js
Labels: QA Passed

#2594 Unskip Web-Api PreventDefaultSourceDisablingTest.
  app/code/Magento/InventoryCatalogApi/Test/Api/PreventDefaultSourceDisablingTest.php
Labels: Progress: review

#2602 MSI-2593-Allow-to-filter-Store-Pickup-orders-on-order-grid.
  app/code/Magento/InventoryInStorePickup/Observer/UpdateOrderGrid.php
  app/code/Magento/InventoryInStorePickup/etc/db_schema.xml
  app/code/Magento/InventoryInStorePickup/etc/db_schema_whitelist.json
  app/code/Magento/InventoryInStorePickup/etc/di.xml
  app/code/Magento/InventoryInStorePickup/etc/events.xml
  app/code/Magento/InventoryInStorePickupAdminUi/view/adminhtml/ui_component/sales_order_grid.xml
Labels: Auto-Tests: Not Covered, Award: advanced, Partner: Vaimo, Progress: review, Store Pickup, partners-contribution

#2280 Delivery method selector on checkout shipping step
  app/code/Magento/InventoryInStorePickup/Test/_files/source_addresses.php
  app/code/Magento/InventoryInStorePickupFrontend/LICENSE.txt
  app/code/Magento/InventoryInStorePickupFrontend/LICENSE_AFL.txt
  app/code/Magento/InventoryInStorePickupFrontend/Model/GetCurrentWebsiteCode.php
  app/code/Magento/InventoryInStorePickupFrontend/Model/Ui/WebsiteCodeConfigProvider.php
  app/code/Magento/InventoryInStorePickupFrontend/README.md
  app/code/Magento/InventoryInStorePickupFrontend/composer.json
  app/code/Magento/InventoryInStorePickupFrontend/etc/frontend/di.xml
  app/code/Magento/InventoryInStorePickupFrontend/etc/module.xml
  app/code/Magento/InventoryInStorePickupFrontend/i18n/en_US.csv
  app/code/Magento/InventoryInStorePickupFrontend/registration.php
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/layout/checkout_index_index.xml
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/requirejs-config.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/css/source/_module.less
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/model/pickup-address-converter.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/model/pickup-locations-service.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/model/quote-ext.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/model/resource-url-manager.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/model/shipping-rate-processor/store-pickup-address.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/view/form/element/email.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/view/shipping-information/address-renderer/store-pickup-address.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/view/store-pickup.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/js/view/store-selector.js
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/delivery-method-selector.html
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/form/element/email.html
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/shipping-information/address-renderer/store-pickup-address.html
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/store-pickup.html
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/store-selector.html
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/store-selector/popup-item.html
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/store-selector/popup.html
  app/code/Magento/InventoryInStorePickupFrontend/view/frontend/web/template/store-selector/selected-location.html
  app/code/Magento/InventoryInStorePickupQuote/Model/ToQuoteAddress.php
  app/code/Magento/InventoryInStorePickupQuote/etc/di.xml
  composer.json
  composer.lock
Labels: Award: MFTF test coverage, Award: advanced, Award: bug fix, Award: category of expertise, Award: complex, Award: special achievement, Award: test coverage, Partner: creativestyle, Progress: review, Store Pickup, partners-contribution

#2636 MC-21773: [MFTF] Failing Test: EndToEndB2CGuestUserMysqlTest
  app/code/Magento/Inventory/Test/Mftf/Test/SkippedTest.xml
Labels: Progress: approved

#2643 Fix extensibility for \Magento\InventorySales\Test\Api\OrderPlacementBase abstract class.
  app/code/Magento/InventorySales/Test/Api/OrderPlacementBase.php
Labels: Award: category of expertise, Partner: ISM eCompany, Progress: approved, partners-contribution

#2654 MC-21944: Unable to save a credit memo
  app/code/Magento/InventoryApi/Test/_files/source_items_numeric_skus.php
  app/code/Magento/InventoryApi/Test/_files/source_items_numeric_skus_rollback.php
  app/code/Magento/InventorySourceSelectionApi/Model/GetInStockSourceItemsBySkusAndSortedSource.php
  app/code/Magento/InventorySourceSelectionApi/Test/Integration/GetSourceItemsBySkusAndSortedSourceTest.php
Labels: Auto-Tests: Covered, QA Passed

#2664 MSI-2657: Eliminate button 'Ship' in orders placed with Store pickup method.
  app/code/Magento/InventoryInStorePickupAdminUi/Plugin/Sales/Block/Adminhtml/Order/ProcessShipButtonPlugin.php
  app/code/Magento/InventoryInStorePickupAdminUi/etc/adminhtml/di.xml
  app/code/Magento/InventoryInStorePickupMultishipping/Plugin/Quote/RemoveInStorePickupDataInMultishippingModePlugin.php
Labels: Progress: review, QA Passed, Store Pickup

#2665 MSI-2659: Latitude and longitude values don't update when set new postcode for source
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/Save.php
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminUpdateSourceDataTest.xml
Labels: Progress: approved, QA Passed

#2646 Msi 2631 Source selector disappear in store pickup orders placement from admin panel
  app/code/Magento/InventoryInStorePickupAdminUi/view/adminhtml/web/order/create/scripts-mixin.js
Labels: Auto-Tests: Not Covered, Award: bug fix, Award: category of expertise, Progress: approved, QA Passed, Store Pickup

#2637 Double product reservation while using multishipping.
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/StorefrontMultishippingPlaceOrderActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/StorefrontSelectShippingInfoActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Section/MultishippingShippingMethodSection.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontMultishippingLoggedInCustomerOrderedSimpleProductAllQtyCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontMultishippingLoggedInCustomerOrderedSimpleProductWithNotAvailableQtyCustomStockTest.xml
  app/code/Magento/InventorySales/etc/events.xml
Labels: Progress: approved, QA Passed

#2632 MSI-2385: Reorder buttons in backend, for product which no longer is tied to stock
  app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
  app/code/Magento/InventorySales/Test/Integration/StockState/CheckQuoteItemQtyPluginTest.php
Labels: Auto-Tests: Covered, Progress: review, QA Passed

#2669 MSI-2666: Eliminate Tracking information from shipment document for Store pickup order.
  app/code/Magento/InventoryInStorePickupShippingAdminUi/Plugin/Shipping/Block/Adminhtml/View/ShipmentTrackingButtonPlugin.php
  app/code/Magento/InventoryInStorePickupShippingAdminUi/Plugin/Shipping/Controller/Order/Shipment/View/ShipmentTrackingPlugin.php
  app/code/Magento/InventoryInStorePickupShippingAdminUi/composer.json
  app/code/Magento/InventoryInStorePickupShippingAdminUi/etc/adminhtml/di.xml
Labels: QA Passed, Store Pickup

#2572 Create Stock table at the same time stock is created #2569
  app/code/Magento/Inventory/Model/Stock.php
  app/code/Magento/Inventory/Test/Integration/CreateStockTableTest.php
  app/code/Magento/InventoryCache/Model/ResourceModel/GetProductIdsByStockIds.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Model/Indexer/ModifySelectInProductPriceIndexFilter.php
  app/code/Magento/InventoryIndexer/Model/ResourceModel/GetStockItemData.php
  app/code/Magento/InventoryIndexer/Observer/StockSaveObserver.php
  app/code/Magento/InventoryIndexer/Test/Integration/Indexer/RemoveIndexData.php
  app/code/Magento/InventoryIndexer/etc/events.xml
  app/code/Magento/InventoryProductAlert/Test/Integration/ProductAlertTest.php
Labels: Award: category of expertise, Award: test coverage, Partner: TechDivision, Progress: approved, QA Passed, partners-contribution

#2649 MC-21430: [Functional Test] Magento\FunctionalTestingFramework.functi…
  app/code/Magento/Inventory/Test/Mftf/Test/AdminUseDecimalQuantityOnSimpleProductTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminUseDecimalQuantityOnVirtualProductTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/AdminEnableBackordersOnProductEditPageActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Section/AdminProductSourcesFormSection.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminBackordersEnabledOnProductPageAndAppliedToSimpleProductOnSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminOutOfStockThresholdAppliedToDownloadableProductInAdvancedInventoryOnProductPageTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminUserApplyOnlyXLeftTreshholdForSimpleProductOnTestSourceInCombinationWithNegativeOutOfStockThresholdAndBackordersTest.xml
  app/code/Magento/InventoryCatalogAdminUi/Test/Mftf/Test/AdminCreateOrderWithSimpleProductInSingleStockModeWithBackordersTest.xml
  app/code/Magento/InventoryCatalogAdminUi/Test/Mftf/Test/AdminCreateOrderWithVirtualProductInSingleStockModeWithBackordersTest.xml
Labels: Progress: changes requested

#2630 MSI-2619: Stock status for sold out product don't change to 'Out of stock"
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontCacheValidationSimpleProductSoldOutOnDefaultStockTest.xml
  app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php
Labels: Progress: approved, QA Passed

#2578 MSI-2522 improve result output for reservation cli
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistencies.php
  app/code/Magento/InventoryReservationCli/Model/GetCompleteOrderStateList.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersInFinalState.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersInNotFinalState.php
  app/code/Magento/InventoryReservationCli/Model/GetSalableQuantityInconsistencies.php
  app/code/Magento/InventoryReservationCli/Model/ResourceModel/GetOrderDataForOrderInFinalState.php
  app/code/Magento/InventoryReservationCli/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalState.php
  app/code/Magento/InventoryReservationCli/Model/ResourceModel/GetOrdersTotalCount.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/AddCompletedOrdersToForUnresolvedReservations.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/AddExpectedReservations.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/Collector.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterCompleteOrders.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterExistingOrders.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterIncompleteOrders.php
Labels: Award: advanced, Award: bug fix, Award: category of expertise, Award: complex, Award: special achievement, Partner: TechDivision, Progress: review, QA Passed, partners-contribution
