Repository magento/inventory, pull requests merged in 2019-01, with the labels that each got.

#1986 MSI-1866: Changes to Source Selection Service Contracts
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Algorithms/DistanceBasedAlgorithm.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Convert/AddressToComponentsString.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Convert/AddressToQueryString.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Convert/AddressToString.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GetDistanceFromSourceToAddress.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GetLatLngFromSource.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GoogleMap/GetLatLngFromAddress.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/Offline/GetLatLngFromAddress.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/GetAddressFromOrder.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/InventoryRequestBuilder/FromOrder/DistanceBuilder.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/ResourceModel/GetGeoNameDataByAddress.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/composer.json
  app/code/Magento/InventoryDistanceBasedSourceSelection/etc/di.xml
  app/code/Magento/InventoryDistanceBasedSourceSelectionApi/Api/GetLatLngFromAddressInterface.php
  app/code/Magento/InventoryDistanceBasedSourceSelectionApi/Model/GetLatLngFromAddress.php
  app/code/Magento/InventoryDistanceBasedSourceSelectionApi/composer.json
  app/code/Magento/InventoryShipping/Model/GetSourceSelectionResultFromInvoice.php
  app/code/Magento/InventoryShipping/etc/di.xml
  app/code/Magento/InventoryShippingAdminUi/Controller/Adminhtml/SourceSelection/ProcessAlgorithm.php
  app/code/Magento/InventoryShippingAdminUi/Ui/DataProvider/GetSourcesByOrderIdSkuAndQty.php
  app/code/Magento/InventoryShippingAdminUi/Ui/DataProvider/SourceSelectionDataProvider.php
  app/code/Magento/InventoryShippingAdminUi/etc/adminhtml/di.xml
  app/code/Magento/InventorySourceSelection/Model/Address.php
  app/code/Magento/InventorySourceSelection/Model/InventoryRequestBuilder/FromOrder/DefaultBuilder.php
  app/code/Magento/InventorySourceSelection/etc/di.xml
  app/code/Magento/InventorySourceSelectionApi/Api/Data/AddressInterface.php
  app/code/Magento/InventorySourceSelectionApi/Exception/UndefinedInventoryRequestBuilderException.php
  app/code/Magento/InventorySourceSelectionApi/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php
  app/code/Magento/InventorySourceSelectionApi/Model/GetInventoryRequestFromOrder.php
  app/code/Magento/InventorySourceSelectionApi/Model/GetInventoryRequestFromOrderBuilder.php
  app/code/Magento/InventorySourceSelectionApi/Model/InventoryRequestFromOrderBuilderInterface.php
  app/code/Magento/InventorySourceSelectionApi/Model/SourceSelectionService.php
  app/code/Magento/InventorySourceSelectionApi/composer.json
  app/code/Magento/InventorySourceSelectionApi/etc/di.xml
Labels: Distance Based Algorithm

#1911 Fix The requested qty is not available
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsSalableWithReservationsCondition.php
Labels: QA Passed

#1992 MSI-1938: Some headings are not indented on Source Selection page
  app/code/Magento/Ui/view/base/web/templates/dynamic-rows/templates/default.html
Labels: QA Passed

#1868 Created tooltip for assigned sources more than 5 for every stock item
  app/code/Magento/InventoryAdminUi/view/adminhtml/web/js/stock/grid/cell/assigned-sources.js
  app/code/Magento/InventoryAdminUi/view/adminhtml/web/template/stock/grid/cell/assigned-sources-cell.html
Labels: MageConf18, QA Passed

#2000 Remove duplicate code
  app/code/Magento/InventoryApi/etc/webapi.xml
Labels: Partner: Krish TechnoLabs, partners-contribution

#2004 Fixed issue #2003 POST /V1/inventory/source-selection-algorithm-result payload doesn't accept street_address
  app/code/Magento/InventorySourceSelection/Model/Address.php
  app/code/Magento/InventorySourceSelectionApi/Api/Data/AddressInterface.php
Labels: Community Insider: Cedcommerce, QA Failed, community-insider-contribution

#2007 Msi 2003
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Convert/AddressToQueryString.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Convert/AddressToString.php
  app/code/Magento/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GetLatLngFromSource.php
  app/code/Magento/InventorySourceSelection/Model/Address.php
  app/code/Magento/InventorySourceSelectionApi/Api/Data/AddressInterface.php
  app/code/Magento/InventorySourceSelectionApi/Model/GetInventoryRequestFromOrder.php
Labels: QA Passed
