Repository magento/inventory, pull requests merged in 2019-04, with the labels that each got.

#2125 Msi 2116 improve existing implementation of in store pickup attribute of source
  app/code/Magento/InventoryInStorePickup/Observer/Source/PopulateWithInStorePickupObserver.php
  app/code/Magento/InventoryInStorePickup/Plugin/InventoryApi/SourceRepository/LoadInStorePickupOnGetListPlugin.php
  app/code/Magento/InventoryInStorePickup/Plugin/InventoryApi/SourceRepository/LoadInStorePickupOnGetPlugin.php
  app/code/Magento/InventoryInStorePickup/Plugin/InventoryApi/SourceRepository/SaveInStorePickupPlugin.php
  app/code/Magento/InventoryInStorePickup/Test/Integration/Extension/InventorySourceExtensionTest.php
  app/code/Magento/InventoryInStorePickup/Test/Integration/Extension/OrderExtensionTest.php
  app/code/Magento/InventoryInStorePickup/etc/adminhtml/events.xml
  app/code/Magento/InventoryInStorePickup/etc/db_schema.xml
  app/code/Magento/InventoryInStorePickup/etc/db_schema_whitelist.json
  app/code/Magento/InventoryInStorePickup/etc/extension_attributes.xml
  app/code/Magento/InventoryInStorePickupAdminUi/Plugin/Ui/DataProvider/ConvertBooleanToStringPlugin.php
  app/code/Magento/InventoryInStorePickupAdminUi/Ui/Component/Listing/Column/InStorePickup.php
  app/code/Magento/InventoryInStorePickupAdminUi/Ui/Component/Listing/Column/IsPickupLocationActive.php
  app/code/Magento/InventoryInStorePickupAdminUi/etc/adminhtml/di.xml
  app/code/Magento/InventoryInStorePickupAdminUi/view/adminhtml/ui_component/inventory_source_form.xml
  app/code/Magento/InventoryInStorePickupAdminUi/view/adminhtml/ui_component/inventory_source_listing.xml
  app/code/Magento/InventoryInStorePickupApi/Api/Data/InStorePickupInterface.php
  app/code/Magento/InventoryInStorePickupApi/Api/Data/PickupLocationInterface.php
Labels: Partner: ISM eCompany, Store Pickup, partners-contribution

#2121 add the correct active menu to inventory source
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/Edit.php
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/Index.php
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/NewAction.php
Labels: Event: StrixCD, QA Passed

#2123 Passed correct websiteCode to check stock quantity when order is created using backoffice
  app/code/Magento/InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
Labels: Event: StrixCD, QA Passed

#2139 MSI-2113: In stock, 0 qty and backorders allowed products not visible…
  app/code/Magento/InventorySales/Model/ResourceModel/IsStockItemSalableCondition/BackordersCondition.php
  app/code/Magento/InventorySales/Test/Integration/GetStockItemData/BackorderConditionTest.php
Labels: QA Passed

#2149 [UI Love for Assigned Sources] Notify Quantity #2132
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/i18n/en_US.csv
  app/code/Magento/InventoryLowQuantityNotificationAdminUi/view/adminhtml/ui_component/product_form.xml
Labels: MageSpecialist + BitBull CD, Partner: MageSpecialist, QA Passed, partners-contribution

#2145 [UI Love for Assigned Sources] Unassign column
  app/code/Magento/InventoryCatalogAdminUi/i18n/en_US.csv
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/template/stock/assign-sources/action-delete.html
Labels: MageSpecialist + BitBull CD, QA Passed

#2147 [UI Love for Assigned Sources] Source code #2134
  app/code/Magento/InventoryCatalogAdminUi/i18n/en_US.csv
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/ui_component/product_form.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/template/dynamic-rows/cells/text.html
Labels: MageSpecialist + BitBull CD, Partner: MageSpecialist, QA Passed, partners-contribution

#2120 Get Rid of MySQL View usage on Default Stock
  app/code/Magento/InventoryCatalog/Model/ResourceModel/AddIsInStockFieldToCollection.php
  app/code/Magento/InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAddInStockFilterToCollectionPlugin.php
Labels: Event: StrixCD, Partner: Strix, Ready for QA, partners-contribution

#2091 MSI-2084 Introduce tests for 'GetNearbySourcesByPostcode'
  app/code/Magento/InventoryInStorePickup/Model/DistanceProvider/Offline/GetNearbySourcesByPostcode.php
  app/code/Magento/InventoryInStorePickup/Test/Integration/DistanceProvider/Offline/GetNearbySourcesByPostcodeTest.php
  app/code/Magento/InventoryInStorePickup/Test/_files/inventory_geoname.php
  app/code/Magento/InventoryInStorePickup/Test/_files/inventory_geoname_rollback.php
  app/code/Magento/InventoryInStorePickup/Test/_files/source_addresses.php
  app/code/Magento/InventoryInStorePickup/etc/module.xml
Labels: Award: test coverage, Partner: TechDivision, Store Pickup, kharkivcd19, partners-contribution

#2158 MSI-2155: Zero qty for children products when save configurable product twice
  app/code/Magento/InventoryConfigurableProductAdminUi/Observer/ProcessSourceItemsObserver.php
Labels: MSI 1.1.2 Release

#2124 GraphQL support for the new Inventory
  app/code/Magento/InventoryGraphQl/LICENSE.txt
  app/code/Magento/InventoryGraphQl/LICENSE_AFL.txt
  app/code/Magento/InventoryGraphQl/Model/Resolver/OnlyXLeftInStockResolver.php
  app/code/Magento/InventoryGraphQl/Model/Resolver/StockStatusProvider.php
  app/code/Magento/InventoryGraphQl/README.md
  app/code/Magento/InventoryGraphQl/composer.json
  app/code/Magento/InventoryGraphQl/etc/module.xml
  app/code/Magento/InventoryGraphQl/etc/schema.graphqls
  app/code/Magento/InventoryGraphQl/registration.php
  composer.json
  composer.lock
Labels: Award: special achievement, Event: StrixCD, MSI 1.1.2 Release, Partner: Strix, Ready for QA, partners-contribution

#2142 Fixed issue #2135 - source_code attribute is missing in REST API endpoint "shipments"
  app/code/Magento/InventoryShipping/Plugin/Sales/Model/Order/GetListShipmentRepositoryPlugin.php
  app/code/Magento/InventoryShipping/etc/di.xml
Labels: MSI 1.1.2 Release, MageSpecialist + BitBull CD, Partner: MageSpecialist, QA Passed, partners-contribution

#2148 Issue2140 reservation cli
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistenciesInCompletedOrders.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersInFinalState.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersWithNotCompensatedReservations.php
  app/code/Magento/InventoryReservationCli/Model/ResourceModel/GetReservationsList.php
  app/code/Magento/InventoryReservationCli/README.md
  app/code/Magento/InventoryReservationCli/Test/Integration/Model/GetListReservationsTotOrdersTest.php
  app/code/Magento/InventoryReservationCli/Test/Integration/_fixtures/broken_reservation.php
  app/code/Magento/InventoryReservationCli/Test/Integration/_fixtures/order_with_reservation.php
  app/code/Magento/InventoryReservationCli/composer.json
  app/code/Magento/InventoryReservationCli/etc/di.xml
  app/code/Magento/InventoryReservationCli/etc/module.xml
  app/code/Magento/InventoryReservationCli/registration.php
  composer.json
  composer.lock
Labels: Award: special achievement, MSI 1.1.2 Release, MageSpecialist + BitBull CD, Partner: MageSpecialist, Ready for QA, partners-contribution

#2127 Add ready for pickup button on the order page in admin panel which notifies customer that order could be picked up 2034
  app/code/Magento/InventoryInStorePickup/Model/IsOrderReadyForPickup.php
  app/code/Magento/InventoryInStorePickup/Model/NotifyOrderIsReadyForPickup.php
  app/code/Magento/InventoryInStorePickup/Model/Order/Email/Container/ReadyForPickupIdentity.php
  app/code/Magento/InventoryInStorePickup/Model/Order/Email/ReadyForPickupNotifier.php
  app/code/Magento/InventoryInStorePickup/Model/Order/Email/ReadyForPickupSender.php
  app/code/Magento/InventoryInStorePickup/Model/Order/IsFulfillable.php
  app/code/Magento/InventoryInStorePickup/Model/ResourceModel/OrderPickupLocation/GetPickupLocationCodeByOrderId.php
  app/code/Magento/InventoryInStorePickup/Model/ResourceModel/OrderPickupLocation/SaveOrderPickupLocation.php
  app/code/Magento/InventoryInStorePickup/Plugin/InventoryApi/SourceRepository/LoadInStorePickupOnGetListPlugin.php
  app/code/Magento/InventoryInStorePickup/Plugin/InventoryApi/SourceRepository/LoadInStorePickupOnGetPlugin.php
  app/code/Magento/InventoryInStorePickup/Plugin/Sales/Order/GetPickupLocationForOrderPlugin.php
  app/code/Magento/InventoryInStorePickup/Plugin/Sales/Order/SavePickupLocationForOrderPlugin.php
  app/code/Magento/InventoryInStorePickup/Test/Integration/Extension/InventorySourceExtensionTest.php
  app/code/Magento/InventoryInStorePickup/composer.json
  app/code/Magento/InventoryInStorePickup/etc/config.xml
  app/code/Magento/InventoryInStorePickup/etc/di.xml
  app/code/Magento/InventoryInStorePickup/etc/email_templates.xml
  app/code/Magento/InventoryInStorePickup/etc/module.xml
  app/code/Magento/InventoryInStorePickup/i18n/en_US.csv
  app/code/Magento/InventoryInStorePickup/view/frontend/email/order_ready_for_pickup.html
  app/code/Magento/InventoryInStorePickupAdminUi/Block/Adminhtml/Order/View/ReadyForPickup.php
  app/code/Magento/InventoryInStorePickupAdminUi/Controller/Adminhtml/Order/NotifyPickup.php
  app/code/Magento/InventoryInStorePickupAdminUi/Model/IsDisplayReadyForPickupButton.php
  app/code/Magento/InventoryInStorePickupAdminUi/composer.json
  app/code/Magento/InventoryInStorePickupAdminUi/etc/adminhtml/routes.xml
  app/code/Magento/InventoryInStorePickupAdminUi/etc/module.xml
  app/code/Magento/InventoryInStorePickupAdminUi/i18n/en_US.csv
  app/code/Magento/InventoryInStorePickupAdminUi/view/adminhtml/layout/sales_order_view.xml
  app/code/Magento/InventoryInStorePickupApi/Api/GetNearbySourcesByPostcodeInterface.php
  app/code/Magento/InventoryInStorePickupApi/Api/IsOrderReadyForPickupInterface.php
  app/code/Magento/InventoryInStorePickupApi/Api/NotifyOrderIsReadyForPickupInterface.php
  app/code/Magento/InventoryInStorePickupApi/Model/GetNearbySourcesByPostcode.php
  app/code/Magento/InventoryInStorePickupApi/composer.json
  app/code/Magento/InventoryInStorePickupApi/etc/di.xml
Labels: Partner: ISM eCompany, Store Pickup, partners-contribution

#2167 fix output issue
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistenciesInCompletedOrders.php
Labels: Partner: MageSpecialist, partners-contribution

#2117 Implement partial stock transfer API
  app/code/Magento/InventoryCatalog/Model/BulkPartialInventoryTransfer.php
  app/code/Magento/InventoryCatalog/Model/GetSourceItemsBySkuAndSourceCodes.php
  app/code/Magento/InventoryCatalog/Model/PartialInventoryTransferItem.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/TransferInventoryPartially.php
  app/code/Magento/InventoryCatalog/Model/Source/Validator/PartialTransferItemsValidator.php
  app/code/Magento/InventoryCatalog/Model/Source/Validator/PartialTransferSourceValidator.php
  app/code/Magento/InventoryCatalog/Test/Api/Bulk/PartialInventoryTransferTest.php
  app/code/Magento/InventoryCatalog/Test/Integration/GetSourceItemsBySkuAndSourceCodesTest.php
  app/code/Magento/InventoryCatalog/etc/di.xml
  app/code/Magento/InventoryCatalogApi/Api/BulkPartialInventoryTransferInterface.php
  app/code/Magento/InventoryCatalogApi/Api/Data/PartialInventoryTransferItemInterface.php
  app/code/Magento/InventoryCatalogApi/Model/PartialInventoryTransferValidatorChain.php
  app/code/Magento/InventoryCatalogApi/Model/PartialInventoryTransferValidatorInterface.php
  app/code/Magento/InventoryCatalogApi/etc/di.xml
  app/code/Magento/InventoryCatalogApi/etc/webapi.xml
Labels: Award: special achievement, MSI 1.1.2 Release, QA Passed

#1975 (MFTF)MSI mftf credit memo tests
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithSimpleProductFromCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedForWholeOrderWithSimpleProductOnDefaultStockAfterFullInvoiceAndShipmentInAdminTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedWithPartialRefundForOrderWithSimpleProductOnDefaultStockAfterFullInvoiceInAdminTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedWithPartialRefundWithSimpleProductOnDefaultStockAfterFullInvoiceAndPartialShipment.xml
  app/code/Magento/InventoryCatalogAdminUi/Test/Mftf/Section/AdminProductGridSection.xml
  dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Store/Metadata/website-meta.xml
Labels: MFTF (Functional Test Coverage)

#2012 MSI-1912: Get sku from order configurable product with custom options
  app/code/Magento/InventoryConfigurableProduct/Plugin/Sales/GetSkuFromOrderItem.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Sales/GetSkuFromOrderItemTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/order_item_with_configurable_and_options.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/order_item_with_configurable_and_options_rollback.php
  app/code/Magento/InventoryConfigurableProduct/composer.json
  app/code/Magento/InventoryConfigurableProduct/etc/di.xml
  app/code/Magento/InventoryShippingAdminUi/Model/ShipmentProvider.php
Labels: Partner: Atwix, QA Passed, UA Contribution Day, partners-contribution

#2171 2169: Implement reservations CLI for incomplete orders
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistenciesForIncompleteOrders.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersInNotFinalState.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersWithMissingInitialReservations.php
  app/code/Magento/InventoryReservationCli/Test/Integration/Model/GetListMissingReservationsForIncompleteOrdersTest.php
  app/code/Magento/InventoryReservationCli/Test/Integration/_fixtures/create_incomplete_order_with_reservation.php
  app/code/Magento/InventoryReservationCli/etc/di.xml
Labels: Partner: TechDivision, QA Passed, UA Contribution Day, partners-contribution

#2049 MSI-2043: disabled source selection when disabled manage stock
  app/code/Magento/InventoryShippingAdminUi/Block/Adminhtml/Order/View/ShipButton.php
  app/code/Magento/InventoryShippingAdminUi/Model/IsOrderSourceManageable.php
  app/code/Magento/InventoryShippingAdminUi/Observer/NewShipmentLoadBefore.php
  app/code/Magento/InventoryShippingAdminUi/Plugin/Sales/Block/Shipment/BackButtonUrlOnNewShipmentPagePlugin.php
Labels: Partner: Atwix, QA Passed, UA Contribution Day, partners-contribution

#2176 [store pickup] code improvement
  app/code/Magento/InventoryInStorePickup/Model/Order/IsFulfillable.php
  app/code/Magento/InventoryInStorePickupAdminUi/Block/Adminhtml/Order/View/ReadyForPickup.php
  app/code/Magento/InventoryInStorePickupAdminUi/Controller/Adminhtml/Order/NotifyPickup.php
  app/code/Magento/InventoryInStorePickupAdminUi/Model/IsDisplayReadyForPickupButton.php
Labels: Store Pickup, UA Contribution Day

#2187 [store pickup] code improvement
  app/code/Magento/InventoryInStorePickupAdminUi/Controller/Adminhtml/Order/NotifyPickup.php
  app/code/Magento/InventoryInStorePickupAdminUi/Ui/Component/Listing/Column/IsPickupLocationActive.php
Labels: Store Pickup

#2179 MSI-1947: Source items deduction during Credit memo creation for unshipped order items
  app/code/Magento/InventorySales/Model/ReturnProcessor/DeductSourceItemQuantityOnRefund.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/GetSourceDeductionRequestFromSourceSelection.php
  app/code/Magento/InventorySales/Model/ReturnProcessor/GetSourceSelectionResultFromCreditMemoItems.php
  app/code/Magento/InventorySales/Observer/SalesInventory/DeductSourceItemQuantityOnRefundObserver.php
  app/code/Magento/InventorySales/composer.json
  app/code/Magento/InventorySales/etc/events.xml
Labels: Award: special achievement, Community Insider: Elogic, MSI 1.1.2 Release, QA Passed, UA Contribution Day, community-insider-contribution

#2056 Improve performance product save operation
  app/code/Magento/InventoryCatalog/Model/BulkInventoryTransfer.php
  app/code/Magento/InventoryCatalog/Model/BulkSourceUnassign.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkInventoryTransfer.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/BulkSourceUnassign.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/SetDataToLegacyStockItem.php
  app/code/Magento/InventoryCatalog/Model/ResourceModel/TransferInventoryPartially.php
  app/code/Magento/InventoryCatalog/Model/SourceItemsSaveSynchronization/SetDataToLegacyCatalogInventory.php
  app/code/Magento/InventoryCatalog/Model/UpdateSourceItemBasedOnLegacyStockItem.php
  app/code/Magento/InventoryCatalog/Test/Integration/SetDataToLegacyStockStatusAtSourceItemsSaveTest.php
  app/code/Magento/InventoryCatalog/etc/di.xml
  app/code/Magento/InventoryLegacySynchronization/LICENSE.txt
  app/code/Magento/InventoryLegacySynchronization/LICENSE_AFL.txt
  app/code/Magento/InventoryLegacySynchronization/Model/AsyncConsumer.php
  app/code/Magento/InventoryLegacySynchronization/Model/GetDefaultSourceItemsBySkus.php
  app/code/Magento/InventoryLegacySynchronization/Model/GetLegacyStockItemsByProductIds.php
  app/code/Magento/InventoryLegacySynchronization/Model/IsAsyncLegacyAlignment.php
  app/code/Magento/InventoryLegacySynchronization/Model/ResourceModel/SetZeroQuantityToLegacyStockItems.php
  app/code/Magento/InventoryLegacySynchronization/Model/ResourceModel/UpdateLegacyStockItemsData.php
  app/code/Magento/InventoryLegacySynchronization/Model/ResourceModel/UpdateSourceItemsData.php
  app/code/Magento/InventoryLegacySynchronization/Model/Synchronize.php
  app/code/Magento/InventoryLegacySynchronization/Model/SynchronizeInventoryData.php
  app/code/Magento/InventoryLegacySynchronization/Model/ToLegacy/SetDataToLegacyInventory.php
  app/code/Magento/InventoryLegacySynchronization/Model/ToMsi/SetDataToSourceItem.php
  app/code/Magento/InventoryLegacySynchronization/Plugin/SetDataToLegacyCatalogInventoryAtBulkTransfer.php
  app/code/Magento/InventoryLegacySynchronization/Plugin/SetDataToLegacyCatalogInventoryAtSourceItemsSavePlugin.php
  app/code/Magento/InventoryLegacySynchronization/Plugin/SetDataToLegacyCatalogInventoryAtTransferInventoryPartial.php
  app/code/Magento/InventoryLegacySynchronization/Plugin/SetToZeroLegacyCatalogInventoryAtSourceItemsDeletePlugin.php
  app/code/Magento/InventoryLegacySynchronization/Plugin/SetZeroQuantityToLegacyAtBulkUnassign.php
  app/code/Magento/InventoryLegacySynchronization/Plugin/UpdateSourceItemAtLegacyQtyCounterPlugin.php
  app/code/Magento/InventoryLegacySynchronization/Plugin/UpdateSourceItemAtLegacyStockItemSavePlugin.php
  app/code/Magento/InventoryLegacySynchronization/README.md
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/SetDataToLegacyCatalogInventoryAtBulkTransferTest.php
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/SetDataToLegacyStockItemAtSourceItemsSaveTest.php
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/SetDataToLegacyStockStatusAtSourceItemsSaveTest.php
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/SetOutOfStockToLegacyStockStatusAtSourceItemsDeleteTest.php
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/SetZeroToLegacyAtBulkUnassignTest.php
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/SetZeroToLegacyStockItemAtSourceItemsDeleteTest.php
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/UpdateDefaultSourceItemAtLegacyStockItemSaveTest.php
  app/code/Magento/InventoryLegacySynchronization/Test/Integration/UpdateDefaultSourceItemAtProductSaveTest.php
  app/code/Magento/InventoryLegacySynchronization/composer.json
  app/code/Magento/InventoryLegacySynchronization/etc/communication.xml
  app/code/Magento/InventoryLegacySynchronization/etc/config.xml
  app/code/Magento/InventoryLegacySynchronization/etc/di.xml
  app/code/Magento/InventoryLegacySynchronization/etc/module.xml
  app/code/Magento/InventoryLegacySynchronization/etc/queue_consumer.xml
  app/code/Magento/InventoryLegacySynchronization/etc/queue_publisher.xml
  app/code/Magento/InventoryLegacySynchronization/etc/queue_topology.xml
  app/code/Magento/InventoryLegacySynchronization/registration.php
  app/code/Magento/InventoryLegacySynchronizationAdminUi/LICENSE.txt
  app/code/Magento/InventoryLegacySynchronizationAdminUi/LICENSE_AFL.txt
  app/code/Magento/InventoryLegacySynchronizationAdminUi/README.md
  app/code/Magento/InventoryLegacySynchronizationAdminUi/composer.json
  app/code/Magento/InventoryLegacySynchronizationAdminUi/etc/adminhtml/system.xml
  app/code/Magento/InventoryLegacySynchronizationAdminUi/etc/module.xml
  app/code/Magento/InventoryLegacySynchronizationAdminUi/registration.php
  composer.json
  composer.lock
Labels: MSI 1.1.2 Release, MageSpecialist + BitBull CD, Partner: MageSpecialist, Performance, QA Passed, partners-contribution

#2186 Update MFTF tests according Manual HIP-TEST
  app/code/Magento/InventoryAdminUi/Test/Mftf/Data/MsiProductData.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnCustomStockFromHomepageTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnDefaultStockFromHomepageTest.xml
Labels: MFTF (Functional Test Coverage)

#2184 2170 reservation cli compensation
  app/code/Magento/InventoryReservationCli/Command/CreateCompensations.php
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistencies.php
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistenciesForIncompleteOrders.php
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistenciesInCompletedOrders.php
  app/code/Magento/InventoryReservationCli/Model/GetCompleteOrderStatusList.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersInFinalState.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersWithMissingInitialReservations.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersWithNotCompensatedReservations.php
  app/code/Magento/InventoryReservationCli/Model/GetSaleableQuantityCompensations.php
  app/code/Magento/InventoryReservationCli/Model/GetSaleableQuantityInconsistencies.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/AddCompletedOrdersToForUnresolvedReservations.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/AddExistingReservations.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/AddExpectedReservations.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/Collector.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/FilterCompleteOrders.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/FilterExistingOrders.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/FilterIncompleteOrders.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/FilterManagedStockProducts.php
  app/code/Magento/InventoryReservationCli/Model/SaleableQuantityInconsistency/FilterUnresolvedReservations.php
  app/code/Magento/InventoryReservationCli/Test/Integration/Model/GetListMissingReservationsForIncompleteOrdersTest.php
  app/code/Magento/InventoryReservationCli/Test/Integration/Model/GetListReservationsTotOrdersTest.php
  app/code/Magento/InventoryReservationCli/Test/Integration/Model/GetSaleableQuantityInconsistenciesTest.php
  app/code/Magento/InventoryReservationCli/Test/Integration/_fixtures/create_incomplete_order_without_reservation.php
  app/code/Magento/InventoryReservationCli/composer.json
  app/code/Magento/InventoryReservationCli/etc/di.xml
Labels: Award: advanced, MSI 1.1.2 Release, Partner: TechDivision, QA Passed, partners-contribution

#2194 MFTF test fixes
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCanSetOnlyXLeftTresholdForVirtualProductWithDefaultSourceTest.xml
  app/code/Magento/Inventory/Test/Mftf/Test/AdminCreateVirtualProductWithDefaultSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateDownloadableProductWithDefaultSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceForDifferentTypeOfProductsTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminUserSetStatusForEachSourceItemTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnDefaultStockFromHomepageTest.xml
Labels: MFTF (Functional Test Coverage)

#2191 MFTF - Credit Memo created with full refund with Simple product on Default stock after full invoice and partial shipment
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedWithFullRefundWithSimpleProductOnDefaultStockAfterFullInvoiceAndPartialShipment.xml
Labels: MFTF (Functional Test Coverage)

#2181 Msi 2055- Customer order Simple product and Free Shipping
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/AdminGoToProductGridFilterResultsByInputActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminUserApplyOnlyXLeftThresholdForSimpleProductOnDefaultSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/LoggedInCustomerCreatedOrderWithSimpleProductFromHomepageWithFreeShippingMethod.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/LoggedInCustomerCreatedOrderWithSimpleProductOnTestStockFromHomepageTest.xml
Labels: MFTF (Functional Test Coverage)

#2090 MSI#1990 - Improve performance of Sources sorting in SSA
  app/code/Magento/InventorySourceSelectionApi/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php
  app/code/Magento/InventorySourceSelectionApi/Model/GetInStockSourceItemsBySkusAndSortedSource.php
  app/code/Magento/InventorySourceSelectionApi/Test/Integration/GetDefaultSortedSourcesResultTest.php
  app/code/Magento/InventorySourceSelectionApi/Test/Integration/GetSourceItemsBySkusAndSortedSourceTest.php
  app/code/Magento/InventorySourceSelectionApi/etc/di.xml
Labels: MSI 1.1.2 Release, Partner: MageSpecialist, Performance, QA Passed, kharkivcd19, partners-contribution

#2197 MSI-1527
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedWithPartialRefundForOrderWithSimpleProductOnDefaultStockAfterFullInvoiceInAdminTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminUserApplyOnlyXLeftThresholdForSimpleProductOnDefaultSourceTest.xml
Labels: MFTF (Functional Test Coverage)

#2199 MSI-2170 Reservation CLI / Improve compensation create command
  app/code/Magento/InventoryReservationCli/Command/CreateCompensations.php
  app/code/Magento/InventoryReservationCli/Command/Input/GetCommandlineStandardInput.php
  app/code/Magento/InventoryReservationCli/Command/Input/GetReservationFromCompensationArgument.php
  app/code/Magento/InventoryReservationCli/Command/ShowInconsistencies.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersInFinalState.php
  app/code/Magento/InventoryReservationCli/Model/GetOrdersInNotFinalState.php
  app/code/Magento/InventoryReservationCli/Model/GetSalableQuantityInconsistencies.php
  app/code/Magento/InventoryReservationCli/Model/GetSaleableQuantityCompensations.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/AddCompletedOrdersToForUnresolvedReservations.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/AddExistingReservations.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/AddExpectedReservations.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/Collector.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterCompleteOrders.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterExistingOrders.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterIncompleteOrders.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterManagedStockProducts.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/FilterUnresolvedReservations.php
  app/code/Magento/InventoryReservationCli/Test/Integration/Model/GetSalableQuantityInconsistenciesTest.php
  app/code/Magento/InventoryReservationCli/etc/di.xml
Labels: MSI 1.1.2 Release, Partner: TechDivision, partners-contribution

#2067 MSI-2062: Inventory Export Stock
  app/code/Magento/InventoryExportStock/LICENSE.txt
  app/code/Magento/InventoryExportStock/LICENSE_AFL.txt
  app/code/Magento/InventoryExportStock/Model/ExportStockIndexData.php
  app/code/Magento/InventoryExportStock/Model/ExportStockSalableQty.php
  app/code/Magento/InventoryExportStock/Model/ExportStockSalableQtySearchResult.php
  app/code/Magento/InventoryExportStock/Model/GetQtyForNotManageStock.php
  app/code/Magento/InventoryExportStock/Model/GetStockItemConfiguration.php
  app/code/Magento/InventoryExportStock/Model/PreciseExportStockProcessor.php
  app/code/Magento/InventoryExportStock/Model/ProductStockIndexData.php
  app/code/Magento/InventoryExportStock/Model/ProductStockIndexDataMapper.php
  app/code/Magento/InventoryExportStock/Model/ResourceModel/ManageStockCondition.php
  app/code/Magento/InventoryExportStock/Model/ResourceModel/StockIndexDumpProcessor.php
  app/code/Magento/InventoryExportStock/README.md
  app/code/Magento/InventoryExportStock/composer.json
  app/code/Magento/InventoryExportStock/etc/di.xml
  app/code/Magento/InventoryExportStock/etc/module.xml
  app/code/Magento/InventoryExportStock/registration.php
  app/code/Magento/InventoryExportStockApi/Api/Data/ExportStockSalableQtySearchResultInterface.php
  app/code/Magento/InventoryExportStockApi/Api/Data/ProductStockIndexDataInterface.php
  app/code/Magento/InventoryExportStockApi/Api/ExportStockIndexDataInterface.php
  app/code/Magento/InventoryExportStockApi/Api/ExportStockSalableQtyInterface.php
  app/code/Magento/InventoryExportStockApi/LICENSE.txt
  app/code/Magento/InventoryExportStockApi/LICENSE_AFL.txt
  app/code/Magento/InventoryExportStockApi/README.md
  app/code/Magento/InventoryExportStockApi/composer.json
  app/code/Magento/InventoryExportStockApi/etc/module.xml
  app/code/Magento/InventoryExportStockApi/etc/webapi.xml
  app/code/Magento/InventoryExportStockApi/registration.php
  app/code/Magento/InventorySales/Model/ResourceModel/GetWebsiteIdByWebsiteCode.php
  composer.json
  composer.lock
Labels: Inventory Import/Export, MSI 1.1.2 Release, Partner: TechDivision, QA Passed, UA Contribution Day, partners-contribution

#2206 Static tests stabilization
  app/code/Magento/InventoryCatalogApi/Api/BulkPartialInventoryTransferInterface.php
  app/code/Magento/InventoryCatalogApi/Api/Data/PartialInventoryTransferItemInterface.php
  app/code/Magento/InventoryCatalogApi/Model/PartialInventoryTransferValidatorInterface.php
  app/code/Magento/InventoryReservationCli/etc/di.xml
Labels: MSI 1.1.2 Release

#2205 MSI-1947:Source items deduction during Credit memo creation for unshipped order items
  app/code/Magento/InventorySales/Observer/SalesInventory/DeductSourceItemQuantityOnRefundObserver.php
Labels: Community Insider: Elogic, MSI 1.1.2 Release, community-insider-contribution

#2202 MSI-2156 Adjust prs #2127, #2201.
  app/code/Magento/InventoryApi/Test/_files/source_items_out_of_stock.php
  app/code/Magento/InventoryApi/Test/_files/source_items_out_of_stock_rollback.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/set_product_configurable_zero_qty.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsAnySourceItemInStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsAnySourceItemInStockCondition.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/IsAnySourceItemInStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/ManageStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsAnySourceItemInStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/ManageStockConditionTest.php
  app/code/Magento/InventorySales/etc/di.xml
Labels: MSI 1.1.2 Release, Partner: ISM eCompany, partners-contribution

#2201 Msi 2172 adjustments to Product status is in stock on storefront even it is out of stock in all sources 2156
  app/code/Magento/InventoryApi/Test/_files/source_items_out_of_stock.php
  app/code/Magento/InventoryBundleProduct/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventoryBundleProduct/Test/_files/source_items_for_bundle_options_on_default_source.php
  app/code/Magento/InventoryBundleProduct/Test/_files/source_items_for_bundle_options_on_default_source_rollback.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/set_product_configurable_zero_qty.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsAnySourceItemInStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsAnySourceItemInStockCondition.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/IsAnySourceItemInStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/ManageStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/MinQtyConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsAnySourceItemInStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/ManageStockConditionTest.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySales/i18n/en_US.csv
Labels: MSI 1.1.2 Release, Partner: Atwix, partners-contribution

#2173 MSI-2126 Immutable DTO for Pickup Location.
  app/code/Magento/InventoryInStorePickup/Model/PickupLocation.php
  app/code/Magento/InventoryInStorePickup/Model/PickupLocation/Mapper.php
  app/code/Magento/InventoryInStorePickup/Model/PickupLocation/Mapper/CreateFromSource.php
  app/code/Magento/InventoryInStorePickup/Test/Integration/PickupLocation/MapperTest.php
  app/code/Magento/InventoryInStorePickup/etc/di.xml
  app/code/Magento/InventoryInStorePickup/etc/frontend/di.xml
  app/code/Magento/InventoryInStorePickupApi/Api/Data/PickupLocationInterface.php
Labels: Partner: ISM eCompany, Store Pickup, UA Contribution Day, partners-contribution

#2172 Product status is in stock on storefront even it is out of stock in all sources 2156
  app/code/Magento/InventoryBundleProduct/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  app/code/Magento/InventoryBundleProduct/Test/_files/source_items_for_bundle_options_on_default_source.php
  app/code/Magento/InventoryBundleProduct/Test/_files/source_items_for_bundle_options_on_default_source_rollback.php
  app/code/Magento/InventoryCatalog/Plugin/InventoryApi/SetToZeroLegacyCatalogInventoryAtSourceItemsDeletePlugin.php
  app/code/Magento/InventoryConfigurableProduct/Test/Integration/Order/PlaceOrderOnNotDefaultStockTest.php
  app/code/Magento/InventoryConfigurableProduct/Test/_files/set_product_configurable_zero_qty.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/IsAnySourceItemInStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableForRequestedQtyCondition/IsAnySourceItemInStockCondition.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalable/IsAnySourceItemInStockConditionTest.php
  app/code/Magento/InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsAnySourceItemInStockConditionTest.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySales/i18n/en_US.csv
Labels: MSI 1.1.2 Release, Partner: ISM eCompany, UA Contribution Day, partners-contribution
