Repository magento/inventory, pull requests merged in 2019-08, with the labels that each got.

#2450 MFTF Configurable product automation.
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationConfigurableProductSoldOutCustomStocks.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminConfigurableProductCustomStockMainWebsitePriceVerification.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateConfigurableProductTextSwatchAttributeCustomStockMainWebsite.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateConfigurableProductVisualSwatchAttributeCustomStockCustomWebsite.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateConfigurableProductWithSwatchAttributeDefaultStocks.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateConfigurableProductWithSwatchAttributeMultipleStocks.xml
  app/code/Magento/InventoryConfigurableProductAdminUi/Test/Mftf/Section/AdminConfigurableProductAssignSourcesSection.xml
Labels: MFTF (Functional Test Coverage)

#2458 Catalog Price Rule With Additional Stock automation.
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/CatalogPriceRuleBundleProductAdditionalStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/CatalogPriceRuleConfigurableProductAdditionalStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/CatalogPriceRuleDownloadableProductAdditionalStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/CatalogPriceRuleGroupedProductAdditionalStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/CatalogPriceRuleSimpleProductAdditionalStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/CatalogPriceRuleVirtualProductAdditionalStockTest.xml
Labels: MFTF (Functional Test Coverage)

#2460 Orders cancellation with virtual product after partial invoice
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCancelOrderWithVirtualProductCustomStockAfterPartialInvoiceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCancelOrderWithVirtualProductDefaultStockAfterPartialInvoiceTest.xml
Labels: MFTF (Functional Test Coverage), Progress: review

#2455 Increase performance by removing unnecessary sql query.
  app/code/Magento/InventoryConfiguration/Model/GetLegacyStockItem.php
Labels: Progress: approved

#2428 Store pickup remove abandoned module
  app/code/Magento/InventoryInStorePickupOrderExtension/LICENSE.txt
  app/code/Magento/InventoryInStorePickupOrderExtension/LICENSE_AFL.txt
  app/code/Magento/InventoryInStorePickupOrderExtension/Model/OrderRepository.php
  app/code/Magento/InventoryInStorePickupOrderExtension/README.md
  app/code/Magento/InventoryInStorePickupOrderExtension/composer.json
  app/code/Magento/InventoryInStorePickupOrderExtension/etc/di.xml
  app/code/Magento/InventoryInStorePickupOrderExtension/etc/module.xml
  app/code/Magento/InventoryInStorePickupOrderExtension/registration.php
  composer.json
  composer.lock
Labels: Partner: ISM eCompany, Progress: review, Store Pickup, partners-contribution

#2468 Remove validation from fax
  app/code/Magento/InventoryAdminUi/view/adminhtml/ui_component/inventory_source_form.xml
  app/code/Magento/InventoryAdminUi/view/adminhtml/ui_component/inventory_source_listing.xml
Labels: QA Passed

#2467 MSI-2463: Stock assign sources grid auto selects all sources selecting all but the default sources.
  app/code/Magento/InventoryAdminUi/Ui/DataProvider/SourceDataProvider.php
Labels: QA Passed, Regression 1.1.3

#2465 Disable mass action in Manage Sources grid request failure fix.
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/MassDisable.php
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/MassEnable.php
Labels: QA Passed, Regression 1.1.3

#2478 Category page and layered navigation for product on custom stock with Elasticsearch 6
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationCustomStockTest.xml
Labels: MFTF (Functional Test Coverage), Progress: approved, Regression 1.1.3

#2485 MSI-2479: Configurable Product SKU not available in B2B Quick Order option.
  app/code/Magento/InventoryAdvancedCheckout/Plugin/Model/IsProductInStock/ProductInStockPlugin.php
  app/code/Magento/InventoryAdvancedCheckout/composer.json
Labels: QA Passed

#2497 Filter out of stock products from search even if Elasticsearch is disabled
  app/code/Magento/InventoryElasticsearch/Plugin/CatalogSearch/Model/Indexer/Fulltext/Action/DataProvider/StockedProductFilterByInventoryStock.php
  app/code/Magento/InventoryElasticsearch/composer.json
Labels: Progress: review, Regression 1.1.3

#2419 EPAM-PR-66
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Form/Modifier/Quantity.php
Labels: Progress: approved

#2502 1.1.3 Release Regression Bug fixes
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/MassDisable.php
  app/code/Magento/InventoryAdminUi/Controller/Adminhtml/Source/MassEnable.php
  app/code/Magento/InventoryAdminUi/Test/Integration/Controller/Adminhtml/Source/SaveTest.php
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/DisableAllSourcesActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/EnableAllSourcesActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/ActionGroup/VerifySourceStatusActionGroup.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Section/AdminManageSourcesGridSection.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminAddSimpleProductToConfigurableProductCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminAssignMultipleSourcesToAdditionalStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminAssignSourceToProductTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminMassDisableMassEnableSourcesTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminSelectDeselectManipulationsInManageSourceGridTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Ui/DataProvider/SourceDataProvider.php
  app/code/Magento/InventoryAdminUi/view/adminhtml/ui_component/inventory_source_form.xml
  app/code/Magento/InventoryAdminUi/view/adminhtml/ui_component/inventory_source_listing.xml
  app/code/Magento/InventoryAdvancedCheckout/Test/Mftf/Test/CreateOrderWithConfigurableProductCustomStockCustomWebsiteBySkuFromCustomerAccountTest.xml
  app/code/Magento/InventoryConfiguration/Model/GetLegacyStockItem.php
  app/code/Magento/InventoryRequisitionList/Test/Mftf/Test/OrderWithMultipleProductsAdditionalStock.xml
  app/code/Magento/InventoryReservationCli/Command/CreateCompensations.php
  app/code/Magento/InventoryReservationCli/Model/SalableQuantityInconsistency/AddExpectedReservations.php
Labels: Regression 1.1.3

#2474 2366: Remove excess fixtures from In-Store Pickup module
  app/code/Magento/InventoryInStorePickup/Test/Integration/SourceSelection/GetSourceItemQtyAvailableServiceTest.php
  app/code/Magento/InventoryInStorePickup/Test/_files/mark_sources_as_pickup_location.php
  app/code/Magento/InventoryInStorePickup/Test/_files/set_orders_pickup_location.php
Labels: Partner: ISM eCompany, Progress: approved, Store Pickup, partners-contribution
