Repository magento/inventory, pull requests merged in 2019-02, with the labels that each got.

#2014 MSI-2013: Change source quantity visualization on product page grid
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreatePartialShipmentForOrderWithConfigurableProductFromCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreatePartialShipmentForOrderWithSimpleProductFromCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreatePartialShipmentForOrderWithSimpleProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithConfigurableProductFromCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithSimpleProductFromCustomSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithSimpleProductInSingleStockModeTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminManualSelectingOfSourcesToDeductItemsInShipmentForOrderWithSimpleProductTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnCustomStockFromHomepageTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnDefaultStockFromHomepageTest.xml
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/template/product/grid/cell/source-items.html
  app/code/Magento/InventorySalesAdminUi/view/adminhtml/web/template/product/grid/cell/salable-quantity.html
Labels: Jenkins Builds

#2016 MSI-2015: Optimize product grid page load
  app/code/Magento/InventoryCatalogAdminUi/Ui/DataProvider/Product/Listing/Modifier/QuantityPerSource.php
  app/code/Magento/InventoryCatalogAdminUi/etc/adminhtml/di.xml
Labels: PAT Build

#2040 MSI-2039: Add strong tag to sources name on product grid page
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/template/product/grid/cell/source-items.html
Labels: In 2.3-develop

#2041 Release MSI 1.1.0
  app/code/Magento/InventoryCatalogAdminUi/view/adminhtml/web/template/product/grid/cell/source-items.html
Labels: 2.3.0-release
