Repository magento/inventory, pull requests merged in 2019-12, with the labels that each got.

#2741 MSI-2733: Improve performance of re-indexation after SourceItem saved.
  app/code/Magento/InventoryIndexer/Indexer/SourceItem/GetSourceItemIds.php
Labels: QA Passed

#2731 MSI-2730: Not able to re-assign main website to default stock.
  app/code/Magento/InventorySales/etc/adminhtml/di.xml
Labels: QA Passed

#2743 Increase MFTF test coverage.
  app/code/Magento/InventoryAdminUi/Test/Mftf/Section/AdminOrderFormItemsSection.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateOrderWithSimpleProductWithAllQuantityDefaultStockMainWebsiteTest.xml
Labels: Progress: approved

#2739 Order success message for Store pickup order should be distinct from normal message.
  InventoryInStorePickupFrontend/Block/Checkout/Onepage/Success/IsOrderStorePickup.php
  InventoryInStorePickupFrontend/composer.json
  InventoryInStorePickupFrontend/view/frontend/layout/checkout_onepage_success.xml
  InventoryInStorePickupFrontend/view/frontend/templates/success.phtml
Labels: Progress: review, QA Passed, Store Pickup

#2738 "Shipping" section in order summary should display selected source/store name for pickup
  InventoryInStorePickupFrontend/Block/Checkout/LayoutProcessor.php
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontSummaryShippingSectionWithSimpleProductCustomStockTest.xml
  InventoryInStorePickupFrontend/view/frontend/layout/checkout_index_index.xml
  InventoryInStorePickupFrontend/view/frontend/requirejs-config.js
  InventoryInStorePickupFrontend/view/frontend/web/js/view/shipping-information-ext.js
  InventoryInStorePickupFrontend/view/frontend/web/js/view/shipping-information/address-renderer/store-pickup-address.js
  InventoryInStorePickupFrontend/view/frontend/web/template/shipping-information.html
  InventoryInStorePickupFrontend/view/frontend/web/template/shipping-information/address-renderer/store-pickup-address.html
Labels: Progress: review, QA Passed, Store Pickup

#2748 Assign all generated websites to default stock
  app/code/Magento/InventorySetupFixtureGenerator/Plugin/Setup/Fixtures/StoresFixturePlugin.php
  app/code/Magento/InventorySetupFixtureGenerator/composer.json
  app/code/Magento/InventorySetupFixtureGenerator/etc/di.xml
Labels: Auto-Tests: Not Required, Progress: approved

#2734 Search request interfaces refactoring
  InventoryAdminUi/Test/Mftf/Test/OfflineDistanceBasedSelectionAlgorithmCustomStockTestTwoItemsDeduction.xml
  InventoryAdminUi/Test/Mftf/Test/OfflineDistanceBasedSelectionAlgorithmSimpleProductCustomStockTest.xml
  InventoryInStorePickup/Model/ResourceModel/Source/GetOrderedDistanceToSources.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveArea.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveFilters.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveMeta.php
  InventoryInStorePickup/Model/SearchRequest.php
  InventoryInStorePickup/Model/SearchRequest/Area.php
  InventoryInStorePickup/Model/SearchRequest/Area/GetDistanceToSources.php
  InventoryInStorePickup/Model/SearchRequest/Builder/AreaBuilder.php
  InventoryInStorePickup/Model/SearchRequest/Builder/FiltersBuilder.php
  InventoryInStorePickup/Model/SearchRequest/FilterSet.php
  InventoryInStorePickup/Model/SearchRequest/Filters.php
  InventoryInStorePickup/Model/SearchRequestBuilder.php
  InventoryInStorePickup/Model/SearchResult/Strategy/DistanceBased.php
  InventoryInStorePickup/Test/Integration/GetPickupLocations/CombinedTest.php
  InventoryInStorePickup/Test/Integration/GetPickupLocations/DistanceFilterOfflineTest.php
  InventoryInStorePickup/Test/Integration/GetPickupLocations/FiltersTest.php
  InventoryInStorePickup/Test/Integration/SearchRequestBuilderTest.php
  InventoryInStorePickup/etc/di.xml
  InventoryInStorePickupApi/Api/Data/SearchRequest/AreaInterface.php
  InventoryInStorePickupApi/Api/Data/SearchRequest/FiltersInterface.php
  InventoryInStorePickupApi/Api/Data/SearchRequestInterface.php
  InventoryInStorePickupApi/Api/Data/SearchResultInterface.php
  InventoryInStorePickupApi/Model/SearchRequestBuilderInterface.php
  InventoryInStorePickupApi/Test/Api/GetPickupLocationsTest.php
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-pickup.js
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-selector.js
  InventoryInStorePickupGraphQl/Model/Resolver/PickupLocations/SearchRequest/Distance.php
  InventoryInStorePickupGraphQl/etc/schema.graphqls
Labels: Progress: approved, Store Pickup

#2750 Unskip ElasticSearchLayeredNavigationCustomStockTest
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationCustomStockTest.xml
Labels: Progress: approved

#2752 Remove caching for GetAssignedSalesChannelsForStockInterface
  app/code/Magento/InventorySales/Model/GetAssignedSalesChannelsForStockCache.php
  app/code/Magento/InventorySales/Model/GetStockBySalesChannelCache.php
  app/code/Magento/InventorySales/etc/di.xml
  app/code/Magento/InventorySetupFixtureGenerator/Plugin/Setup/Fixtures/StoresFixturePlugin.php
  app/code/Magento/InventorySetupFixtureGenerator/composer.json
  app/code/Magento/InventorySetupFixtureGenerator/etc/di.xml
  dev/tests/integration/_files/Magento/TestModuleInventoryStateCache/etc/di.xml
Labels: Progress: review, QA Passed

#2736 Change order status to “Complete” after notifying. Make possible to notify again.
  InventoryInStorePickupAdminUi/Test/Mftf/ActionGroup/AdminAssertOrderStatusActionGroup.xml
  InventoryInStorePickupAdminUi/Test/Mftf/ActionGroup/AdminAssertShipmentWithStorePickupActionGroup.xml
  InventoryInStorePickupAdminUi/Test/Mftf/Test/AdminNotifyOrderIsReadyForPickupTwiceWithSimpleProductCustomStockTest.xml
  InventoryInStorePickupApi/Api/Data/SearchRequestInterface.php
  InventoryInStorePickupSales/Model/NotifyOrdersAreReadyForPickup.php
  InventoryInStorePickupSales/Model/Order/AddCommentToOrder.php
  InventoryInStorePickupSales/Model/Order/AddStorePickupAttributesToOrder.php
  InventoryInStorePickupSales/Model/Order/CreateShippingDocument.php
  InventoryInStorePickupSalesAdminUi/Block/Adminhtml/Order/View/ReadyForPickup.php
  InventoryInStorePickupSalesAdminUi/Controller/Adminhtml/Order/NotifyPickup.php
  InventoryInStorePickupSalesAdminUi/Model/IsRenderReadyForPickupButton.php
Labels: Progress: review, QA Passed, Store Pickup

#2755 Illiminate using of array_merge.
  app/code/Magento/Inventory/Model/ResourceModel/SourceItem/SaveMultiple.php
Labels: Auto-Tests: Not Required, Partner: Comwrap, Progress: review, partners-contribution

#2386 MC-17524: Child product is not addable to Cart from PLP if it does not have default source assigned
  app/code/Magento/InventoryApi/Test/_files/change_stock_for_base_website.php
  app/code/Magento/InventoryApi/Test/_files/change_stock_for_base_website_rollback.php
  app/code/Magento/InventoryApi/Test/_files/stock_with_source_link.php
  app/code/Magento/InventoryApi/Test/_files/stock_with_source_link_rollback.php
  app/code/Magento/InventoryGroupedProduct/Test/Integration/Order/PlaceOrderOnCustomStockTest.php
Labels: Progress: approved

#2740 MC-29177: Users can buy more products than available in stock
  app/code/Magento/InventoryCatalog/Model/ResourceModel/SetDataToLegacyStockStatus.php
  app/code/Magento/InventoryCatalog/Model/SourceItemsSaveSynchronization/SetDataToLegacyCatalogInventory.php
  app/code/Magento/InventoryCatalog/Test/Integration/SetDataToLegacyStockStatusAtSourceItemsSaveTest.php
Labels: Auto-Tests: Covered, Progress: approved, QA Passed

#2746 MSI-2744: Placing an Order MSI makes a check for IsProductSalableForRequestedQty 2 times for each product.
  app/code/Magento/InventorySales/etc/events.xml
Labels: Auto-Tests: Not Required, QA Passed

#2595 MSI-2558: Introduce reusable checker classes
  app/code/Magento/Inventory/Model/Source/Validator/CodeValidator.php
  app/code/Magento/Inventory/Model/Source/Validator/CountryValidator.php
  app/code/Magento/Inventory/Model/Source/Validator/NameValidator.php
  app/code/Magento/Inventory/Model/Source/Validator/PostcodeValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/QuantityValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/SkuValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/SourceCodeValidator.php
  app/code/Magento/Inventory/Model/SourceItem/Validator/StatusValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/SourceCodeValidator.php
  app/code/Magento/Inventory/Model/StockSourceLink/Validator/StockIdValidator.php
  app/code/Magento/Inventory/Model/Validators/IsNumericValue.php
  app/code/Magento/Inventory/Model/Validators/NoSpecialCharsInString.php
  app/code/Magento/Inventory/Model/Validators/NoWhitespaceInString.php
  app/code/Magento/Inventory/Model/Validators/NotAnEmptyString.php
  app/code/Magento/Inventory/Test/Integration/Source/Validator/CodeValidatorTest.php
  app/code/Magento/Inventory/Test/Integration/Source/Validator/NameValidatorTest.php
  app/code/Magento/Inventory/Test/Unit/Model/Source/Validator/CodeValidatorTest.php
  app/code/Magento/Inventory/Test/Unit/Model/Source/Validator/NameValidatorTest.php
Labels: Partner: TechDivision, Progress: approved, partners-contribution

#2753 Unskip MFTF tests.
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminApplyUseDecimalsOnProductPageSimpleProductDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminBackordersEnabledOnProductPageAndAppliedToSimpleProductOnDefaultSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminBundleProductDisabledManageStockOnProductPageDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminConfigurableProductDisabledManageStockOnProductPageDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedWithPartialRefundForOrderWithSimpleProductOnDefaultStockAfterFullInvoiceInAdminTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceForDifferentTypeOfProductsWithOutOfStockStatusOnSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceForSimpleProductsWithOutOfStockStatusOnSourceTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceTransferringNotifyQuantityForDifferentTypesOfProductsTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceTransferringNotifyQuantityForSimpleProductsTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/GuestCustomerCreateOrderWithSimpleProductOnCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/ReorderButtonBundleProductDefaultStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontAdvancedSearchGroupedProductCustomStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontOrderCreatedWIthConfigurableProductWithDropDownAttributeTest.xml
Labels: Progress: approved

#2598 MSI-2281: Add Sources column to the Sales Order Grid in Magento Admin panel
  app/code/Magento/InventoryShippingAdminUi/Model/ResourceModel/GetAllocatedSourcesForOrder.php
  app/code/Magento/InventoryShippingAdminUi/Ui/Component/Listing/Column/AllocatedSources.php
  app/code/Magento/InventoryShippingAdminUi/view/adminhtml/ui_component/sales_order_grid.xml
  app/code/Magento/InventoryShippingAdminUi/view/adminhtml/web/js/order/grid/cell/allocated-sources.js
  app/code/Magento/InventoryShippingAdminUi/view/adminhtml/web/template/order/grid/cell/allocated-sources-cell.html
Labels: Progress: approved, QA Passed
