Repository magento/inventory, pull requests merged in 2020-09, with the labels that each got.

#3170 [Support] Product salability status is not updated for default stock after order is placed until it is shipped
  InventoryAdminUi/Test/Mftf/Test/StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest.xml
  InventoryIndexer/Model/Queue/GetSalabilityDataForUpdate.php
  InventoryIndexer/Model/Queue/UpdateIndexSalabilityStatus.php
  InventoryIndexer/Model/Queue/UpdateIndexSalabilityStatus/IndexProcessor.php
  InventoryIndexer/Model/Queue/UpdateIndexSalabilityStatus/UpdateLegacyStock.php
  InventoryIndexer/Model/ResourceModel/UpdateLegacyStockStatus.php
  InventoryIndexer/Test/Unit/Model/Queue/GetSalabilityDataForUpdateTest.php
  InventoryIndexer/Test/Unit/Model/Queue/UpdateIndexSalabilityStatus/UpdateLegacyStockTest.php
  InventoryIndexer/Test/Unit/Model/Queue/UpdateIndexSalabilityStatusTest.php
  InventoryIndexer/Test/Unit/Model/ResourceModel/UpdateLegacyStockStatusTest.php
Labels: Progress: approved, QA Passed

#3171 Tests Broken isolation
  InventoryApi/Test/_files/products_rollback.php
  InventoryConfigurableProduct/Test/_files/product_configurable_rollback.php
  InventoryImportExport/Test/Integration/Model/Import/ProductTest.php
  InventoryImportExport/Test/Integration/Model/ProductImportExportBase.php
  InventoryInStorePickupSales/Test/Integration/SourceSelection/GetSourceItemQtyAvailableServiceTest.php
  InventorySalesApi/Test/_files/websites_with_stores_rollback.php
Labels: 2.4-develop: dep, Progress: review

#3137 MC-35399: Low Stock Product report contains Out Of Stock product
  InventoryAdminUi/Test/Mftf/Test/AdminLowStockReportForSimpleProductWithDefaultStockAndZeroQuantityTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminLowStockReportForSimpleProductWithStatusCheckAndDefaultStockTest.xml
  InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
Labels: Progress: review, QA Passed

#3139 MC-33760: Low Stock Report Export Error in Magento2.3.4
  InventoryAdminUi/Test/Mftf/Data/CatalogInventoryConfigData.xml
  InventoryAdminUi/Test/Mftf/Test/AdminLowStockReportForSimpleProductWithDefaultStockAndZeroQuantityTest.xml
  InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockCsv.php
  InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockExcel.php
  InventoryLowQuantityNotificationAdminUi/Test/Mftf/Section/LowStockProductGridSection.xml
  InventoryLowQuantityNotificationAdminUi/Test/Mftf/Test/AdminLowStockReportExportVerificationTest.xml
Labels: Progress: approved, QA Passed

#3191 [MTS | Pangolin] Update Chrome browser to version 85
  InventoryAdminUi/Test/Mftf/ActionGroup/StorefrontProductCartActionGroup.xml
  InventoryAdminUi/Test/Mftf/Section/StorfrontMiniCartSection.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenDownloadableProductIsSoldOutOnMultipleStockModeTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCacheValidationWhenDownloadableProductIsSoldOutOnSingleStockModeTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateInvoiceForVirtualProductInSingleStockModeTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedWithPartialRefundForOrderWithSimpleProductOnDefaultStockAfterFullInvoiceInAdminTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreditMemoCreatedWithPartialRefundWithSimpleProductOnDefaultStockAfterPartialInvoiceAndPartialShipmentTest.xml
  InventoryAdminUi/Test/Mftf/Test/StoreFrontQtyOfSimpleProductManagedViaMiniShoppingCartOnHomepageTest.xml
Labels: 2.4-develop: dep, Progress: approved, in progress

#3161 In store pickup intersection search graphql
  InventoryInStorePickupGraphQl/Model/Resolver/PickupLocations.php
  InventoryInStorePickupGraphQl/Model/Resolver/PickupLocations/SearchRequest.php
  InventoryInStorePickupGraphQl/Model/Resolver/PickupLocations/SearchRequestBuilder.php
  InventoryInStorePickupGraphQl/Model/Resolver/PickupLocations/SearchRequestBuilder/ExtensionProvider.php
  InventoryInStorePickupGraphQl/Test/GraphQl/PickupLocationsNegativeCasesTest.php
  InventoryInStorePickupGraphQl/Test/GraphQl/PickupLocationsPositiveCasesTest.php
  InventoryInStorePickupGraphQl/etc/graphql/di.xml
  InventoryInStorePickupGraphQl/etc/schema.graphqls
Labels: 1.2-develop, Award: category of expertise, Award: special achievement, Award: test coverage, Partner: Vaimo, Progress: approved, partners-contribution

#3151 Refactoring.
  InventoryBundleProduct/Plugin/InventorySales/IsBundleProductSalable.php
  InventoryBundleProduct/composer.json
  InventoryBundleProduct/etc/di.xml
  InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
  InventoryConfigurableProduct/Plugin/InventorySales/IsConfigurableProductSalable.php
  InventoryConfigurableProduct/composer.json
  InventoryConfigurableProduct/etc/di.xml
  InventorySales/Model/IsProductSalableCondition/IsProductSalableConditionChain.php
Labels: Award: advanced, Award: complex, Partner: Vaimo, Progress: review, partners-contribution
