Repository magento/inventory, pull requests merged in 2020-02, with the labels that each got.

#2771 MSI-2645: Search by city name fails for Store pickup selection.
  InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GoogleMap/GetGeoCodesForAddress.php
  InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GoogleMap/GetLatLngFromAddress.php
  InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GoogleMap/GetLatsLngsFromAddress.php
  InventoryDistanceBasedSourceSelection/Model/DistanceProvider/Offline/GetLatsLngsFromAddress.php
  InventoryDistanceBasedSourceSelection/Model/ResourceModel/GetGeoNamesDataByAddress.php
  InventoryDistanceBasedSourceSelection/etc/di.xml
  InventoryDistanceBasedSourceSelectionApi/Api/GetLatsLngsFromAddressInterface.php
  InventoryDistanceBasedSourceSelectionApi/Model/GetLatsLngsFromAddress.php
  InventoryDistanceBasedSourceSelectionApi/etc/di.xml
  InventoryDistanceBasedSourceSelectionApi/etc/webapi.xml
  InventoryInStorePickup/Model/ResourceModel/Source/GetOrderedDistanceToSources.php
  InventoryInStorePickup/Model/SearchRequest/Area/GetDistanceToSources.php
  InventoryProductAlert/Test/Integration/ProductAlertTest.php
Labels: Progress: review, QA Passed, Store Pickup

#2781 MSI-2436: Store Pickup AdminUI: Disable shipping address partially
  InventoryInStorePickupSalesAdminUi/Plugin/Sales/Block/Adminhtml/Order/Create/Shipping/Address/AdaptFormPlugin.php
  InventoryInStorePickupSalesAdminUi/Plugin/Sales/Model/AdminOrder/Create/AdaptSetShippingAddressPlugin.php
  InventoryInStorePickupSalesAdminUi/etc/adminhtml/di.xml
  InventoryInStorePickupSalesAdminUi/view/adminhtml/web/order/create/scripts-mixin.js
Labels: Progress: review, QA Passed, Store Pickup

#2815 Load default pickup locations list with empty search query
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-selector.js
Labels: Award: bug fix, Store Pickup

#2818 #1584 Fix UX Text - Max Actions Transfer Inventory to Source
  Inventory/i18n/en_US.csv
  InventoryCatalog/Model/BulkInventoryTransfer.php
  InventoryCatalogAdminUi/i18n/en_US.csv
  InventoryCatalogAdminUi/view/adminhtml/layout/inventorycatalog_inventory_bulktransfer.xml
  InventoryCatalogAdminUi/view/adminhtml/templates/inventory_transfer.phtml
  InventoryCatalogAdminUi/view/adminhtml/ui_component/product_listing.xml
Labels: Progress: approved

#2801 Fix stock indexer is executed twice after "products" import
  InventoryImportExport/etc/di.xml
Labels: Award: bug fix, Progress: approved, QA Passed

#2838 Mftf tests stabilization
  InventoryAdminUi/Test/Mftf/Data/MsiProductData.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontAdvancedSearchBundleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontAdvancedSearchConfigurableProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontAdvancedSearchDownloadableProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontAdvancedSearchSimpleProductCustomStockTest.xml
Labels: Progress: approved

#2820 HOTFIX: #26607 Fix failing CI due to Functional Tests
  InventoryAdminUi/Test/Mftf/ActionGroup/RegisterCustomOnStorefrontActionGroup.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderAllOptionQuantityConfigurableProductCustomStock.xml
Labels: Award: MFTF test coverage, Partner: Mediotype, Progress: review, partners-contribution

#2842 MC-31568: [Magento On-Premise] Inventory source item API not not work…
  InventoryIndexer/Indexer/IndexHandler.php
Labels: Award: bug fix, Progress: changes requested

#2835 MC-31469: [Magento On-Premise] Inventory source item API not not work…
  InventoryIndexer/Indexer/IndexHandler.php
Labels: Progress: review

#2844 MSI-2138: Disable fields in Mass action -> Update attributes -> Advanced inventory.
  InventoryCatalog/Model/ResourceModel/UpdateLegacyStockItems.php
  InventoryCatalog/Model/UpdateInventory.php
  InventoryCatalog/Model/UpdateInventory/InventoryData.php
  InventoryCatalog/Plugin/Catalog/Controller/Adminhtml/Product/Action/Attribute/Save/ProcessInventoryPlugin.php
  InventoryCatalog/etc/communication.xml
  InventoryCatalog/etc/di.xml
  InventoryCatalog/etc/queue.xml
  InventoryCatalog/etc/queue_consumer.xml
  InventoryCatalog/etc/queue_publisher.xml
  InventoryCatalog/etc/queue_topology.xml
  InventoryCatalogAdminUi/ViewModel/IsSingleSourceMode.php
  InventoryCatalogAdminUi/view/adminhtml/layout/catalog_product_action_attribute_edit.xml
  InventoryCatalogAdminUi/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml
  InventoryCatalogAdminUi/view/adminhtml/web/js/product/attribute/edit/inventory/toggle/toggle-editability-all.js
  InventoryCatalogAdminUi/view/adminhtml/web/js/product/attribute/edit/inventory/toggle/toggle-editability.js
Labels: Progress: approved, QA Passed

#2845 [TSG] MC-22129: MFTF TASK FOR MC-6080
  Inventory/Test/Mftf/Test/SkippedTest.xml
Labels: Progress: approved
