Repository magento/inventory, pull requests merged in 2020-06, with the labels that each got.

#3067 MSI-3066: Product not appears on category page when async Stock / Source indexer enabled.
  InventoryCache/Plugin/InventoryIndexer/Indexer/SourceItem/Strategy/Sync/CacheFlush.php
  InventoryCache/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/CacheFlush.php
  InventoryCache/composer.json
  InventoryCache/etc/di.xml
  InventoryCatalog/Plugin/InventoryIndexer/Indexer/SourceItem/Strategy/Sync/PriceIndexUpdater.php
  InventoryCatalog/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/PriceIndexUpdatePlugin.php
  InventoryCatalog/etc/di.xml
  InventoryIndexer/Model/ResourceModel/GetProductIdsByStockIds.php
  InventoryIndexer/etc/di.xml
Labels: 1.2.0-develop, Progress: approved, Regression bug

#3047 MQE-2113: fix errors reported by the annotation static check
  Inventory/Test/Mftf/Test/SkippedTest/EndToEndB2CGuestUserMysqlTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoPartialRefundPartialInvoicePartialShipmentBundleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateSimpleProductReassignSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminInvoiceCreatedForWholeOrderWithGroupedProductWithChildsProductOnNonDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminNotAbleCreateBundleProductShipTogetherCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminUserCreatedShipmentForWholeOrderWithSimpleProductFromTestSourceWithNumericSourceCodeTest.xml
  InventoryAdminUi/Test/Mftf/Test/LoggedInCustomerOrderedGroupedProductWithChildProductsAssignedToDefaultStockFromHomepageTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontReorderOfTheOrderWithBundleProductFromHomepageOnDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontSalableQuantityOnNonDefaultStockForGroupedProductAfterPlacingOrderCountedCorrectlyTest.xml
  InventoryAdminUi/Test/Mftf/Test/VerifyThatMessageOnlyZeroLeftNotAppearedOnSimpleProductPageOnFrontendTest.xml
  InventoryAdminUi/Test/Mftf/Test/VerifyThatMessageOnlyZeroLeftNotAppearedOnSimpleProductPageOnFrontendWithMainWebsiteAssignedAsSalesChannelTest.xml
  InventoryAdminUi/Test/Mftf/Test/VerifyThatMessageOnlyZeroLeftNotAppearedOnSimpleProductPageOnFrontendWithWebsiteAndNewStoreAndNewStoreViewTest.xml
  InventoryAdminUi/Test/Mftf/Test/VerifyThatMessageOnlyZeroLeftNotAppearedOnSimpleProductPageOnFrontendWithoutTestWebsiteAssignedAsSalesChannelTest.xml
  InventoryAdvancedCheckout/Test/Mftf/Test/AddBundleDynamicFromCustomStockBySkuFromCustomerAccountTest.xml
  InventoryAdvancedCheckout/Test/Mftf/Test/AddConfigurableFromCustomStockBySkuFromCustomerAccountTest.xml
  InventoryAdvancedCheckout/Test/Mftf/Test/AddSimpleFromCustomStockBySkuFromCustomerAccountTest.xml
  InventoryAdvancedCheckout/Test/Mftf/Test/AddSimpleOutOfStockProductBySkuFromCustomerAccountAdditionalStockTest.xml
  InventoryAdvancedCheckout/Test/Mftf/Test/CreateOrderWithConfigurableProductCustomStockCustomWebsiteBySkuFromCustomerAccountTest.xml
  InventoryRequisitionList/Test/Mftf/Test/StoreFrontQTYChangeCustomStockProductVariationOfConfigurableProductTest.xml
  InventoryRequisitionList/Test/Mftf/Test/StorefrontAddCustomStockProductWithFileToTheCartFromRequisitionListTest.xml
Labels: Progress: approved

#3057 Is product salable improvements
  InventoryAdminUi/Test/Mftf/Test/StorefrontCreateOrderAllQuantityConfigurableProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderAllOptionQuantityConfigurableProductCustomStockTest.xml
  InventoryCache/Plugin/InventoryIndexer/Queue/Reservation/UpdateSalabilityStatus/CacheFlush.php
  InventoryCache/composer.json
  InventoryCache/etc/di.xml
  InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
  InventoryIndexer/Model/IsProductSalable.php
  InventoryIndexer/Model/Queue/ReservationData.php
  InventoryIndexer/Model/Queue/UpdateIndexSalabilityStatus.php
  InventoryIndexer/Model/Queue/UpdateIndexSalabilityStatus/IndexProcessor.php
  InventoryIndexer/Model/ResourceModel/UpdateIsSalable.php
  InventoryIndexer/Plugin/InventorySales/EnqueueAfterPlaceReservationsForSalesEvent.php
  InventoryIndexer/etc/communication.xml
  InventoryIndexer/etc/di.xml
  InventoryIndexer/etc/frontend/di.xml
  InventoryIndexer/etc/graphql/di.xml
  InventoryIndexer/etc/queue_consumer.xml
  InventoryIndexer/etc/queue_publisher.xml
  InventoryIndexer/etc/queue_topology.xml
  InventoryReservations/etc/di.xml
  InventoryReservations/etc/frontend/di.xml
  InventoryReservations/etc/graphql/di.xml
  InventorySales/Model/IsProductSalableCondition/IsSalableWithReservationsCondition.php
  dev/tests/api-functional/_files/Magento/TestModuleInventoryStateCache/etc/frontend/di.xml
  dev/tests/integration/_files/Magento/TestModuleInventoryStateCache/Plugin/CatalogInventory/Model/StockRegistryProvider/GetNonCachedStockItemPlugin.php
  dev/tests/integration/_files/Magento/TestModuleInventoryStateCache/etc/frontend/di.xml
Labels: Award: advanced, Award: bug fix, Award: category of expertise, Award: complex, Award: special achievement, Partner: Vaimo, Progress: approved, partners-contribution

#3052 Store pickup storefront improvement
  InventoryInStorePickupFrontend/view/frontend/web/js/model/pickup-locations-service.js
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-selector.js
Labels: Partner: Vaimo, Progress: approved, Regression bug, partners-contribution

#3034 MSI-3022: Refactor tests to be able to execute them when Magento performance is dropped.
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateFullInvoiceForOrderWithDownloadableProductOnCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateFullInvoiceForOrderWithSimpleProductOnCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminUserCreateOrderWithSimpleProductOnTestStockFromCustomWebsiteTest.xml
  InventoryAdminUi/Test/Mftf/Test/ReorderButtonGroupedProductOnTestStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontReorderOfTheOrderWithBundleProductFromHomepageOnDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromHomepageTest.xml
Labels: 2.4.0-develop: :one:, Progress: approved

#3082 [TSG][2.3.6] MC-34987: MFTF tests causing high load on Jenkins agents in MTSv1 platform
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest.xml
  InventoryCatalog/Test/Mftf/Data/QueueConsumerData.xml
Labels: Progress: approved

#3081 Rename in store pickup to instore pickup
  InventoryInStorePickupAdminUi/Test/Mftf/ActionGroup/AdminSelectInStorePickupShippingMethodActionGroup.xml
  InventoryInStorePickupAdminUi/Test/Mftf/Data/CatalogInventoryConfigData.xml
  InventoryInStorePickupFrontend/Block/Checkout/LayoutProcessor.php
  InventoryInStorePickupFrontend/view/frontend/web/js/view/shipping-information-ext.js
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-pickup.js
  InventoryInStorePickupMultishipping/Test/Integration/Carrier/InStorePickupWithMultishippingTest.php
  InventoryInStorePickupSales/Test/Integration/Extension/OrderExtensionTest.php
  InventoryInStorePickupSales/Test/Integration/IsOrderReadyForPickupTest.php
  InventoryInStorePickupSales/Test/Integration/NotifyOrdersAreReadyForPickupTest.php
  InventoryInStorePickupSales/Test/Integration/SourceSelection/GetSourceItemQtyAvailableServiceTest.php
  InventoryInStorePickupSalesAdminUi/Plugin/Sales/Block/Adminhtml/Order/ProcessShipButtonPlugin.php
  InventoryInStorePickupSalesAdminUi/Test/Mftf/Section/AdminOrderFormPaymentSection.xml
  InventoryInStorePickupSalesAdminUi/view/adminhtml/web/order/create/scripts-mixin.js
  InventoryInStorePickupSalesAdminUi/view/adminhtml/web/order/create/trigger-shipping-method-update.js
  InventoryInStorePickupSalesApi/Test/GraphQl/PlaceOrderTest.php
  InventoryInStorePickupSalesApi/Test/_files/store_for_eu_website_store_carriers_conf.php
  InventoryInStorePickupSalesApi/Test/_files/store_for_eu_website_store_carriers_conf_rollback.php
  InventoryInStorePickupSalesApi/etc/acl.xml
  InventoryInStorePickupSalesApi/etc/config.xml
  InventoryInStorePickupSalesApi/etc/webapi.xml
  InventoryInStorePickupShipping/Model/Carrier/Command/GetConfigPrice.php
  InventoryInStorePickupShipping/Test/Integration/Carrier/InStorePickupTest.php
  InventoryInStorePickupShipping/Test/Integration/IsInStorePickupDeliveryAvailableForCartTest.php
  InventoryInStorePickupShippingAdminUi/etc/adminhtml/system.xml
  InventoryInStorePickupShippingApi/Model/Carrier/GetCarrierTitle.php
  InventoryInStorePickupShippingApi/Model/Carrier/InStorePickup.php
  InventoryInStorePickupShippingApi/etc/config.xml
Labels: 2.4.0-develop: :one:, Partner: Vaimo, Progress: review, Regression bug, partners-contribution

#3086 [TSG][2.3] MC-35125: [2.3.5-p2] 20+ Failing MFTF Tests
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest.xml
  InventoryCatalog/Test/Mftf/Data/QueueConsumerData.xml
Labels: Progress: approved

#3046 Issue with oversell of products
  InventoryReservationCli/Model/ResourceModel/GetOrderDataForOrderInFinalState.php
  InventoryReservationCli/Model/ResourceModel/GetOrderIncrementId.php
  InventoryReservationCli/Model/SalableQuantityInconsistency.php
  InventoryReservationCli/Model/SalableQuantityInconsistency/AddCompletedOrdersToForUnresolvedReservations.php
  InventoryReservationCli/Model/SalableQuantityInconsistency/AddExpectedReservations.php
  InventoryReservationCli/Model/SalableQuantityInconsistency/Collector.php
  InventoryReservationCli/Test/Unit/Model/ResourceModel/GetOrderDataForOrderInFinalStateTest.php
  InventorySales/Model/SalesEventToArrayConverter.php
  InventorySales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php
  InventorySales/Test/Integration/Order/PlaceOrderOnDefaultStockTest.php
  InventorySales/Test/Integration/StockManagement/ReservationPlacingDuringRegisterProductsSaleTest.php
  InventorySalesApi/Api/Data/SalesEventInterface.php
  InventoryShipping/Model/SourceDeductionRequestFromShipmentFactory.php
Labels: 2.4.0-develop: :one:, Progress: review

#3100 MSI-3093: Export product low stock notifications report not working fix.
  InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockCsv.php
  InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockExcel.php
Labels: Progress: approved, QA Passed

#3085 Fix product is not shown on category page if the product is not assigned to any source and "display out stock" is "Yes"
  InventoryCatalog/Model/ResourceModel/AddStockDataToCollection.php
  InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockDataToCollectionTest.php
  InventoryCatalog/Test/Mftf/Test/StorefrontCustomWebsiteCustomStockDisplayOutOfStockTest.xml
Labels: 1.2-develop, Progress: approved, QA Passed

#3069 MC-34794: MSI Low Stock Report Grid Empty
  InventoryAdminUi/Test/Mftf/Test/AdminLowStockReportForSimpleProductWithDefaultStockAndZeroQuantityTest.xml
  InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
Labels: Progress: approved, QA Passed

#3084 Fix product is not shown on category page if the product is not assigned to any source and "display out stock" is "Yes"
  InventoryCatalog/Model/ResourceModel/AddStockDataToCollection.php
  InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockDataToCollectionTest.php
  InventoryCatalog/Test/Mftf/Test/StorefrontCustomWebsiteCustomStockDisplayOutOfStockTest.xml
  InventoryCatalogSearch/Plugin/Search/FilterMapper/AdaptStockStatusFilterPlugin.php
Labels: 1.1-develop, Progress: approved, QA Passed

#3042 MC-34169: MSI Low Stock Report Grid Empty
  InventoryAdminUi/Test/Mftf/Test/AdminLowStockReportForSimpleProductWithDefaultStockAndZeroQuantityTest.xml
  InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
Labels: Progress: approved, QA Passed

#2939 MSI-2917: CLI command 'inventory:reservation:list-inconsistencies' doesn't work with virtual products.
  InventoryReservationCli/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalState.php
  InventoryReservationCli/Test/Integration/Model/GetSalableQuantityInconsistenciesTest.php
  InventoryReservationCli/Test/Integration/_files/create_incomplete_order_without_reservation_virtual_product.php
Labels: Progress: review, QA Passed

#3096 Accept city as null during creating CreditMemo
  InventorySourceSelectionApi/Model/GetInventoryRequestFromOrder.php
Labels: Progress: approved, QA Passed
