Repository magento/inventory, pull requests merged in 2020-01, with the labels that each got.

#2767 removed unnecessary line code for command save to source.
  app/code/Magento/Inventory/Model/Source/Command/Save.php
Labels: Cleanup, Progress: approved

#2766 Fix wrong field declaration.
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminManageStockInConfigurationTurnedOffForDownloadableProductTest.xml
Labels: Progress: approved

#2768 Refactor ManageStockCondition.php
  app/code/Magento/InventorySales/Model/IsProductSalableCondition/ManageStockCondition.php
Labels: Partner: Strix, Progress: approved, partners-contribution

#2732 The configurable product is displayed in Storefront despite that all the quantity is reserved. Two error messages appear if try to add this product to cart
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminCreateNewWebsiteWithStoreAndStoreViewTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminMultipleWebsitesAssignedAsSaleChannelsToStockTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminNewWebsiteHasDefaultStockAssignedAutomaticallyTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/AdminStockCannotBeDeletedWhenSalesChannelIsAssignedTest.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontCreateOrderAllQuantityConfigurableProductCustomStock.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderAllOptionQuantityConfigurableProductCustomStock.xml
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/StorefrontPriceOfConfigurableProductAssignedToTestStockAndTestWebsiteWhenOptionOfDisplayingOutOfStockProductsEnabledTest.xml
  app/code/Magento/InventoryConfigurableProduct/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
  app/code/Magento/InventoryConfigurableProduct/Plugin/Model/Product/Type/Configurable/IsSalableOptionPlugin.php
  app/code/Magento/InventoryConfigurableProduct/etc/frontend/di.xml
Labels: Progress: approved, QA Passed

#2772 Implement modifiers for SourceDataProvider and StockDataProvider
  app/code/Magento/InventoryAdminUi/Ui/DataProvider/SourceDataProvider.php
  app/code/Magento/InventoryAdminUi/Ui/DataProvider/StockDataProvider.php
Labels: Progress: changes requested, Source Management, Stock Management

#2775 Improve for array function to source and stock
  app/code/Magento/InventoryApi/Model/SourceItemValidatorChain.php
  app/code/Magento/InventoryApi/Model/SourceValidatorChain.php
  app/code/Magento/InventoryApi/Model/StockSourceLinkValidatorChain.php
  app/code/Magento/InventoryApi/Model/StockValidatorChain.php
Labels: Performance, Source Management

#2776 GraphQl support for In-Store Pickup [Mutation] - Extended Webapi Tests
  InventoryInStorePickupSalesApi/Test/Api/PlaceOrderTest.php
  InventoryInStorePickupSalesApi/Test/_files/quote_with_save_shipping_address_to_address_book.php
  InventoryInStorePickupSalesApi/Test/_files/quote_with_save_shipping_address_to_address_book_rollback.php
  InventoryInStorePickupSalesApi/Test/_files/quote_with_shipping_address_same_as_billing.php
  InventoryInStorePickupSalesApi/Test/_files/quote_with_shipping_address_same_as_billing_rollback.php
  InventoryInStorePickupSalesApi/Test/_files/store_for_eu_website_store_carriers_conf.php
  InventoryInStorePickupSalesApi/Test/_files/store_for_eu_website_store_carriers_conf_rollback.php
Labels: Store Pickup, WEB API

#2780 MC-30456: Test ProductAlertTest is failing
  app/code/Magento/InventoryProductAlert/Test/Integration/ProductAlertTest.php
Labels: Progress: approved

#2784 MSI-2557: Investigate code duplication can be avoided.
  InventoryInStorePickupQuoteGraphQl/Model/Cart/GetShippingAddress/AdaptGetShippingAddressPlugin.php
  InventoryInStorePickupQuoteGraphQl/Model/Cart/SetShippingAddressesOnCart.php
  InventoryInStorePickupQuoteGraphQl/etc/graphql/di.xml
  InventoryInStorePickupQuoteGraphQl/etc/schema.graphqls
Labels: Store Pickup

#2758 Search term handling implementation
  InventoryInStorePickup/Model/SearchRequest/Area.php
  InventoryInStorePickup/Model/SearchRequest/Area/GetDistanceToSources.php
  InventoryInStorePickup/Model/SearchRequest/Area/SearchTerm/CityParser.php
  InventoryInStorePickup/Model/SearchRequest/Area/SearchTerm/CountryParser.php
  InventoryInStorePickup/Model/SearchRequest/Area/SearchTerm/PostcodeParser.php
  InventoryInStorePickup/Model/SearchRequest/Builder/AreaBuilder.php
  InventoryInStorePickup/Model/SearchRequestBuilder.php
  InventoryInStorePickup/Test/Integration/GetPickupLocations/CombinedTest.php
  InventoryInStorePickup/Test/Integration/GetPickupLocations/DistanceFilterOfflineTest.php
  InventoryInStorePickup/Test/Integration/SearchRequestBuilderTest.php
  InventoryInStorePickup/composer.json
  InventoryInStorePickup/etc/di.xml
  InventoryInStorePickup/etc/module.xml
  InventoryInStorePickupApi/Api/Data/SearchRequest/AreaInterface.php
  InventoryInStorePickupApi/Model/SearchRequest/Area/Pipeline.php
  InventoryInStorePickupApi/Model/SearchRequest/Area/SearchTerm/DelimiterConfig.php
  InventoryInStorePickupApi/Model/SearchRequest/Area/SearchTerm/ParserInterface.php
  InventoryInStorePickupApi/Model/SearchRequestBuilderInterface.php
  InventoryInStorePickupApi/Test/Api/GetPickupLocationsTest.php
  InventoryInStorePickupApi/etc/config.xml
  InventoryInStorePickupFrontend/Model/Ui/DelimiterConfigProvider.php
  InventoryInStorePickupFrontend/etc/frontend/di.xml
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-pickup.js
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-selector.js
  InventoryInStorePickupGraphQl/Model/Resolver/PickupLocations/SearchRequest/Distance.php
Labels: Award: advanced, Award: category of expertise, Award: complex, Partner: Vaimo, Progress: approved, Store Pickup, WIP, partners-contribution

#2786 Reorder virtual product MFTF test stabilization.
  app/code/Magento/InventoryAdminUi/Test/Mftf/Test/LoggedInCustomerReorderVirtualProductOnTestStockTest.xml
Labels: Progress: approved

#2800 Fix backorder notification should not be displayed when manage stock is set to "NO"
  InventorySales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php
  InventorySales/Test/Unit/Model/IsProductSalableCondition/BackOrderNotifyCustomerConditionTest.php
Labels: Progress: approved, QA Passed

#2794 MSI-2719: Introduce a Bulk version of IsProductSalableForRequestedQtyInterface API.
  InventorySales/Model/AreProductsSalableForRequestedQty.php
  InventorySales/Model/AreProductsSalableForRequestedQty/ProductsSalableResult.php
  InventorySales/Model/CheckItemsQuantity.php
  InventorySales/etc/di.xml
  InventorySalesApi/Api/AreProductsSalableForRequestedQtyInterface.php
  InventorySalesApi/Api/Data/ProductsSalableResultInterface.php
Labels: Progress: review, QA Passed

#2798 [TSG] Fixes for 2.4 (pr5) (2.4-develop)
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoTotalRefundFullInvoiceFullShipmentGroupedProductDefaultStock.xml
Labels: Progress: approved
