Repository magento/inventory, pull requests merged in 2020-04, with the labels that each got.

#2913 AreProductsSalableForRequestedQtyInterface Rework
  InventorySales/Model/AreProductsSalableForRequestedQty.php
  InventorySales/Model/AreProductsSalableForRequestedQty/ProductsSalableInfo.php
  InventorySales/Model/CheckItemsQuantity.php
  InventorySales/Model/ProductSalableResult.php
  InventorySales/Model/ProductsSalableResult.php
  InventorySales/etc/di.xml
  InventorySalesApi/Api/AreProductsSalableForRequestedQtyInterface.php
  InventorySalesApi/Api/Data/IsProductSalableResultInterface.php
  InventorySalesApi/Api/Data/ProductSalableForRequestedQtyInfoInterface.php
  InventorySalesApi/Api/Data/ProductsSalableResultInterface.php
  InventorySalesApi/Test/Api/AreProductsSalableForRequestedQtyTest.php
  InventorySalesApi/etc/webapi.xml
Labels: Progress: changes requested

#2889 MSI-2882: Store Pickup button present on check-out when products are …
  InventoryInStorePickupFrontend/Block/Checkout/LayoutProcessor.php
  InventoryInStorePickupFrontend/Model/Validator/IsStorePickUpAvailableForWebsiteValidator.php
  InventoryInStorePickupFrontend/composer.json
  InventoryInStorePickupShipping/Model/IsInStorePickupDeliveryAvailableForCart.php
  InventoryInStorePickupShipping/Test/Integration/IsInStorePickupDeliveryAvailableForCartTest.php
  InventoryInStorePickupShipping/etc/di.xml
  InventoryInStorePickupShippingApi/Model/Carrier/InStorePickup.php
  InventoryInStorePickupShippingApi/Model/IsInStorePickupDeliveryAvailableForCartInterface.php
Labels: Award: bug fix, Award: category of expertise, Award: complex, Award: special achievement, Award: test coverage, Progress: review, Store Pickup

#2916 MSI-2592: Alternative for IsProductSalableInterface when working with a list of items.
  InventorySales/Model/AreProductsSalable.php
  InventorySales/Model/AreProductsSalableForRequestedQty.php
  InventorySales/Model/AreProductsSalableForRequestedQty/ProductsSalableResult.php
  InventorySales/Model/CheckItemsQuantity.php
  InventorySales/Model/IsProductSalableForRequestedQtyRequest.php
  InventorySales/Model/IsProductSalableForRequestedQtyResult.php
  InventorySales/Model/IsProductSalableResult.php
  InventorySales/etc/di.xml
  InventorySalesApi/Api/AreProductsSalableForRequestedQtyInterface.php
  InventorySalesApi/Api/AreProductsSalableInterface.php
  InventorySalesApi/Api/Data/IsProductSalableForRequestedQtyRequestInterface.php
  InventorySalesApi/Api/Data/IsProductSalableForRequestedQtyResultInterface.php
  InventorySalesApi/Api/Data/IsProductSalableResultInterface.php
  InventorySalesApi/Api/Data/ProductsSalableResultInterface.php
  InventorySalesApi/Api/IsProductSalableForRequestedQtyInterface.php
  InventorySalesApi/Api/IsProductSalableInterface.php
  InventorySalesApi/Test/Api/AreProductsSalableForRequestedQtyTest.php
  InventorySalesApi/Test/Api/AreProductsSalableTest.php
  InventorySalesApi/etc/webapi.xml
Labels: Progress: approved

#2922 [TSG] MC-32608: [MSI][MFTF] AdminCreateCreditMemoSimpleProductWithChangedSkuCustomStockTest fails because of bad design
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuCustomStockTest.xml
Labels: Progress: approved

#2920 MQE-1994: Refactor MFTF tests/actionGroups that need custom actions
  InventoryAdminUi/Test/Mftf/Helper/AssertSourceCodeIsNotEditable.php
  InventoryAdminUi/Test/Mftf/Test/AdminCannotEditExistingSourceCodeInGridTest.xml
Labels: Progress: approved

#2934 Fix When upgrading to 2.3.4 with encrypted drive, seeing "File name too long" error
  InventoryAdminUi/Test/Mftf/Test/StorefrontBackordersEnabledOnConfigPageAndAppliedFromHomepageToWithConfigurableProductWithDropDownAttrAndVariablesNonDefaultSourceTest.xml
Labels: Event: Global-Contribution-Day, Progress: approved

#2938 [TSG] MC-32517: Error on Backend Orders Page after split database
  InventoryShippingAdminUi/Model/ResourceModel/GetAllocatedSourcesForOrder.php
  InventoryShippingAdminUi/Test/Integration/Model/ResourceModel/GetAllocatedSourcesForOrderTest.php
Labels: QA Passed, Regression bug

#2840 #26986 REST API Pagination issue
  InventoryInStorePickup/Test/Integration/GetPickupLocations/CombinedTest.php
Labels: Auto-Tests: Covered, Award: bug fix, Partner: Mediotype, Progress: approved, partners-contribution

#2950 [REST] Unable to create a product without type_id
  InventoryLowQuantityNotification/Plugin/Catalog/Model/ResourceModel/Product/ProcessDefaultSourceItemConfigurationPlugin.php
Labels: 1.2.0-develop, QA Passed

#2928 Replace IsProductSalable and IsProductSalableForRequestedQty usages.
  InventoryAdvancedCheckout/Plugin/Model/IsProductInStock/ProductInStockPlugin.php
  InventoryBundleProduct/Model/GetBundleProductStockStatus.php
  InventoryBundleProduct/Plugin/Bundle/Model/ResourceModel/Selection/Collection/AdaptAddQuantityFilterPlugin.php
  InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetProductStockStatusBySkuPlugin.php
  InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetProductStockStatusPlugin.php
  InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetStockStatusBySkuPlugin.php
  InventoryCatalog/Plugin/CatalogInventory/Api/StockRegistry/AdaptGetStockStatusPlugin.php
  InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAddStockStatusToProductsPlugin.php
  InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
  InventoryCatalog/Test/Integration/NegativeMinQtyPlaceOrderTest.php
  InventoryCatalog/Test/Integration/NegativeMinQtyTest.php
  InventoryConfigurableProduct/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
  InventoryConfigurableProduct/Plugin/Model/Product/Type/Configurable/IsSalableOptionPlugin.php
  InventoryConfigurableProduct/Test/Integration/IsProductSalable/IsSalableLegacyStockItemIsInStockTest.php
  InventoryExportStock/Model/PreciseExportStockProcessor.php
  InventoryGraphQl/Model/Resolver/StockStatusProvider.php
  InventoryInStorePickupQuoteGraphQl/Test/Api/Customer/PickupLocationForShippingTest.php
  InventoryProductAlert/Plugin/AdaptProductSalabilityPlugin.php
  InventoryRequisitionList/Plugin/Model/RequisitionListItem/Validator/StockPlugin.php
  InventorySales/Plugin/StockState/CheckQuoteItemQtyPlugin.php
  InventorySales/Test/Integration/IsProductSalable/BackorderConditionTest.php
  InventorySales/Test/Integration/IsProductSalable/IsAnySourceItemInStockConditionTest.php
  InventorySales/Test/Integration/IsProductSalable/IsSalableWithReservationsConditionTest.php
  InventorySales/Test/Integration/IsProductSalable/ManageStockConditionTest.php
  InventorySales/Test/Integration/IsProductSalable/MinQtyConditionTest.php
  InventorySales/Test/Integration/IsProductSalableForRequestedQty/BackorderConditionTest.php
  InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsAnySourceItemInStockConditionTest.php
  InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsCorrectQtyConditionTest.php
  InventorySales/Test/Integration/IsProductSalableForRequestedQty/IsSalableWithReservationsConditionTest.php
  InventorySales/Test/Integration/IsProductSalableForRequestedQty/ManageStockConditionTest.php
  InventorySalesApi/Test/Api/StockRepository/SalesChannelManagementTest.php
Labels: 1.2.0-develop, Event: Global-Contribution-Day, Progress: approved, QA Passed

#2964 In store pickup refactoring
  InventoryInStorePickup/Model/SearchCriteria/ResolveArea.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveDefaultFilters.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveFilters.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveIntersection.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveMeta.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveScopeFilter.php
  InventoryInStorePickupApi/Model/SearchCriteria/ResolverInterface.php
  InventoryInStorePickupApi/Model/SearchCriteriaResolverChain.php
  InventoryInStorePickupFrontend/view/frontend/web/template/store-selector/popup.html
  InventoryInStorePickupSales/Model/NotifyOrdersAreReadyForPickup.php
  InventoryInStorePickupSales/Model/Result.php
  InventoryInStorePickupSales/Test/Integration/NotifyOrdersAreReadyForPickupTest.php
  InventoryInStorePickupSalesAdminUi/Controller/Adminhtml/Order/NotifyPickup.php
  InventoryInStorePickupSalesApi/Api/Data/ResultInterface.php
  InventoryInStorePickupShipping/Model/Carrier/Command/GetConfigPrice.php
  InventoryInStorePickupShipping/Model/Carrier/Command/GetFreePackages.php
  InventoryInStorePickupShipping/Model/Carrier/Command/GetShippingPrice.php
  InventoryInStorePickupShipping/Model/Carrier/Command/GetShippingPriceRequest.php
  InventoryInStorePickupShipping/Model/Carrier/ShippingPriceRequest.php
  InventoryInStorePickupShippingApi/Api/Data/ShippingPriceRequestInterface.php
  InventoryInStorePickupShippingApi/Model/Carrier/Command/GetFreePackagesInterface.php
  InventoryInStorePickupShippingApi/Model/Carrier/Command/GetShippingPriceInterface.php
  InventoryInStorePickupShippingApi/Model/Carrier/Command/GetShippingPriceRequestInterface.php
  InventoryInStorePickupShippingApi/Model/Carrier/InStorePickup.php
Labels: 1.2.0-develop, Partner: Vaimo, Progress: approved, partners-contribution

#2952 Performance improvements
  Inventory/Model/Stock/Command/GetCache.php
  Inventory/etc/di.xml
  InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
Labels: 1.2.0-develop, Progress: approved

#2973 Adapt bundle product stock status considering option default qty.
  InventoryBundleProduct/Model/GetBundleProductStockStatus.php
  InventoryBundleProduct/Model/GetProductSelection.php
  InventoryBundleProduct/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
  InventoryBundleProduct/composer.json
  InventoryBundleProduct/etc/di.xml
  InventoryBundleProductIndexer/Plugin/Bundle/Model/LinkManagement/ReindexSourceItemsAfterAddBundleSelectionPlugin.php
  InventoryBundleProductIndexer/Plugin/Bundle/Model/LinkManagement/ReindexSourceItemsAfterRemoveBundleSelectionPlugin.php
  InventoryBundleProductIndexer/Plugin/Bundle/Model/LinkManagement/ReindexSourceItemsAfterSaveBundleSelectionPlugin.php
Labels: Progress: approved

#2976 Added @see tags for deprecated interfaces
  InventorySalesApi/Api/IsProductSalableForRequestedQtyInterface.php
  InventorySalesApi/Api/IsProductSalableInterface.php
Labels: Cleanup, Progress: review

#3003 Disable page builder on the store pickup description field
  InventoryInStorePickupAdminUi/view/adminhtml/ui_component/inventory_source_form.xml
Labels: 1.2.0-develop

#3004 [TSG] MC-33244: [MSI][MFTF] AdminUserCreateOrderWithSimpleProductOnTestStockFromCustomWebsiteTest fails because of bad design
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderWithSimpleProductOnTestStockFromCustomWebsiteTest.xml
Labels: 1.2.0-develop

#3000 [TSG] MC-33244: [MSI][MFTF] AdminUserCreateOrderWithSimpleProductOnTestStockFromCustomWebsiteTest fails because of bad design
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderWithSimpleProductOnTestStockFromCustomWebsiteTest.xml
Labels: Progress: approved

#2984 [TSG-CSL3] For 1.2.0 (MC-30568: Shared indexers have invalid status after full reindex)
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderAllOptionQuantityConfigurableProductCustomStockTest.xml
Labels: 1.2.0-develop, Progress: approved

#2983 [TSG-CSL3] For 1.2 (MC-30568: Shared indexers have invalid status after full reindex)
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderAllOptionQuantityConfigurableProductCustomStockTest.xml
Labels: Progress: approved
