Repository magento/inventory, pull requests merged in 2020-08, with the labels that each got.

#2966 MFTF test fix. Changes for settings of downloadable shareable product.
  InventoryAdminUi/Test/Mftf/Test/GuestCustomerOrderedDownloadableProductOnDefaultStockFromHomepageTest.xml
Labels: 2.4-develop: dep, MFTF, Progress: approved, Progress: delivery

#3144 Reservation fix
  InventoryReservationCli/Command/Input/GetReservationFromCompensationArgument.php
  InventoryReservationCli/Model/SalableQuantityInconsistency/Collector.php
  InventoryReservations/Model/ResourceModel/CleanupReservations.php
  InventorySales/Model/ReturnProcessor/GetSalesChannelForOrder.php
  InventorySales/Model/ReturnProcessor/GetSourceDeductionRequestFromSourceSelection.php
  InventorySales/Model/ReturnProcessor/ProcessRefundItems.php
  InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
  InventoryShipping/Observer/VirtualSourceDeductionProcessor.php
Labels: Progress: approved, QA Failed

#3152 Ensure that numeric source codes are preserved
  InventoryInStorePickup/Model/ResourceModel/Source/GetOrderedDistanceToSources.php
Labels: Progress: approved, QA Passed

#3154 Sync 1.2-master with 1.2-develop
  InventoryAdminUi/Test/Integration/_files/user_with_restricted_role_rollback.php
  InventoryInStorePickup/Model/ResourceModel/Source/GetOrderedDistanceToSources.php
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontPickUpSourceInfoSimpleProductCustomStockTest.xml
  InventoryReservationCli/Command/Input/GetReservationFromCompensationArgument.php
  InventoryReservationCli/Model/SalableQuantityInconsistency/Collector.php
  InventoryReservations/Model/ResourceModel/CleanupReservations.php
  InventorySales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php
  InventorySales/Model/ReturnProcessor/GetSalesChannelForOrder.php
  InventorySales/Model/ReturnProcessor/GetSourceDeductionRequestFromSourceSelection.php
  InventorySales/Model/ReturnProcessor/ProcessRefundItems.php
  InventorySales/Observer/CatalogInventory/CancelOrderItemObserver.php
  InventorySales/Test/Unit/Model/IsProductSalableCondition/BackOrderNotifyCustomerConditionTest.php
  InventoryShipping/Observer/VirtualSourceDeductionProcessor.php
Labels: 2.4-develop: :one:

#3158 MFTF Test for pickup order with product with inventory on numeric source
  InventoryInStorePickupAdminUi/Test/Mftf/Data/MsiSourceData.xml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithSimpleProductNumericSourceTest.xml
Labels: Progress: approved

#3148 MC-35574: show source stock instead of default stock
  InventoryVisualMerchandiser/LICENSE.txt
  InventoryVisualMerchandiser/LICENSE_AFL.txt
  InventoryVisualMerchandiser/Plugin/Model/Resolver/QuantityAndStockPlugin.php
  InventoryVisualMerchandiser/README.md
  InventoryVisualMerchandiser/Test/Integration/Model/Category/ProductsTest.php
  InventoryVisualMerchandiser/Test/_files/product_with_category.php
  InventoryVisualMerchandiser/Test/_files/product_with_category_rollback.php
  InventoryVisualMerchandiser/Test/_files/source_items_products.php
  InventoryVisualMerchandiser/Test/_files/source_items_products_rollback.php
  InventoryVisualMerchandiser/composer.json
  InventoryVisualMerchandiser/etc/di.xml
  InventoryVisualMerchandiser/etc/module.xml
  InventoryVisualMerchandiser/registration.php
  _metapackage/composer.json
Labels: Progress: review, QA Passed

#3167 MC-34817: Error in logs after MC-22212
  InventoryCatalog/etc/di.xml
Labels: Progress: approved

#3163 Sync 1.2-master with 1.2-develop
  InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin.php
  InventoryCatalog/etc/di.xml
  InventoryInStorePickupAdminUi/Test/Mftf/Data/MsiSourceData.xml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithSimpleProductNumericSourceTest.xml
  InventoryVisualMerchandiser/LICENSE.txt
  InventoryVisualMerchandiser/LICENSE_AFL.txt
  InventoryVisualMerchandiser/Plugin/Model/Resolver/QuantityAndStockPlugin.php
  InventoryVisualMerchandiser/README.md
  InventoryVisualMerchandiser/Test/Integration/Model/Category/ProductsTest.php
  InventoryVisualMerchandiser/Test/_files/product_with_category.php
  InventoryVisualMerchandiser/Test/_files/product_with_category_rollback.php
  InventoryVisualMerchandiser/Test/_files/source_items_products.php
  InventoryVisualMerchandiser/Test/_files/source_items_products_rollback.php
  InventoryVisualMerchandiser/composer.json
  InventoryVisualMerchandiser/etc/di.xml
  InventoryVisualMerchandiser/etc/module.xml
  InventoryVisualMerchandiser/registration.php
  _metapackage/composer.json
Labels: 2.4-develop: dep, Progress: approved

#3168 MFTF test coverage customer notification for pickup orders with complex products
  InventoryInStorePickupAdminUi/Test/Mftf/Test/AdminNotifyCustomerForPickupOrderBundleProductTest.xml
  InventoryInStorePickupAdminUi/Test/Mftf/Test/AdminNotifyCustomerForPickupOrderConfigurableProductTest.xml
  InventoryInStorePickupAdminUi/Test/Mftf/Test/AdminNotifyCustomerForPickupOrderGroupedProductTest.xml
Labels: Progress: approved
