Repository magento/inventory, pull requests merged in 2020-07, with the labels that each got.

#3120 MSI-3116: In Store Pickup order with Bundle product could not be notified.
  InventoryInStorePickupSales/Model/Order/IsFulfillable.php
Labels: Progress: approved, QA Passed

#3114 MSI-3110-In-Store-Pickup-delivery-not-available-for-order-with-Configurable-product.
  InventoryInStorePickup/Model/SearchCriteria/ResolveIntersection.php
  InventoryInStorePickupApi/Test/Api/GetPickupLocationsTest.php
  InventoryInStorePickupShipping/Model/Carrier/Validation/PickupLocationsAvailabilityValidator.php
Labels: Award: bug fix, Award: category of expertise, Partner: Vaimo, Progress: approved, partners-contribution

#3122 Sync 1.2.0-master with 1.2.0-develop
  InventoryInStorePickup/Model/SearchCriteria/ResolveIntersection.php
  InventoryInStorePickupApi/Test/Api/GetPickupLocationsTest.php
  InventoryInStorePickupSales/Model/Order/IsFulfillable.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/GetOrderNotificationSentByOrderId.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/GetOrderSendNotificationByOrderId.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/SaveOrderNotification.php
  InventoryInStorePickupSales/etc/db_schema.xml
  InventoryInStorePickupShipping/Model/Carrier/Validation/PickupLocationsAvailabilityValidator.php
Labels: 2.4.0-develop: :one:

#3092 [TSG] MC-34513: [Backport for 2.4.x-p1] Allow an authenticated user in custom role without permissons can edit sources
  InventoryAdminUi/Controller/Adminhtml/Source/Edit.php
  InventoryAdminUi/Controller/Adminhtml/Source/InlineEdit.php
  InventoryAdminUi/Controller/Adminhtml/Source/MassDisable.php
  InventoryAdminUi/Controller/Adminhtml/Source/MassEnable.php
  InventoryAdminUi/Controller/Adminhtml/Source/Save.php
  InventoryAdminUi/Test/Integration/Ui/Component/SourceListingTest.php
  InventoryAdminUi/Test/Integration/_files/user_with_restricted_role.php
  InventoryAdminUi/Test/Integration/_files/user_with_restricted_role_rollback.php
  InventoryAdminUi/Ui/Component/Listing/Column/EditAction.php
  InventoryAdminUi/Ui/Component/Listing/Columns.php
  InventoryAdminUi/Ui/Component/Listing/MassAction.php
  InventoryAdminUi/view/adminhtml/ui_component/inventory_source_listing.xml
Labels: Progress: approved, QA Passed

#3125 Sync 1.2-master with 1.2-develop
  InventoryAdminUi/Test/Mftf/Test/AdminLowStockReportForSimpleProductWithDefaultStockAndZeroQuantityTest.xml
  InventoryCatalog/Model/ResourceModel/AddStockDataToCollection.php
  InventoryCatalog/Test/Integration/CatalogInventory/Model/ResourceModel/Stock/Status/AddStockDataToCollectionTest.php
  InventoryCatalog/Test/Mftf/Test/StorefrontCustomWebsiteCustomStockDisplayOutOfStockTest.xml
  InventoryInStorePickup/Model/SearchCriteria/ResolveIntersection.php
  InventoryInStorePickupApi/Test/Api/GetPickupLocationsTest.php
  InventoryInStorePickupSales/Model/Order/IsFulfillable.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/GetOrderNotificationSentByOrderId.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/GetOrderSendNotificationByOrderId.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/SaveOrderNotification.php
  InventoryInStorePickupSales/etc/db_schema.xml
  InventoryInStorePickupShipping/Model/Carrier/Validation/PickupLocationsAvailabilityValidator.php
  InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
  InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockCsv.php
  InventoryLowQuantityNotificationAdminUi/Controller/Adminhtml/Report/ExportLowstockExcel.php
  InventoryReservationCli/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalState.php
  InventoryReservationCli/Test/Integration/Model/GetSalableQuantityInconsistenciesTest.php
  InventoryReservationCli/Test/Integration/_files/create_incomplete_order_without_reservation_virtual_product.php
  InventorySourceSelectionApi/Model/GetInventoryRequestFromOrder.php
Labels: 2.4-develop: :one:

#3091 [TSG] MC-34754: [Backport for 2.4.0-p1] Improper Authorization in Inventory module in Store allows Edit Stocks, Delete Stocks, Source to Stock Assigning without permissions
  Inventory/Test/Integration/Stock/StockSourceLinkProcessorTest.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Delete.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Edit.php
  InventoryAdminUi/Controller/Adminhtml/Stock/InlineEdit.php
  InventoryAdminUi/Controller/Adminhtml/Stock/MassDelete.php
  InventoryAdminUi/Controller/Adminhtml/Stock/NewAction.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Save.php
  InventoryAdminUi/Model/Stock/StockSourceLinkProcessor.php
  InventoryAdminUi/Test/Integration/Ui/Component/StocksListingTest.php
  InventoryAdminUi/Test/Integration/_files/user_assigned_to_stocks.php
  InventoryAdminUi/Test/Integration/_files/user_assigned_to_stocks_rollback.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Buttons/NewButton.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Column/EditAction.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Columns.php
  InventoryAdminUi/Ui/Component/Listing/Stock/MassAction.php
  InventoryAdminUi/view/adminhtml/ui_component/inventory_stock_listing.xml
  InventoryCatalogAdminUi/Ui/Component/AssignSources/Button.php
  InventoryCatalogAdminUi/Ui/Component/AssignSources/Record.php
Labels: Progress: changes requested, QA Passed

#3038 MC-34258: Product mass Update Attributes results in blank page
  InventoryCatalogAdminUi/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml
Labels: Progress: approved

#3068 [TSG] MC-34514: [Backport for 2.3.x] Allow an authenticated user in custom role without permissons can edit sources
  InventoryAdminUi/Controller/Adminhtml/Source/Edit.php
  InventoryAdminUi/Controller/Adminhtml/Source/InlineEdit.php
  InventoryAdminUi/Controller/Adminhtml/Source/MassDisable.php
  InventoryAdminUi/Controller/Adminhtml/Source/MassEnable.php
  InventoryAdminUi/Controller/Adminhtml/Source/Save.php
  InventoryAdminUi/Test/Integration/Ui/Component/SourceListingTest.php
  InventoryAdminUi/Test/Integration/_files/user_with_restricted_role.php
  InventoryAdminUi/Test/Integration/_files/user_with_restricted_role_rollback.php
  InventoryAdminUi/Ui/Component/Listing/Column/EditAction.php
  InventoryAdminUi/Ui/Component/Listing/Columns.php
  InventoryAdminUi/Ui/Component/Listing/MassAction.php
  InventoryAdminUi/view/adminhtml/ui_component/inventory_source_listing.xml
Labels: QA Passed

#3033 MC-34215: Product mass Update Attributes results in blank page
  InventoryCatalogAdminUi/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml
Labels: Progress: approved

#3134 MFTF Store pickup orders with complex products tests
  InventoryAdminUi/Test/Mftf/Data/CatalogInventoryData.xml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithBundleProductCustomStockTest.xml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithConfigurableProductCustomStockTest.xml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithGroupedProductCustomStockTest.xml
Labels: Progress: approved

#3135 MC-35084: Credit memos with downloadable product and numeric SKU fail to process and return white screen
  InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php
  InventorySales/Test/Unit/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriorityTest.php
Labels: Progress: approved, QA Passed

#3129 MC-35060: Credit memos with downloadable product and numeric SKU fail to process and return white screen
  InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php
  InventorySales/Test/Unit/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriorityTest.php
Labels: Progress: approved

#3083 [TSG] MC-34751: [Backport for 2.3.x] Improper Authorization in Inventory module in Store allows Edit Stocks, Delete Stocks, Source to Stock Assigning without permissions
  Inventory/Test/Integration/Stock/StockSourceLinkProcessorTest.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Delete.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Edit.php
  InventoryAdminUi/Controller/Adminhtml/Stock/InlineEdit.php
  InventoryAdminUi/Controller/Adminhtml/Stock/MassDelete.php
  InventoryAdminUi/Controller/Adminhtml/Stock/NewAction.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Save.php
  InventoryAdminUi/Model/Stock/StockSourceLinkProcessor.php
  InventoryAdminUi/Test/Integration/Ui/Component/StocksListingTest.php
  InventoryAdminUi/Test/Integration/_files/user_assigned_to_stocks.php
  InventoryAdminUi/Test/Integration/_files/user_assigned_to_stocks_rollback.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Buttons/NewButton.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Column/EditAction.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Columns.php
  InventoryAdminUi/Ui/Component/Listing/Stock/MassAction.php
  InventoryAdminUi/view/adminhtml/ui_component/inventory_stock_listing.xml
  InventoryCatalogAdminUi/Ui/Component/AssignSources/Button.php
  InventoryCatalogAdminUi/Ui/Component/AssignSources/Record.php
Labels: QA Passed

#3138 Sync 1.2-master with 1.2-develop
  Inventory/Test/Integration/Stock/StockSourceLinkProcessorTest.php
  InventoryAdminUi/Controller/Adminhtml/Source/Edit.php
  InventoryAdminUi/Controller/Adminhtml/Source/InlineEdit.php
  InventoryAdminUi/Controller/Adminhtml/Source/MassDisable.php
  InventoryAdminUi/Controller/Adminhtml/Source/MassEnable.php
  InventoryAdminUi/Controller/Adminhtml/Source/Save.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Delete.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Edit.php
  InventoryAdminUi/Controller/Adminhtml/Stock/InlineEdit.php
  InventoryAdminUi/Controller/Adminhtml/Stock/MassDelete.php
  InventoryAdminUi/Controller/Adminhtml/Stock/NewAction.php
  InventoryAdminUi/Controller/Adminhtml/Stock/Save.php
  InventoryAdminUi/Model/Stock/StockSourceLinkProcessor.php
  InventoryAdminUi/Test/Integration/Ui/Component/SourceListingTest.php
  InventoryAdminUi/Test/Integration/Ui/Component/StocksListingTest.php
  InventoryAdminUi/Test/Integration/_files/user_assigned_to_stocks.php
  InventoryAdminUi/Test/Integration/_files/user_assigned_to_stocks_rollback.php
  InventoryAdminUi/Test/Integration/_files/user_with_restricted_role.php
  InventoryAdminUi/Test/Integration/_files/user_with_restricted_role_rollback.php
  InventoryAdminUi/Test/Mftf/Data/CatalogInventoryData.xml
  InventoryAdminUi/Ui/Component/Listing/Column/EditAction.php
  InventoryAdminUi/Ui/Component/Listing/Columns.php
  InventoryAdminUi/Ui/Component/Listing/MassAction.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Buttons/NewButton.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Column/EditAction.php
  InventoryAdminUi/Ui/Component/Listing/Stock/Columns.php
  InventoryAdminUi/Ui/Component/Listing/Stock/MassAction.php
  InventoryAdminUi/view/adminhtml/ui_component/inventory_source_listing.xml
  InventoryAdminUi/view/adminhtml/ui_component/inventory_stock_listing.xml
  InventoryCatalogAdminUi/Ui/Component/AssignSources/Button.php
  InventoryCatalogAdminUi/Ui/Component/AssignSources/Record.php
  InventoryCatalogAdminUi/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithBundleProductCustomStockTest.xml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithConfigurableProductCustomStockTest.xml
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestCreateOrderWithGroupedProductCustomStockTest.xml
  InventorySales/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriority.php
  InventorySales/Test/Unit/Model/ReturnProcessor/GetInvoicedItemsPerSourceByPriorityTest.php
Labels: 2.4-develop: :one:, in progress

#3146 Delete test image after test execution
  InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontPickUpSourceInfoSimpleProductCustomStockTest.xml
Labels: Priority: P1, Progress: approved

#3143 MC-35486: Incorrect qty is returned for "Backorders with Notify Custo…
  InventorySales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php
  InventorySales/Test/Unit/Model/IsProductSalableCondition/BackOrderNotifyCustomerConditionTest.php
Labels: Progress: review, QA Passed

#3142 MC-35306 Incorrect qty is returned for "Backorders with Notify Customer"
  InventorySales/Model/IsProductSalableCondition/BackOrderNotifyCustomerCondition.php
  InventorySales/Test/Unit/Model/IsProductSalableCondition/BackOrderNotifyCustomerConditionTest.php
Labels: Progress: approved, QA Passed
