Repository magento/inventory, pull requests merged in 2020-05, with the labels that each got.

#2987 MC-32321: Cannot assign more than 20 sources to product
  InventoryAdminUi/Test/Mftf/Test/AdminAssignMultipleSourcesToProductTest.xml
  InventoryCatalogAdminUi/Observer/ProcessSourceItemsObserver.php
  InventoryLowQuantityNotificationAdminUi/Observer/ProcessSourceItemConfigurationsObserver.php
Labels: Progress: review, QA Passed

#2951 MC-32285: Cannot assign more than 20 sources to product
  InventoryAdminUi/Test/Mftf/Test/AdminAssignMultipleSourcesToProductTest.xml
  InventoryCatalogAdminUi/Observer/ProcessSourceItemsObserver.php
  InventoryLowQuantityNotificationAdminUi/Observer/ProcessSourceItemConfigurationsObserver.php
Labels: Progress: changes requested, QA Passed

#3005 inventory:reservation:list-inconsistencies command fails with split database config
  InventoryReservationCli/Model/ResourceModel/GetOrderDataForOrderInFinalState.php
  InventoryReservationCli/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalState.php
  InventoryReservationCli/Model/ResourceModel/GetOrdersTotalCount.php
  InventoryReservationCli/Test/Unit/Model/ResourceModel/GetOrderDataForOrderInFinalStateTest.php
  InventoryReservationCli/Test/Unit/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalStateTest.php
  InventoryReservationCli/Test/Unit/Model/ResourceModel/GetOrdersTotalCountTest.php
Labels: Progress: approved

#2977 inventory:reservation:list-inconsistencies command fails with split database config
  InventoryReservationCli/Model/ResourceModel/GetOrderDataForOrderInFinalState.php
  InventoryReservationCli/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalState.php
  InventoryReservationCli/Model/ResourceModel/GetOrdersTotalCount.php
Labels: Progress: approved, QA Passed

#3017 #27500 PHPUnit 9
  Inventory/Test/Unit/Model/SourceRepositoryTest.php
  InventoryImportExport/Test/Unit/Model/ValidatorChainTest.php
  InventoryInStorePickupMultishipping/Test/Unit/Controller/Checkout/PluginTest.php
  InventoryInStorePickupQuote/Test/Unit/Plugin/Quote/AddressCollection/GetPickupLocationInformationPluginTest.php
  InventoryMultiDimensionalIndexerApi/Test/Unit/IndexTableSwitcherTest.php
  InventoryReservationCli/Test/Unit/Model/ResourceModel/GetOrderDataForOrderInFinalStateTest.php
  InventoryReservationCli/Test/Unit/Model/ResourceModel/GetOrderItemsDataForOrdersInNotFinalStateTest.php
  InventoryReservationCli/Test/Unit/Model/ResourceModel/GetOrdersTotalCountTest.php
  InventoryReservations/Test/Unit/Model/ReservationBuilderTest.php
  InventoryReservations/Test/Unit/Model/SnakeToCamelCaseConverterTest.php
  InventorySales/Test/Unit/Model/IsProductSalableCondition/BackOrderNotifyCustomerConditionTest.php
Labels: Partner: Mediotype, Progress: review, partners-contribution

#3024 MQE-2109: Prepare green build with CE + EE + B2B + MSI + ASI + PB
  InventoryAdminUi/Test/Mftf/ActionGroup/AssignWebsiteToStockActionGroup.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateFullInvoiceForOrderWithSimpleProductOnCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminManageStockOnProductPageTurnedOffForSimpleProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminMassActionUnAssignAllProductSourcesFromSimpleProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminUserCreateOrderWithSimpleProductOnTestStockFromCustomWebsiteTest.xml
  InventoryAdminUi/Test/Mftf/Test/ReorderButtonGroupedProductOnTestStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromHomepageTest.xml
Labels: 1.2.0-develop, MFTF

#3009 [WIP]MFTF tests stabilization.
  InventoryAdminUi/Test/Mftf/ActionGroup/AssignWebsiteToStockActionGroup.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminManageStockOnProductPageTurnedOffForSimpleProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminMassActionUnAssignAllProductSourcesFromSimpleProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromHomepageTest.xml
Labels: 1.2.0-develop, Progress: approved

#3026 Async reservation
  InventoryIndexer/Model/Queue/RecalculateIndexSalabilityStatus.php
  InventoryIndexer/Plugin/InventorySales/EnqueueAfterPlaceReservationsForSalesEvent.php
  InventoryIndexer/etc/di.xml
Labels: Progress: review

#3044 Remove qty check during setQty method. Move Qty check before persist.
  InventorySales/Plugin/Quote/Api/ValidateQtyBeforeSave.php
  InventorySales/Plugin/Quote/Model/Quote/Item/CartItemPersister/ValidateQtyBeforePersist.php
  InventorySales/composer.json
  InventorySales/etc/di.xml
  InventorySales/etc/events.xml
Labels: Partner: Vaimo, partners-contribution

#2969 Async Indexer For Stock
  InventoryBundleProductIndexer/Plugin/InventoryIndexer/Indexer/SourceItem/Strategy/Sync/SourceItemIndexerPlugin.php
  InventoryBundleProductIndexer/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/ReindexFullPlugin.php
  InventoryBundleProductIndexer/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/ReindexListPlugin.php
  InventoryBundleProductIndexer/etc/di.xml
  InventoryCatalog/Model/BulkInventoryTransfer.php
  InventoryCatalog/Model/BulkPartialInventoryTransfer.php
  InventoryCatalog/Test/Integration/CatalogInventory/Api/StockRegistry/GetStockStatusAsyncReindexTest.php
  InventoryCatalogAdminUi/etc/adminhtml/system.xml
  InventoryConfigurableProductIndexer/Plugin/InventoryIndexer/Indexer/SourceItem/Strategy/Sync/SourceItemIndexerPlugin.php
  InventoryConfigurableProductIndexer/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/ReindexFullPlugin.php
  InventoryConfigurableProductIndexer/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/ReindexListPlugin.php
  InventoryConfigurableProductIndexer/etc/di.xml
  InventoryGroupedProductIndexer/Plugin/InventoryIndexer/Indexer/SourceItem/Strategy/Sync/SourceItemIndexerPlugin.php
  InventoryGroupedProductIndexer/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/ReindexFullPlugin.php
  InventoryGroupedProductIndexer/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/ReindexListPlugin.php
  InventoryGroupedProductIndexer/etc/di.xml
  InventoryIndexer/Indexer/SourceItem/SourceItemIndexer.php
  InventoryIndexer/Indexer/SourceItem/SourceItemReindexStrategy.php
  InventoryIndexer/Indexer/SourceItem/Strategy/Async.php
  InventoryIndexer/Indexer/SourceItem/Strategy/Sync.php
  InventoryIndexer/Indexer/Stock/StockIndexer.php
  InventoryIndexer/Indexer/Stock/StockReindexStrategy.php
  InventoryIndexer/Indexer/Stock/Strategy/Async.php
  InventoryIndexer/Indexer/Stock/Strategy/Sync.php
  InventoryIndexer/Model/IndexerConfig.php
  InventoryIndexer/Model/ReindexStrategyOptions.php
  InventoryIndexer/composer.json
  InventoryIndexer/etc/communication.xml
  InventoryIndexer/etc/config.xml
  InventoryIndexer/etc/di.xml
  InventoryIndexer/etc/queue_consumer.xml
  InventoryIndexer/etc/queue_publisher.xml
  InventoryIndexer/etc/queue_topology.xml
Labels: 1.2.0-develop, Award: advanced, Award: category of expertise, Award: special achievement, Partner: Comwrap, Progress: review, partners-contribution

#2972 Add caching of result for sql queries
  InventorySales/Model/GetStockBySalesChannelCache.php
  InventorySales/Model/ResourceModel/GetAssignedStockIdForWebsiteCache.php
  InventorySales/etc/di.xml
Labels: 1.2.0-develop, Progress: approved

#3043 MC-33114: AreProductsSalablePlugin should be available to check sale availability by scope of products
  InventoryAdvancedCheckout/Plugin/Model/AreProductsSalablePlugin.php
  InventoryAdvancedCheckout/composer.json
  InventoryAdvancedCheckout/etc/di.xml
Labels: Progress: approved

#3037 MC-18332 MySQL search engine removal
  InventoryCatalogSearch/Plugin/Model/Adapter/Mysql/Aggregation/DataProvider/SelectBuilderForAttribute/AdaptApplyStockConditionToSelectPlugin.php
  InventoryCatalogSearch/Plugin/Model/Search/FilterMapper/TermDropdownStrategy/AdaptApplyStockConditionToSelectPlugin.php
  InventoryCatalogSearch/Plugin/Search/FilterMapper/AdaptStockStatusFilterPlugin.php
  InventoryCatalogSearch/Test/Integration/Model/Adapter/Mysql/Aggregation/DataProvider/ApplyStockConditionToSelectTest.php
  InventoryCatalogSearch/Test/Integration/Model/Adapter/Mysql/Aggregation/DataProvider/ApplyStockConditionToSelectWithDefaultStockTest.php
  InventoryCatalogSearch/Test/Integration/Model/Search/FilterMapper/TermDropdownStrategy/ApplyStockConditionToSelectOnDefaultStockTest.php
  InventoryCatalogSearch/Test/Integration/Model/Search/FilterMapper/TermDropdownStrategy/ApplyStockConditionToSelectTest.php
  InventoryCatalogSearch/composer.json
  InventoryCatalogSearch/etc/di.xml
Labels: 1.2.0-develop

#3051 [TR]: MySQL8 Support
  Inventory/etc/db_schema.xml
  InventoryInStorePickupQuote/etc/db_schema.xml
  InventoryInStorePickupSales/etc/db_schema.xml
  InventoryReservations/etc/db_schema.xml
  InventorySales/etc/db_schema.xml
  InventoryShipping/etc/db_schema.xml
Labels: Partner: TechDivision, partners-contribution

#3063 Add index to stock index table.
  InventoryIndexer/Indexer/IndexStructure.php
Labels: Partner: Vaimo, Progress: approved, partners-contribution
