Repository magento/inventory, pull requests merged in 2020-03, with the labels that each got.

#2855 [TSG] MC-29184: Unexpected message appears if you try to add products to order via admin panel
  InventorySalesAdminUi/Test/Mftf/Test/AdminAddSelectedProductToOrderTest.xml
Labels: Progress: approved

#2849 [TSG] MC-25026: MFTF TASK FOR MC-6080 (MC-25681)
  Inventory/Test/Mftf/Test/SkippedTest.xml
Labels: Progress: approved

#2795 MSI-2724: Inventory is not updated when Product SKU is changed.
  Inventory/Test/Mftf/Test/AdminCreateVirtualProductWithDefaultSourceTest.xml
  InventoryAdminUi/Test/Mftf/ActionGroup/AdminChangeProductSkuActionGroup.xml
  InventoryAdminUi/Test/Mftf/ActionGroup/AdminCreateCreditMemoReturnToStockActionGroup.xml
  InventoryAdminUi/Test/Mftf/Data/CatalogInventoryConfigData.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoSimpleProductWithChangedSkuDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithChangedSimpleProductIntoConfigurableDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentWithDeletedSimpleProductDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCustomNotifyQuantityAppliedOnProductPageToDownloadableProductOnDefaultSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminManageStockOnProductPageTurnedOffForDownloadableProductInTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminOutOfStockThresholdAppliedToDownloadableProductInAdvancedInventoryOnProductPageTest.xml
  InventoryAdminUi/Test/Mftf/Test/CatalogPriceRuleSimpleProductAdditionalStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/GuestCustomerCreateOrderWithSimpleProductOnCustomStockTest.xml
  InventoryCatalog/Model/DeleteSourceItemsBySkus.php
  InventoryCatalog/Plugin/Catalog/Model/ResourceModel/Product/CreateSourceItemsPlugin.php
  InventoryCatalog/Plugin/Catalog/Model/ResourceModel/Product/DeleteSourceItemsPlugin.php
  InventoryCatalog/Plugin/Catalog/Model/ResourceModel/Product/ProcessSourceItemsPlugin.php
  InventoryCatalog/Test/Api/DeleteProductTest.php
  InventoryCatalog/Test/Api/UpdateProductSkuTest.php
  InventoryCatalog/Test/Api/UpdateProductTypeTest.php
  InventoryCatalog/etc/communication.xml
  InventoryCatalog/etc/config.xml
  InventoryCatalog/etc/di.xml
  InventoryCatalog/etc/queue.xml
  InventoryCatalog/etc/queue_consumer.xml
  InventoryCatalog/etc/queue_publisher.xml
  InventoryCatalog/etc/queue_topology.xml
  InventoryCatalog/etc/webapi_rest/di.xml
  InventoryCatalog/etc/webapi_soap/di.xml
  InventoryCatalogAdminUi/etc/adminhtml/system.xml
  InventoryImportExport/Observer/DeleteSourceItemsAfterProductDeleteObserver.php
  InventoryImportExport/Observer/ProcessReservationsAfterProductImportObserver.php
  InventoryImportExport/etc/events.xml
  InventoryLowQuantityNotification/Model/ResourceModel/SourceItemConfiguration/GetBySku.php
  InventoryLowQuantityNotification/Plugin/Catalog/Model/ResourceModel/Product/CreateSourceItemConfigurationPlugin.php
  InventoryLowQuantityNotification/Plugin/Inventory/Model/ResourceModel/SourceItem/DeleteMultiple/DeleteSourceItemsConfigurationPlugin.php
  InventoryLowQuantityNotification/Test/Api/DeleteProductTest.php
  InventoryLowQuantityNotification/Test/Api/UpdateProductSkuTest.php
  InventoryLowQuantityNotification/etc/di.xml
  InventoryLowQuantityNotification/etc/webapi_rest/di.xml
  InventoryLowQuantityNotification/etc/webapi_soap/di.xml
  InventorySales/Model/ResourceModel/DeleteReservationsBySkus.php
  InventorySales/Model/ResourceModel/UpdateReservationsBySkus.php
  InventorySales/Plugin/Catalog/Model/ResourceModel/Product/DeleteReservationsPlugin.php
  InventorySales/Plugin/Catalog/Model/ResourceModel/Product/UpdateReservationsPlugin.php
  InventorySales/Plugin/Catalog/Model/SkuDataForReservationUpdate.php
  InventorySales/etc/communication.xml
  InventorySales/etc/di.xml
  InventorySales/etc/queue.xml
  InventorySales/etc/queue_consumer.xml
  InventorySales/etc/queue_publisher.xml
  InventorySales/etc/queue_topology.xml
  InventoryShipping/Model/GetItemsToDeductFromShipment.php
  InventoryShippingAdminUi/Model/IsOrderSourceManageable.php
  InventorySourceDeductionApi/Model/IsItemCouldBeDeductedByTypes.php
Labels: Progress: review

#2848 [TSG] MC-29851: Unexpected message appears if you try to add products to order via admin panel
  InventorySalesAdminUi/Test/Mftf/Test/AdminAddSelectedProductToOrderTest.xml
Labels: Progress: approved

#2850 #2299 : manage stock = no but showing only X left
  InventorySalesFrontendUi/Plugin/Block/Stockqty/AbstractStockqtyPlugin.php
  InventorySalesFrontendUi/Test/Mftf/Test/UserApplyOnlyXLeftThresholdDisabledManageStockForSimpleProductTest.xml
Labels: Progress: approved, QA Passed

#2856 #26989 MFTF: Use <magentoCron> for reindex
  InventoryAdminUi/Test/Mftf/Test/AdminCancelOrderConfigurableProductWithDropDownAttributeAndCustomSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoWholeOrderWithConfigurableProductFromCustomSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateScheduledPermanentUpdateConfigurableProductCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateScheduledPermanentUpdateConfigurableProductDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithConfigurableProductFromCustomSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateShipmentForWholeOrderWithConfigurableProductFromDefaultSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminInvoiceCreatedForWholeOrderWithConfigurableProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnDefaultStockFromAdminTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontBackordersEnabledOnConfigurationPageAndAppliedFromHomepageToWithConfigurableProductWithDropDownAttributeAndVariablesAssignedToNonDefaultSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontButtonReorderForTheOrderWithConfigurableProductOnDefaultStockInCustomerCabinetOnHomepageIsNotPresentIfProductSoldOutTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerOrderConfigurableProductWithDropDownAttributeAndCustomSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerOrderConfigurableProductWithDropDownAttributeAndDefaultSourceTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontPartialInvoiceCreatedForOrderWithConfigurableProductInAdminTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontPriceOfConfigurableProductAssignedToTestStockAndTestWebsiteWhenOptionOfDisplayingOutOfStockProductsEnabledTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontQuickOrderConfigurableProductsCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontSalableQuantityOnNonDefaultStockForConfigurableProductWithDropDownAttributeAfterPlacingOrderCountedCorrectlyTest.xml
Labels: Partner: Mediotype, Progress: approved, partners-contribution

#2865 UX Text - Max Actions Transfer Inventory to Source
  InventoryCatalogAdminUi/Controller/Adminhtml/Inventory/BulkTransferPost.php
  InventoryCatalogAdminUi/view/adminhtml/templates/inventory_transfer.phtml
Labels: Progress: approved

#2868 #1389 :- Add tooltip to Product grid as well as Product page describing what is "Salable Quantity"
  InventorySalesAdminUi/i18n/en_US.csv
  InventorySalesAdminUi/view/adminhtml/ui_component/product_form.xml
  InventorySalesAdminUi/view/adminhtml/web/css/source/_module.less
  InventorySalesAdminUi/view/adminhtml/web/template/product/form/fieldset.html
Labels: Progress: approved, QA Passed

#2839 MSI-2826-Hide-store-pickup-during-order-submissions-if-one-of-the-products-is-not-available-for-pickup.
  InventoryInStorePickup/Model/ProductInfo.php
  InventoryInStorePickup/Model/ResourceModel/GetPickupLocationIntersectionForSkus.php
  InventoryInStorePickup/Model/SearchCriteria/ResolveIntersection.php
  InventoryInStorePickup/composer.json
  InventoryInStorePickup/etc/di.xml
  InventoryInStorePickup/etc/module.xml
  InventoryInStorePickupApi/Api/Data/SearchRequest/FiltersInterface.php
  InventoryInStorePickupApi/Api/Data/SearchRequest/ProductInfoInterface.php
  InventoryInStorePickupApi/Test/Api/GetPickupLocationsTest.php
  InventoryInStorePickupApi/Test/_files/source_all_pickup_locations.php
  InventoryInStorePickupApi/etc/extension_attributes.xml
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-pickup.js
  InventoryInStorePickupFrontend/view/frontend/web/js/view/store-selector.js
  InventoryInStorePickupShipping/etc/di.xml
Labels: Auto-Tests: Covered, Award: complex, Award: special achievement, Award: test coverage, Partner: Vaimo, Progress: approved, partners-contribution

#2751 Remove "Ship" functionality for store pickup orders.
  InventoryInStorePickupSales/Model/NotifyOrdersAreReadyForPickup.php
  InventoryInStorePickupSales/Model/NotifyOrdersAreReadyForPickupEmailSender.php
  InventoryInStorePickupSales/Model/Order/AddStorePickupAttributesToOrder.php
  InventoryInStorePickupSales/Model/Order/CreateShippingArguments.php
  InventoryInStorePickupSales/Model/Order/Email/ReadyForPickupNotifier.php
  InventoryInStorePickupSales/Model/Order/Email/ReadyForPickupSender.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/GetOrderNotificationSentByOrderId.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/GetOrderSendNotificationByOrderId.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderNotification/SaveOrderNotification.php
  InventoryInStorePickupSales/Observer/NotifyOrdersAreReadyForPickupSendEmailObserver.php
  InventoryInStorePickupSales/Plugin/Sales/Order/ShipmentRepository/AdaptShipmentPlugin.php
  InventoryInStorePickupSales/Test/Integration/NotifyOrdersAreReadyForPickupTest.php
  InventoryInStorePickupSales/etc/acl.xml
  InventoryInStorePickupSales/etc/crontab.xml
  InventoryInStorePickupSales/etc/db_schema.xml
  InventoryInStorePickupSales/etc/db_schema_whitelist.json
  InventoryInStorePickupSales/etc/events.xml
  InventoryInStorePickupSales/etc/webapi.xml
  InventoryInStorePickupSales/etc/webapi_rest/di.xml
  InventoryInStorePickupSales/etc/webapi_soap/di.xml
  InventoryInStorePickupSalesApi/Api/Data/ResultInterface.php
  InventoryInStorePickupSalesApi/Api/NotifyOrdersAreReadyForPickupInterface.php
  InventoryInStorePickupSalesApi/etc/extension_attributes.xml
Labels: Progress: review, QA Passed, Store Pickup

#2869 #2816 : "This is a required field" error is shown after assigning source to the product
  InventoryCatalogAdminUi/Test/Js/product/form/sources/qty.test.js
  InventoryCatalogAdminUi/view/adminhtml/ui_component/product_form.xml
  InventoryCatalogAdminUi/view/adminhtml/web/js/product/form/sources/qty.js
Labels: Award: bug fix, Progress: approved, QA Passed

#2879 Update link to CLA in contribution docs
  .github/CONTRIBUTING.md
Labels: Progress: approved

#2880 add copying.txt copyright info
  COPYING.txt
Labels: Progress: approved

#2872 Remove inventory reservations based on orders
  InventoryReservations/Model/ResourceModel/CleanupReservations.php
Labels: Partner: Reach Digital, Progress: approved, QA Passed, partners-contribution

#2871 [TSG] MC-32302: Error on Backend Orders Page after split database
  InventoryShippingAdminUi/Model/ResourceModel/GetAllocatedSourcesForOrder.php
  InventoryShippingAdminUi/Test/Integration/Model/ResourceModel/GetAllocatedSourcesForOrderTest.php
Labels: Progress: review

#2885 MSI-2864: Cannot ship product if user doesn't have permission to edit Source configurations.
  InventoryShippingAdminUi/Controller/Adminhtml/SourceSelection/Index.php
  InventoryShippingAdminUi/Controller/Adminhtml/SourceSelection/ProcessAlgorithm.php
  InventoryShippingAdminUi/Controller/Adminhtml/SourceSelection/Validate.php
Labels: QA Passed

#2888 MFTF: Fix failing test caused by loading mask still visible
  InventoryAdminUi/Test/Mftf/Test/LoggedInCustomerReorderSimpleProductOnTestStockTest.xml
Labels: Partner: Mediotype, Progress: approved, partners-contribution

#2890 MC-30568: Shared indexers have invalid status after full reindex
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerCreateOrderAllOptionQuantityConfigurableProductCustomStockTest.xml
Labels: Progress: approved

#2892 MSI-2583[BackPort]: Unchecked Notify Quantity "Use Default" Not Saved after Product Save.
  InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceTransferringNotifyQuantityForDifferentTypesOfProductsTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceTransferringNotifyQuantityForSimpleProductsTest.xml
  InventoryAdminUi/Test/Mftf/Test/LowStockNotificationAppliedOnConfigurationPageSimpleProductDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/LowStockNotificationAppliedOnConfigurationPageVirtualProductDefaultStockTest.xml
  InventoryCatalog/Plugin/Catalog/Model/ResourceModel/Product/CreateSourceItemsPlugin.php
  InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
  InventoryLowQuantityNotification/Model/SourceItemsConfigurationProcessor.php
  InventoryLowQuantityNotification/Plugin/Catalog/Model/ResourceModel/Product/CreateSourceItemConfigurationPlugin.php
  InventoryLowQuantityNotification/Plugin/Catalog/Model/ResourceModel/Product/ProcessDefaultSourceItemConfigurationPlugin.php
  InventoryLowQuantityNotification/etc/webapi_rest/di.xml
  InventoryLowQuantityNotification/etc/webapi_soap/di.xml
  InventoryLowQuantityNotificationAdminUi/Observer/ProcessSourceItemConfigurationsObserver.php
  InventoryLowQuantityNotificationAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php
Labels: Progress: approved, QA Passed

#2893 [trigger] MC-23540: Elasticsearch 7.x.x Upgrade
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchQuickAdvancedSearchAdditionalStockProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchQuickAdvancedSearchDefaultStockProductTest.xml
Labels: Progress: approved

#2891 MSI-2583: Unchecked Notify Quantity "Use Default" Not Saved after Product Save.
  InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceTransferringNotifyQuantityForDifferentTypesOfProductsTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminMassActionTransferInventoryToSourceTransferringNotifyQuantityForSimpleProductsTest.xml
  InventoryAdminUi/Test/Mftf/Test/LowStockNotificationAppliedOnConfigurationPageSimpleProductDefaultStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/LowStockNotificationAppliedOnConfigurationPageVirtualProductDefaultStockTest.xml
  InventoryCatalog/Plugin/Catalog/Model/ResourceModel/Product/CreateSourceItemsPlugin.php
  InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
  InventoryLowQuantityNotification/Model/SourceItemsConfigurationProcessor.php
  InventoryLowQuantityNotification/Plugin/Catalog/Model/ResourceModel/Product/CreateSourceItemConfigurationPlugin.php
  InventoryLowQuantityNotification/Plugin/Catalog/Model/ResourceModel/Product/ProcessDefaultSourceItemConfigurationPlugin.php
  InventoryLowQuantityNotification/etc/webapi_rest/di.xml
  InventoryLowQuantityNotification/etc/webapi_soap/di.xml
  InventoryLowQuantityNotificationAdminUi/Observer/ProcessSourceItemConfigurationsObserver.php
  InventoryLowQuantityNotificationAdminUi/Ui/DataProvider/Product/Form/Modifier/SourceItemConfiguration.php
Labels: Progress: approved, QA Passed

#2894 MC-31098: Add support of Elasticsearch7 to codebase
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchQuickAdvancedSearchAdditionalStockProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchQuickAdvancedSearchDefaultStockProductTest.xml
Labels: Progress: approved

#2863 Fix mftf
  InventoryAdminUi/Test/Mftf/Test/AdminCreateConfigurableProductWithSwatchAttributeMultipleStocksTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontLoggedInCustomerOrderConfigurableProductTextSwatchAttributeCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontOrderCreatedWithConfigurableProductWithSwatchAttributeTest.xml
Labels: 1.2-develop, Auto-Tests: Covered, Progress: approved

#2903 [TSG] MC-32581: [MSI][MFTF] AdminNotifyQuantityUseDefaultAppliedToVirtualPr…
  InventoryAdminUi/Test/Mftf/Test/AdminNotifyQuantityUseDefaultAppliedToVirtualProductOnConfigurationAdminPageTest.xml
Labels: Progress: approved

#2905 [TSG] MC-32577: [MSI][MFTF] StorefrontReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromHomepageTest fails because of bad design
  InventoryAdminUi/Test/Mftf/Test/AdminReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnDefaultStockFromAdminTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromAdminTest.xml
  InventoryAdminUi/Test/Mftf/Test/StorefrontReorderOfTheOrderWithConfigurableProductWithDropDownAttributeOnTestStockFromHomepageTest.xml
Labels: Progress: approved

#2877 Fix exception when a product is not assigned to all stocks during IsOrderSourceManageable check
  InventoryShippingAdminUi/Model/IsOrderSourceManageable.php
  InventoryShippingAdminUi/Test/Integration/Model/IsOrderSourceManageableTest.php
Labels: Progress: approved

#2896 MSI-2859: Extra compensation reservation when Credit Memo created.
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoPartialReturnToStockAfterFullInvoiceFullShipmentSimpleProductsCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/AdminCreateCreditMemoPartialReturnToStockAfterFullInvoiceSimpleProductsCustomStockTest.xml
  InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php
Labels: Progress: approved, QA Passed

#2901 MSI-2899: Low stock report in scope of website works incorrectly
  InventoryAdminUi/Test/Mftf/ActionGroup/AdminSwitchStoreViewNoConfirmationActionGroup.xml
  InventoryAdminUi/Test/Mftf/Test/AdminLowStockReportSimpleProductTwoWebsitesTest.xml
  InventoryLowQuantityNotification/Model/ResourceModel/LowQuantityCollection.php
Labels: Progress: approved

#2887 Test fix. Added data fixture websites_with_stores.php
  InventoryImportExport/Test/Integration/Model/ProductTestAdditionalStockTest.php
Labels: Auto-Tests: Covered, Award: bug fix, Progress: approved

#2906 [TSG] MC-32639: Error on Frontend while adding product to cart (with DB split)
  InventoryInStorePickupQuote/Model/ResourceModel/DeleteQuoteAddressPickupLocation.php
  InventoryInStorePickupQuote/Model/ResourceModel/GetPickupLocationCodeByQuoteAddressId.php
  InventoryInStorePickupQuote/Model/ResourceModel/SaveQuoteAddressPickupLocation.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderPickupLocation/GetPickupLocationCodeByOrderId.php
  InventoryInStorePickupSales/Model/ResourceModel/OrderPickupLocation/SaveOrderPickupLocation.php
  InventoryInStorePickupSales/etc/db_schema.xml
Labels: Progress: approved

#2907 MSI-2904: Fatal error in `inventory:reservation:list-inconsistencies`because of wrong sku parameter type.
  InventoryReservationCli/Model/SalableQuantityInconsistency/FilterManagedStockProducts.php
  InventoryReservationCli/Test/Integration/Model/GetSalableQuantityInconsistenciesTest.php
  InventoryReservationCli/Test/Integration/_files/create_incomplete_order_without_reservation_numeric_sku.php
  InventoryReservationCli/Test/Integration/_files/simple_product_numeric_sku.php
  InventoryReservationCli/Test/Integration/_files/simple_product_numeric_sku_rollback.php
Labels: Progress: approved, QA Passed

#2908 [TSG] MC-32882: [MFTF] Failing Tests in 2.3.5-develop
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationCustomStockTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchLayeredNavigationTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchQuickAdvancedSearchAdditionalStockProductTest.xml
  InventoryAdminUi/Test/Mftf/Test/ElasticSearchQuickAdvancedSearchDefaultStockProductTest.xml
Labels: Progress: approved

#2912 MSI-2904: Fatal error in `inventory:reservation:list-inconsistencies` because of wrong sku parameter type. [Backport]
  InventoryReservationCli/Model/SalableQuantityInconsistency/FilterManagedStockProducts.php
  InventoryReservationCli/Test/Integration/Model/GetSalableQuantityInconsistenciesTest.php
  InventoryReservationCli/Test/Integration/_files/create_incomplete_order_without_reservation_numeric_sku.php
  InventoryReservationCli/Test/Integration/_files/simple_product_numeric_sku.php
  InventoryReservationCli/Test/Integration/_files/simple_product_numeric_sku_rollback.php
Labels: Progress: approved
